/* GENERATED by scripts/generate.mjs from icons/outline/interface/toggle-on-circle.svg, icons/solid/interface/toggle-on-circle.svg. Do not edit by hand. */
import { IconBase } from "../../icon-base.js";
import type { QeetrixIconProps } from "../../types.js";

export function ToggleOnCircle({ variant = "outline", ...props }: QeetrixIconProps & { variant?: "outline" | "solid" }) {
  if (variant === "solid") {
    return (
      <IconBase variant={variant} {...props}>
        <path
          d="M13.86 3.85938H10.14C5.65 3.85938 2 7.50938 2 11.9994C2 16.4894 5.65 20.1394 10.14 20.1394H13.86C18.35 20.1394 22 16.4894 22 11.9994C22 7.50938 18.35 3.85938 13.86 3.85938ZM13.86 16.4194C11.42 16.4194 9.44 14.4394 9.44 11.9994C9.44 9.55938 11.42 7.57938 13.86 7.57938C16.3 7.57938 18.28 9.55938 18.28 11.9994C18.28 14.4394 16.3 16.4194 13.86 16.4194Z"
          fill="currentColor"
          fillRule="evenodd"
        />
      </IconBase>
    );
  }
  return (
    <IconBase variant={variant} {...props}>
      <path
        d="M14 20.75H10C5.17 20.75 1.25 16.82 1.25 12C1.25 7.18 5.17 3.25 10 3.25H14C18.83 3.25 22.75 7.18 22.75 12C22.75 16.82 18.83 20.75 14 20.75ZM10 4.75C6 4.75 2.75 8 2.75 12C2.75 16 6 19.25 10 19.25H14C18 19.25 21.25 16 21.25 12C21.25 8 18 4.75 14 4.75H10Z"
        fill="currentColor"
      />
      <path
        d="M14 16.75C11.38 16.75 9.25 14.62 9.25 12C9.25 9.38 11.38 7.25 14 7.25C16.62 7.25 18.75 9.38 18.75 12C18.75 14.62 16.62 16.75 14 16.75ZM14 8.75C12.21 8.75 10.75 10.21 10.75 12C10.75 13.79 12.21 15.25 14 15.25C15.79 15.25 17.25 13.79 17.25 12C17.25 10.21 15.79 8.75 14 8.75Z"
        fill="currentColor"
      />
    </IconBase>
  );
}
