/* GENERATED by scripts/generate.mjs from icons/arrows/arrow-down.svg. Do not edit by hand. */
import { IconBase } from "../icon-base.js";
import type { QeetrixIconProps } from "../types.js";

export function ArrowDown(props: QeetrixIconProps) {
  return (
    <IconBase {...props}>
      <path d="M12 4v16" />
      <path d="m6 14 6 6 6-6" />
    </IconBase>
  );
}
