/* GENERATED by scripts/generate.mjs from icons/accessibility/captions-off.svg. Do not edit by hand. */
import { IconBase } from "../icon-base.js";
import type { QeetrixIconProps } from "../types.js";

export function CaptionsOff(props: QeetrixIconProps) {
  return (
    <IconBase {...props}>
      <rect x="2" y="5" width="20" height="14" rx="2" />
      <path d="M9.5 10.5a2.5 2.5 0 1 0 0 3" />
      <path d="M17 10.5a2.5 2.5 0 1 0 0 3" />
      <path d="M3 3 21 21" />
    </IconBase>
  );
}
