/* GENERATED by scripts/generate.mjs from icons/data/chart-area.svg. Do not edit by hand. */
import { IconBase } from "../icon-base.js";
import type { QeetrixIconProps } from "../types.js";

export function ChartArea(props: QeetrixIconProps) {
  return (
    <IconBase {...props}>
      <path d="M3 20h18M3 20V4" />
      <path d="M6 20v-5l4-4 4 3 5-6v12z" />
    </IconBase>
  );
}
