/* GENERATED by scripts/generate.mjs from icons/navigation/chevrons-down.svg. Do not edit by hand. */
import { IconBase } from "../icon-base.js";
import type { QeetrixIconProps } from "../types.js";

export function ChevronsDown(props: QeetrixIconProps) {
  return (
    <IconBase {...props}>
      <path d="M6 7l6 6 6-6" />
      <path d="M6 13l6 6 6-6" />
    </IconBase>
  );
}
