/* GENERATED by scripts/generate.mjs from icons/editing/clipboard-list.svg. Do not edit by hand. */
import { IconBase } from "../icon-base.js";
import type { QeetrixIconProps } from "../types.js";

export function ClipboardList(props: QeetrixIconProps) {
  return (
    <IconBase {...props}>
      <rect x="9" y="2" width="6" height="4" rx="1" />
      <path d="M9 4H7a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2h-2" />
      <path d="M9 12h6M9 16h4" />
    </IconBase>
  );
}
