/* GENERATED by scripts/generate.mjs from icons/files/file-lock.svg. Do not edit by hand. */
import { IconBase } from "../icon-base.js";
import type { QeetrixIconProps } from "../types.js";

export function FileLock(props: QeetrixIconProps) {
  return (
    <IconBase {...props}>
      <path d="M14 3H7a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8z" />
      <path d="M14 3v5h5" />
      <rect x="9.5" y="14" width="5" height="4" rx="1" />
      <path d="M10.75 14v-1a1.25 1.25 0 0 1 2.5 0v1" />
    </IconBase>
  );
}
