/* GENERATED by scripts/generate.mjs from icons/files/file-image.svg. Do not edit by hand. */
import { IconBase } from "../icon-base.js";
import type { QeetrixIconProps } from "../types.js";

export function FileImage(props: QeetrixIconProps) {
  return (
    <IconBase {...props}>
      <path d="M14 3H7a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8z" />
      <path d="M14 3v5h5" />
      <circle cx="10.5" cy="12.5" r="1.5" />
      <path d="M7 18l3-3 2 2 2-2 3 3" />
    </IconBase>
  );
}
