/* GENERATED by scripts/generate.mjs from icons/security/fingerprint.svg. Do not edit by hand. */
import { IconBase } from "../icon-base.js";
import type { QeetrixIconProps } from "../types.js";

export function Fingerprint(props: QeetrixIconProps) {
  return (
    <IconBase {...props}>
      <path d="M12 4a8 8 0 0 1 8 8c0 2.6-.6 5.1-1.8 7.4" />
      <path d="M12 4a8 8 0 0 0-8 8c0 2.6.6 5.1 1.8 7.4" />
      <path d="M12 8.5a3.5 3.5 0 0 1 3.5 3.5c0 2.4-.5 4.7-1.4 6.8" />
      <path d="M12 8.5a3.5 3.5 0 0 0-3.5 3.5c0 2.4.5 4.7 1.4 6.8" />
      <path d="M12 12.5v6.5" />
    </IconBase>
  );
}
