/* GENERATED by scripts/generate.mjs from icons/files/folder.svg. Do not edit by hand. */
import { IconBase } from "../icon-base.js";
import type { QeetrixIconProps } from "../types.js";

export function Folder(props: QeetrixIconProps) {
  return (
    <IconBase {...props}>
      <path d="M3 8V6a1 1 0 0 1 1-1h4l2 2h9a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1z" />
    </IconBase>
  );
}
