/* GENERATED by scripts/generate.mjs from icons/files/folder-lock.svg. Do not edit by hand. */
import { IconBase } from "../icon-base.js";
import type { QeetrixIconProps } from "../types.js";

export function FolderLock(props: QeetrixIconProps) {
  return (
    <IconBase {...props}>
      <path d="M3 8V6a1 1 0 0 1 1-1h4l2 2h9a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1z" />
      <rect x="9.5" y="12" width="5" height="4" rx="1" />
      <path d="M10.75 12v-1a1.25 1.25 0 0 1 2.5 0v1" />
    </IconBase>
  );
}
