/* GENERATED by scripts/generate.mjs from icons/communication/forward.svg. Do not edit by hand. */
import { IconBase } from "../icon-base.js";
import type { QeetrixIconProps } from "../types.js";

export function Forward(props: QeetrixIconProps) {
  return (
    <IconBase {...props}>
      <path d="M14 9l5 5-5 5" />
      <path d="M19 14h-7a7 7 0 0 1-7-7V5" />
    </IconBase>
  );
}
