/* GENERATED by scripts/generate.mjs from icons/communication/mail-plus.svg. Do not edit by hand. */
import { IconBase } from "../icon-base.js";
import type { QeetrixIconProps } from "../types.js";

export function MailPlus(props: QeetrixIconProps) {
  return (
    <IconBase {...props}>
      <rect x="2" y="7" width="12" height="10.5" rx="2" />
      <path d="M2 8.2l6 4.2L14 8.2" />
      <path d="M18.5 3.5v6M15.5 6.5h6" />
    </IconBase>
  );
}
