/* GENERATED by scripts/generate.mjs from icons/communication/message-square-search.svg. Do not edit by hand. */
import { IconBase } from "../icon-base.js";
import type { QeetrixIconProps } from "../types.js";

export function MessageSquareSearch(props: QeetrixIconProps) {
  return (
    <IconBase {...props}>
      <path d="M21 15a2 2 0 0 1-2 2H8l-4 4V6a2 2 0 0 1 2-2h13a2 2 0 0 1 2 2z" />
      <circle cx="12" cy="10" r="2.5" />
      <path d="M13.8 11.8 15.5 13.5" />
    </IconBase>
  );
}
