/* GENERATED by scripts/generate.mjs from icons/devices/monitor.svg. Do not edit by hand. */
import { IconBase } from "../icon-base.js";
import type { QeetrixIconProps } from "../types.js";

export function Monitor(props: QeetrixIconProps) {
  return (
    <IconBase {...props}>
      <rect x="2" y="4" width="20" height="13" rx="2" />
      <path d="M8 21h8" />
      <path d="M12 17v4" />
    </IconBase>
  );
}
