/* GENERATED by scripts/generate.mjs from icons/arrows/move.svg. Do not edit by hand. */
import { IconBase } from "../icon-base.js";
import type { QeetrixIconProps } from "../types.js";

export function Move(props: QeetrixIconProps) {
  return (
    <IconBase {...props}>
      <path d="M12 3v18" />
      <path d="M3 12h18" />
      <path d="M9 6l3-3 3 3M9 18l3 3 3-3M6 9l-3 3 3 3M18 9l3 3-3 3" />
    </IconBase>
  );
}
