/* GENERATED by scripts/generate.mjs from icons/design/palette.svg. Do not edit by hand. */
import { IconBase } from "../icon-base.js";
import type { QeetrixIconProps } from "../types.js";

export function Palette(props: QeetrixIconProps) {
  return (
    <IconBase {...props}>
      <path d="M12 3a9 9 0 1 0 0 18c1.1 0 2-.9 2-2 0-1.7 1.3-3 3-3h2a2 2 0 0 0 2-2 9 9 0 0 0-9-9z" />
      <path d="M8 9h.01M7 13h.01M11 7h.01" />
    </IconBase>
  );
}
