/* GENERATED by scripts/generate.mjs from icons/security/password.svg. Do not edit by hand. */
import { IconBase } from "../icon-base.js";
import type { QeetrixIconProps } from "../types.js";

export function Password(props: QeetrixIconProps) {
  return (
    <IconBase {...props}>
      <rect x="3" y="8" width="18" height="8" rx="2" />
      <path d="M7 12h.01M11 12h.01M15 12h.01" />
    </IconBase>
  );
}
