/* GENERATED by scripts/generate.mjs from icons/interface/plus-square.svg. Do not edit by hand. */
import { IconBase } from "../icon-base.js";
import type { QeetrixIconProps } from "../types.js";

export function PlusSquare(props: QeetrixIconProps) {
  return (
    <IconBase {...props}>
      <rect x="4" y="4" width="16" height="16" rx="2" />
      <path d="M12 8v8" />
      <path d="M8 12h8" />
    </IconBase>
  );
}
