/* GENERATED by scripts/generate.mjs from icons/security/shield-x.svg. Do not edit by hand. */
import { IconBase } from "../icon-base.js";
import type { QeetrixIconProps } from "../types.js";

export function ShieldX(props: QeetrixIconProps) {
  return (
    <IconBase {...props}>
      <path d="M12 3l8 3v6c0 5-3.5 8-8 9-4.5-1-8-4-8-9V6z" />
      <path d="M14.5 9.5l-5 5M9.5 9.5l5 5" />
    </IconBase>
  );
}
