/* GENERATED by scripts/generate.mjs from icons/interface/sort-asc.svg. Do not edit by hand. */
import { IconBase } from "../icon-base.js";
import type { QeetrixIconProps } from "../types.js";

export function SortAsc(props: QeetrixIconProps) {
  return (
    <IconBase {...props}>
      <path d="M4 7h11M4 12h7M4 17h4" />
      <path d="M18 18V6" />
      <path d="M15 9l3-3 3 3" />
    </IconBase>
  );
}
