/* GENERATED by scripts/generate.mjs from icons/data/trending-down.svg. Do not edit by hand. */
import { IconBase } from "../icon-base.js";
import type { QeetrixIconProps } from "../types.js";

export function TrendingDown(props: QeetrixIconProps) {
  return (
    <IconBase {...props}>
      <path d="M3 7l6 6 4-4 8 8" />
      <path d="M15 17h6v-6" />
    </IconBase>
  );
}
