/* GENERATED by scripts/generate.mjs from icons/users/user-search.svg. Do not edit by hand. */
import { IconBase } from "../icon-base.js";
import type { QeetrixIconProps } from "../types.js";

export function UserSearch(props: QeetrixIconProps) {
  return (
    <IconBase {...props}>
      <circle cx="10" cy="8" r="4" />
      <path d="M18 21v-2a5 5 0 0 0-5-5H7a5 5 0 0 0-5 5v2" />
      <circle cx="18" cy="7" r="2.5" />
      <path d="M19.8 8.8 22 11" />
    </IconBase>
  );
}
