/* GENERATED by scripts/generate.mjs from icons/utilities/zap.svg. Do not edit by hand. */
import { IconBase } from "../icon-base.js";
import type { QeetrixIconProps } from "../types.js";

export function Zap(props: QeetrixIconProps) {
  return (
    <IconBase {...props}>
      <path d="M13 2L4 14h7l-1 8 9-12h-7z" />
    </IconBase>
  );
}
