/* GENERATED by scripts/generate.mjs from icons/outline/communication/message-add-alt.svg, icons/solid/communication/message-add-alt.svg. Do not edit by hand. */
import { IconBase } from "../../icon-base.js";
import type { QeetrixIconProps } from "../../types.js";

export function MessageAddAlt({ variant = "outline", ...props }: QeetrixIconProps & { variant?: "outline" | "solid" }) {
  if (variant === "solid") {
    return (
      <IconBase variant={variant} {...props}>
        <path
          d="M16 2H8C4 2 2 4 2 8V21C2 21.55 2.45 22 3 22H16C20 22 22 20 22 16V8C22 4 20 2 16 2ZM15.5 12.75H12.75V15.5C12.75 15.91 12.41 16.25 12 16.25C11.59 16.25 11.25 15.91 11.25 15.5V12.75H8.5C8.09 12.75 7.75 12.41 7.75 12C7.75 11.59 8.09 11.25 8.5 11.25H11.25V8.5C11.25 8.09 11.59 7.75 12 7.75C12.41 7.75 12.75 8.09 12.75 8.5V11.25H15.5C15.91 11.25 16.25 11.59 16.25 12C16.25 12.41 15.91 12.75 15.5 12.75Z"
          fill="currentColor"
          fillRule="evenodd"
        />
      </IconBase>
    );
  }
  return (
    <IconBase variant={variant} {...props}>
      <path
        d="M16 22.75H3C2.04 22.75 1.25 21.96 1.25 21V8C1.25 3.58 3.58 1.25 8 1.25H16C20.42 1.25 22.75 3.58 22.75 8V16C22.75 20.42 20.42 22.75 16 22.75ZM8 2.75C4.42 2.75 2.75 4.42 2.75 8V21C2.75 21.14 2.86 21.25 3 21.25H16C19.58 21.25 21.25 19.58 21.25 16V8C21.25 4.42 19.58 2.75 16 2.75H8Z"
        fill="currentColor"
      />
      <path
        d="M15.5 12.75H8.5C8.09 12.75 7.75 12.41 7.75 12C7.75 11.59 8.09 11.25 8.5 11.25H15.5C15.91 11.25 16.25 11.59 16.25 12C16.25 12.41 15.91 12.75 15.5 12.75Z"
        fill="currentColor"
      />
      <path
        d="M12 16.25C11.59 16.25 11.25 15.91 11.25 15.5V8.5C11.25 8.09 11.59 7.75 12 7.75C12.41 7.75 12.75 8.09 12.75 8.5V15.5C12.75 15.91 12.41 16.25 12 16.25Z"
        fill="currentColor"
      />
    </IconBase>
  );
}
