import type { FilledRecipe } from "../scripts/lib/filled.js";

/**
 * Icons that get a filled drawing, derived from their Lucide outline by `bun run derive:filled`.
 *
 * Lucide is outline-only, so filled drawings are a Qeetrix addition. An icon is listed only when
 * its outline derives into a clean, consistent solid form: bodies filled to the outline's painted
 * extent, details cut as negative lines of stroke width, and crossing lines cleared by a gap.
 * Open-line icons (arrows, chevrons, text marks, charts on axes) and outlines whose meaning or
 * detail does not survive filling are deliberately absent. Every entry was reviewed visually.
 *
 * Entries are grouped by source category. An empty recipe infers every element's role; `roles`
 * overrides it by element index in the outline source. See docs/filled.md for the roles and the
 * review routine.
 */
export const filledRecipes: Readonly<Record<string, FilledRecipe>> = {
  // Accessibility
  baby: {},
  "badge-question-mark": {},
  "circle-question-mark": {},
  "closed-caption": {},
  eye: {},
  "eye-off": {},
  glasses: {},
  info: {},
  "life-buoy": {},
  moon: {},
  "moon-star": {},
  speech: {},
  sun: {},
  "sun-dim": {},
  "sun-medium": {},
  "sun-moon": {},
  "zoom-in": {},
  "zoom-out": {},

  // Accounts & access
  award: {},
  badge: {},
  "badge-alert": {},
  "badge-info": {},
  ban: {},
  bell: {},
  "bell-dot": {},
  "book-user": {},
  bookmark: {},
  "bookmark-check": {},
  "bookmark-minus": {},
  "bookmark-off": {},
  "bookmark-plus": {},
  "bookmark-x": {},
  building: {},
  "circle-user": {},
  "circle-user-round": {},
  contact: {},
  "contact-round": {},
  cookie: {},
  "credit-card": {},
  "credit-card-check": {},
  "credit-card-minus": {},
  "credit-card-x": {},
  "file-user": {},
  flag: {},
  inbox: {},
  "message-circle-x": {},
  "notebook-tabs": {},
  settings: {},
  "share-2": {},
  shield: {},
  "shield-alert": {},
  "shield-ban": {},
  "shield-check": {},
  "shield-cog": {},
  "shield-ellipsis": {},
  "shield-keyhole": {},
  "shield-minus": {},
  "shield-off": {},
  "shield-plus": {},
  "shield-question-mark": {},
  "shield-user": {},
  "shield-x": {},
  "square-user": {},
  "square-user-round": {},
  star: {},
  "star-check": {},
  "star-minus": {},
  "star-plus": {},
  tag: {},
  "thumbs-down": {},
  "thumbs-up": {},
  ticket: {},
  user: {},
  "user-check": {},
  "user-lock": {},
  "user-minus": {},
  "user-plus": {},
  "user-round": {},
  "user-x": {},
  users: {},
  "users-round": {},
  "venetian-mask": {},
  "wallet-cards": {},
  "wallet-minimal": {},
  wrench: {},

  // Animals
  bird: {},
  bone: {},
  cat: {},
  dog: {},
  panda: {},
  "paw-print": {},
  squirrel: {},

  // Arrows
  "arrow-big-down": {},
  "arrow-big-down-dash": {},
  "arrow-big-left": {},
  "arrow-big-left-dash": {},
  "arrow-big-right": {},
  "arrow-big-right-dash": {},
  "arrow-big-up": {},
  "arrow-big-up-dash": {},
  "circle-arrow-down": {},
  "circle-arrow-left": {},
  "circle-arrow-right": {},
  "circle-arrow-up": {},
  "circle-chevron-down": {},
  "circle-chevron-left": {},
  "circle-chevron-right": {},
  "circle-chevron-up": {},
  milestone: {},
  "mouse-pointer": {},
  "mouse-pointer-2": {},
  "phone-incoming": {},
  "phone-outgoing": {},
  play: {},
  rewind: {},
  signpost: {},
  "square-arrow-down": {},
  "square-arrow-down-left": {},
  "square-arrow-down-right": {},
  "square-arrow-left": {},
  "square-arrow-right": {},
  "square-arrow-up": {},
  "square-arrow-up-left": {},
  "square-arrow-up-right": {},
  "square-chevron-down": {},
  "square-chevron-left": {},
  "square-chevron-right": {},
  "square-chevron-up": {},
  "square-play": {},

  // Buildings
  church: {},
  factory: {},
  "graduation-cap": {},
  hotel: {},
  house: {},
  "house-plug": {},
  store: {},

  // Charts
  "folder-kanban": {},
  "square-chart-gantt": {},
  "square-kanban": {},

  // Communication
  "ethernet-port": {},
  lectern: {},
  "smartphone-nfc": {},

  // Connectivity
  "car-battery": {},
  "card-sim": {},
  "cassette-tape": {},
  "circle-power": {},
  "cloud-off": {},
  // The stand hangs from the screen rather than crossing it.
  monitor: { roles: { 2: "stroke" } },
  "monitor-check": { roles: { 2: "stroke" } },
  "monitor-cloud": { roles: { 1: "stroke" } },
  "monitor-down": { roles: { 3: "stroke" } },
  "monitor-pause": { roles: { 3: "stroke" } },
  "monitor-play": { roles: { 1: "stroke" } },
  "monitor-stop": { roles: { 0: "stroke" } },
  "monitor-up": { roles: { 3: "stroke" } },
  "monitor-x": { roles: { 3: "stroke" } },
  "phone-call": {},
  "phone-missed": {},
  smartphone: {},
  "smartphone-charging": {},
  "square-power": {},
  voicemail: {},
  volume: {},
  "volume-1": {},
  // Sound waves stay lines.
  "volume-2": { roles: { 1: "stroke", 2: "stroke" } },
  "volume-x": {},
  webcam: {},
  zap: {},

  // Cursors
  sparkles: {},

  // Design
  "bring-to-front": {},
  component: {},
  "file-axis-3d": {},
  layers: {},
  "layers-2": {},
  "layers-minus": {},
  "layers-plus": {},
  "layout-arrow-down": {},
  "layout-arrow-right": {},
  "layout-dashboard": {},
  "layout-freeform": {},
  "layout-grid": {},
  "layout-grid-circles": {},
  "layout-list": {},
  "layout-panel-left": {},
  pencil: {},
  "pencil-sparkles": {},
  "send-to-back": {},
  "square-dimensions": {},
  "squares-unite": {},
  stamp: {},
  "swatch-book": {},

  // Coding & development
  blocks: {},
  "circle-dot": {},
  "circle-slash": {},
  container: {},
  "flag-triangle-left": {},
  "flag-triangle-right": {},
  form: {},
  "git-branch": {},
  "git-branch-minus": {},
  "git-compare": {},
  "git-fork": {},
  "hard-drive": {},
  "hard-drive-download": {},
  "hard-drive-upload": {},
  "message-circle-code": {},
  "message-square-code": {},
  "message-square-diff": {},
  network: {},
  puzzle: {},
  router: {},
  server: {},
  "square-dot": {},
  "square-function": {},
  "square-pi": {},
  "square-radical": {},
  "square-slash": {},
  "square-terminal": {},
  workflow: {},

  // Devices
  "alarm-clock": {},
  "alarm-clock-check": {},
  "alarm-clock-minus": {},
  "alarm-clock-plus": {},
  "boom-box": {},
  computer: {},
  // The top disc sits in front of the drum; the middle seam is cut.
  database: { roles: { 0: "front" } },
  disc: {},
  "disc-2": {},
  "disc-album": {},
  eject: {},
  gpu: {},
  hd: {},
  "hdmi-port": {},
  laptop: {},
  "laptop-minimal": {},
  "laptop-minimal-check": {},
  "memory-stick": {},
  // The cup and stand stay lines around a solid capsule.
  mic: { roles: { 0: "stroke", 1: "stroke" } },
  "mic-vocal": {},
  mouse: {},
  "pc-case": {},
  plug: {},
  "plug-2": {},
  printer: {},
  "printer-check": {},
  "printer-x": {},
  "radio-receiver": {},
  "rectangle-goggles": {},
  tablet: {},
  touchpad: {},
  tv: {},
  "tv-minimal": {},
  "tv-minimal-play": {},
  "usb-c-port": {},
  vibrate: {},
  video: {},

  // Emoji
  balloon: {},
  "face-angry": {},
  "face-expressionless": {},
  "face-grinning": {},
  "face-neutral": {},
  "face-slightly-frowning": {},
  "face-slightly-smiling": {},
  "heart-crack": {},

  // File icons
  archive: {},
  "archive-x": {},
  file: {},
  "file-braces": {},
  "file-chart-column": {},
  "file-chart-column-increasing": {},
  "file-chart-line": {},
  "file-check": {},
  "file-code": {},
  "file-diff": {},
  "file-down": {},
  "file-exclamation-point": {},
  "file-minus": {},
  "file-play": {},
  "file-plus": {},
  "file-question-mark": {},
  "file-search": {},
  "file-signal": {},
  "file-sliders": {},
  "file-spreadsheet": {},
  "file-symlink": {},
  "file-terminal": {},
  "file-text": {},
  "file-type": {},
  "file-up": {},
  "file-x": {},
  folder: {},
  "folder-bookmark": {},
  "folder-check": {},
  "folder-closed": {},
  "folder-code": {},
  "folder-dot": {},
  "folder-down": {},
  "folder-git": {},
  "folder-minus": {},
  "folder-plus": {},
  "folder-root": {},
  "folder-search-2": {},
  "folder-up": {},
  "folder-x": {},
  package: {},
  "package-2": {},
  trash: {},

  // Finance
  banknote: {},
  "circle-dollar-sign": {},
  "circle-pound-sterling": {},
  landmark: {},
  "piggy-bank": {},
  receipt: {},
  "receipt-cent": {},
  "receipt-euro": {},
  "receipt-indian-rupee": {},
  "receipt-japanese-yen": {},
  "receipt-pound-sterling": {},
  "receipt-russian-ruble": {},
  "receipt-text": {},
  "receipt-turkish-lira": {},

  // Food & beverage
  apple: {},
  bean: {},
  beef: {},
  beer: {},
  "bottle-wine": {},
  "cake-slice": {},
  can: {},
  carrot: {},
  carton: {},
  "chef-hat": {},
  cherry: {},
  coffee: {},
  "cooking-pot": {},
  "cup-soda": {},
  donut: {},
  drumstick: {},
  egg: {},
  "egg-fried": {},
  "fish-symbol": {},
  "glass-water": {},
  ham: {},
  hamburger: {},
  "ice-cream-bowl": {},
  "ice-cream-cone": {},
  martini: {},
  microwave: {},
  milk: {},
  "paper-bag": {},
  popsicle: {},
  refrigerator: {},
  soup: {},

  // Gaming
  "chess-bishop": {},
  "chess-king": {},
  "chess-pawn": {},
  crown: {},
  "dice-1": {},
  "dice-2": {},
  "dice-3": {},
  "dice-4": {},
  "dice-5": {},
  "dice-6": {},
  dices: {},
  gamepad: {},
  "gamepad-2": {},
  "gamepad-directional": {},
  gem: {},
  ghost: {},
  gift: {},
  joystick: {},
  "playing-card": {},
  "playing-cards": {},
  rocket: {},
  skull: {},
  "toy-brick": {},

  // Home
  armchair: {},
  "bed-double": {},
  "bed-single": {},
  "door-closed": {},
  fan: {},
  "house-heart": {},
  "house-wifi": {},
  lamp: {},
  "lamp-ceiling": {},
  "lamp-floor": {},
  "lamp-wall-down": {},
  "lamp-wall-up": {},
  "plant-pot": {},
  "soap-dispenser-droplet": {},
  "washing-machine": {},

  // Layout
  "align-end-horizontal": {},
  "align-end-vertical": {},
  "align-horizontal-distribute-end": {},
  "align-horizontal-distribute-start": {},
  "align-horizontal-justify-center": {},
  "align-horizontal-justify-end": {},
  "align-horizontal-justify-start": {},
  "align-horizontal-space-between": {},
  "align-start-horizontal": {},
  "align-start-vertical": {},
  "align-vertical-distribute-end": {},
  "align-vertical-distribute-start": {},
  "align-vertical-justify-center": {},
  "align-vertical-justify-end": {},
  "align-vertical-justify-start": {},
  "align-vertical-space-between": {},
  "app-window": {},
  "app-window-mac": {},
  "between-horizontal-end": {},
  "between-horizontal-start": {},
  "between-vertical-end": {},
  "between-vertical-start": {},
  "circle-ellipsis": {},
  "columns-2": {},
  "columns-3": {},
  dock: {},
  fullscreen: {},
  funnel: {},
  "funnel-plus": {},
  "funnel-x": {},
  "gallery-horizontal": {},
  "gallery-horizontal-end": {},
  "gallery-thumbnails": {},
  "gallery-vertical": {},
  "gallery-vertical-end": {},
  "layout-panel-top": {},
  "layout-template": {},
  "panel-bottom": {},
  "panel-bottom-close": {},
  "panel-bottom-dashed": {},
  "panel-bottom-open": {},
  "panel-left": {},
  "panel-left-close": {},
  "panel-left-dashed": {},
  "panel-left-open": {},
  "panel-left-right-dashed": {},
  "panel-right": {},
  "panel-right-close": {},
  "panel-right-dashed": {},
  "panel-right-open": {},
  "panel-top": {},
  "panel-top-bottom-dashed": {},
  "panel-top-close": {},
  "panel-top-dashed": {},
  "panel-top-open": {},
  "panels-left-bottom": {},
  "panels-right-bottom": {},
  "panels-top-left": {},
  "rows-2": {},
  "rows-3": {},
  "square-menu": {},
  "square-square": {},
  "stretch-horizontal": {},
  "stretch-vertical": {},
  "toggle-left": {},
  "toggle-right": {},

  // Mail
  "mail-check": {},
  "mail-minus": {},
  "mail-open": {},
  "mail-warning": {},
  send: {},
  "send-horizontal": {},

  // Mathematics
  calculator: {},
  "circle-divide": {},
  "circle-equal": {},
  "circle-minus": {},
  "circle-plus": {},
  "circle-x": {},
  "octagon-x": {},
  "square-divide": {},
  "square-equal": {},
  "square-minus": {},
  "square-plus": {},
  "square-x": {},
  weight: {},
  "weight-tilde": {},

  // Medical
  // Wheels sit in front of the body; the axle between them stays a line.
  ambulance: { roles: { 4: "stroke", 5: "front", 6: "front" } },
  bandage: {},
  "briefcase-medical": {},
  heart: {},
  mars: {},
  mouth: {},
  pill: {},
  "pill-bottle": {},
  "scan-heart": {},
  siren: {},
  "square-activity": {},
  "tube-lotion": {},
  venus: {},

  // Multimedia
  ad: {},
  captions: {},
  "circle-pause": {},
  "circle-play": {},
  "circle-stop": {},
  clapperboard: {},
  "diamond-minus": {},
  "diamond-plus": {},
  "fast-forward": {},
  guitar: {},
  "keyboard-music": {},
  megaphone: {},
  "midi-port": {},
  music: {},
  "music-2": {},
  "music-3": {},
  "music-4": {},
  newspaper: {},
  "octagon-pause": {},
  pause: {},
  piano: {},
  presentation: {},
  projector: {},
  "skip-back": {},
  "skip-forward": {},
  speaker: {},
  "square-pause": {},
  "square-stop": {},
  "step-back": {},
  "step-forward": {},
  turntable: {},

  // Nature
  cannabis: {},
  "flame-kindling": {},
  flower: {},
  "flower-2": {},
  leaf: {},
  mountain: {},
  "mountain-snow": {},
  shovel: {},
  shrub: {},
  stone: {},
  "tree-deciduous": {},
  "tree-pine": {},

  // Navigation & Places
  binoculars: {},
  compass: {},
  footprints: {},
  "map-pin": {},
  "map-pin-check-inside": {},
  "map-pin-minus-inside": {},
  "map-pin-plus-inside": {},
  "map-pin-x-inside": {},
  navigation: {},
  "navigation-2": {},
  // The needle hangs from the head rather than crossing it.
  pin: { roles: { 0: "stroke" } },

  // Notification
  "bell-off": {},
  "bell-ring": {},
  "circle-alert": {},
  "circle-check": {},
  "octagon-alert": {},
  "square-check": {},
  "square-exclamation-point": {},
  "triangle-alert": {},

  // Photography
  camera: {},
  film: {},
  flashlight: {},
  image: {},
  lightbulb: {},
  "scan-eye": {},
  "scan-square": {},
  "square-bookmark": {},

  // Science
  beaker: {},
  "flask-conical": {},
  "flask-round": {},
  "lens-concave": {},
  "lens-convex": {},
  "mirror-rectangular": {},
  "mirror-round": {},
  radiation: {},
  "test-tube": {},
  "test-tube-diagonal": {},
  "test-tubes": {},

  // Security
  bomb: {},
  "id-card": {},
  "id-card-lanyard": {},
  "key-round": {},
  "key-square": {},
  lock: {},
  "lock-keyhole": {},
  // The open shackle stays a line.
  "lock-keyhole-open": { roles: { 2: "stroke" } },
  "lock-open": { roles: { 1: "stroke" } },
  vault: {},

  // Shapes
  astroid: {},
  box: {},
  circle: {},
  "circle-slash-2": {},
  "circle-small": {},
  club: {},
  cone: {},
  cross: {},
  cuboid: {},
  cylinder: {},
  diamond: {},
  ellipse: {},
  hexagon: {},
  octagon: {},
  pentagon: {},
  pyramid: {},
  "rectangle-horizontal": {},
  "rectangle-vertical": {},
  shapes: {},
  spade: {},
  sparkle: {},
  square: {},
  squircle: {},
  torus: {},
  triangle: {},
  "triangle-right": {},
  ungroup: {},

  // Shopping
  "badge-cent": {},
  "badge-dollar-sign": {},
  "badge-euro": {},
  "badge-indian-rupee": {},
  "badge-japanese-yen": {},
  "badge-pound-sterling": {},
  "badge-russian-ruble": {},
  "badge-turkish-lira": {},
  "circle-euro": {},
  handbag: {},
  shirt: {},
  "shopping-bag": {},
  "shopping-cart": {},

  // Social
  "badge-check": {},
  "badge-minus": {},
  "badge-percent": {},
  "badge-plus": {},
  "badge-x": {},
  "circle-percent": {},
  "diamond-percent": {},
  "hat-glasses": {},
  "message-circle": {},
  "message-circle-check": {},
  "message-circle-heart": {},
  "message-circle-more": {},
  "message-circle-plus": {},
  "message-circle-question-mark": {},
  "message-circle-reply": {},
  "message-circle-warning": {},
  "message-square": {},
  "message-square-check": {},
  "message-square-heart": {},
  "message-square-more": {},
  "message-square-plus": {},
  "message-square-quote": {},
  "message-square-reply": {},
  "message-square-text": {},
  "message-square-warning": {},
  "message-square-x": {},
  "square-percent": {},
  sticker: {},
  vote: {},

  // Sports
  "circle-star": {},
  podium: {},
  "rugby-ball": {},
  "square-star": {},
  trophy: {},
  whistle: {},

  // Text formatting
  "book-open": {},
  "book-open-text": {},
  brush: {},
  // The clip sits in front of the board.
  clipboard: { roles: { 0: "front" } },
  "clipboard-check": { roles: { 0: "front" } },
  "clipboard-list": { roles: { 0: "front" } },
  "clipboard-minus": { roles: { 0: "front" } },
  "clipboard-plus": { roles: { 0: "front" } },
  "clipboard-type": { roles: { 0: "front" } },
  "clipboard-x": { roles: { 0: "front" } },
  // The front sheet sits on an outlined back sheet.
  copy: { roles: { 0: "front", 1: "stroke" } },
  "copy-check": { roles: { 1: "front", 2: "stroke" } },
  "copy-minus": { roles: { 1: "front", 2: "stroke" } },
  "copy-plus": { roles: { 2: "front", 3: "stroke" } },
  "copy-slash": { roles: { 1: "front", 2: "stroke" } },
  copyleft: {},
  copyright: {},
  "creative-commons": {},
  delete: {},
  eraser: {},
  "grid-2x2": {},
  "grid-3x2": {},
  keyboard: {},
  "library-big": {},
  mail: {},
  map: {},
  notebook: {},
  "notebook-text": {},
  "notepad-text": {},
  "paint-roller": {},
  "paintbrush-vertical": {},
  palette: {},
  pen: {},
  "pen-line": {},
  "pen-tool": {},
  "pencil-line": {},
  phone: {},
  quote: {},
  "rectangle-ellipsis": {},
  save: {},
  // The handle stays attached to the lens.
  search: { roles: { 0: "stroke" } },
  "search-alert": { roles: { 1: "stroke" } },
  "search-check": { roles: { 2: "stroke" } },
  "search-code": { roles: { 1: "stroke" } },
  "search-slash": { roles: { 2: "stroke" } },
  "search-x": { roles: { 3: "stroke" } },
  "square-asterisk": {},
  "square-code": {},
  "square-library": {},
  "square-pilcrow": {},
  "square-scissors": {},
  "square-sigma": {},
  "square-text": {},
  "sticky-note": {},
  table: {},
  "table-2": {},
  "table-cells-merge": {},
  "table-cells-split": {},
  "table-properties": {},

  // Time & calendar
  calendar: {},
  "calendar-1": {},
  "calendar-check": {},
  "calendar-days": {},
  "calendar-fold": {},
  "calendar-minus-2": {},
  "calendar-plus-2": {},
  "calendar-range": {},
  "calendar-x": {},
  clock: {},
  "clock-1": {},
  "clock-10": {},
  "clock-11": {},
  "clock-12": {},
  "clock-2": {},
  "clock-3": {},
  "clock-4": {},
  "clock-5": {},
  "clock-6": {},
  "clock-7": {},
  "clock-8": {},
  "clock-9": {},
  hourglass: {},
  timer: {},
  watch: {},

  // Tools
  axe: {},
  bolt: {},
  hammer: {},
  "hard-hat": {},
  "inspection-panel": {},
  pickaxe: {},
  ruler: {},
  "ruler-dimension-line": {},
  toolbox: {},

  // Transportation
  bike: {},
  briefcase: {},
  "briefcase-business": {},
  // Wheels sit in front of the body; the axle between them stays a line.
  car: { roles: { 1: "front", 2: "stroke", 3: "front" } },
  "car-front": {},
  "car-taxi-front": {},
  "circle-parking": {},
  "ev-charger": {},
  fuel: {},
  gauge: {},
  "octagon-minus": {},
  "parking-meter": {},
  plane: {},
  "plane-landing": {},
  "plane-takeoff": {},
  road: {},
  sailboat: {},
  ship: {},
  "square-m": {},
  "square-parking": {},
  "ticket-check": {},
  "ticket-minus": {},
  "ticket-percent": {},
  "ticket-plus": {},
  "ticket-slash": {},
  "ticket-x": {},
  "traffic-cone": {},
  // Wheels sit in front of the body; the axle between them stays a line.
  trailer: { roles: { 5: "front" } },
  "tram-front": {},
  // Wheels sit in front of the body; the axle between them stays a line.
  truck: { roles: { 1: "stroke", 3: "front", 4: "front" } },

  // Travel
  "concierge-bell": {},
  luggage: {},

  // Weather
  bubbles: {},
  cloud: {},
  "cloud-drizzle": {},
  "cloud-fog": {},
  "cloud-hail": {},
  "cloud-lightning": {},
  "cloud-rain": {},
  "cloud-rain-wind": {},
  "cloud-snow": {},
  droplet: {},
  droplets: {},
  flame: {},
  thermometer: {},
  umbrella: {},
};
