import { posix } from "node:path";
import type { IconVariant } from "../../src/types/icon.js";
import type { ReactSvgElement } from "./svg-to-react.js";

/** Matches `formatter.lineWidth` in biome.json; tests prove Biome leaves the output unchanged. */
const lineWidth = 100;

export const runtimeModule = "src/runtime/resolve-icon-props.js";
export const propsModule = "src/types/icon-props.js";

/** One drawing of a concept. */
export type VariantSource = {
  readonly variant: IconVariant;
  /** Repository-relative source SVG, for the header. */
  readonly sourcePath: string;
  readonly svg: ReactSvgElement;
};

export type ComponentSource = {
  /** Repository-relative `.tsx` path the module will be written to. */
  readonly outputPath: string;
  readonly componentName: string;
  /** Every drawing of the concept in configured variant order; the first is the default. */
  readonly variants: readonly VariantSource[];
};

function importPath(outputPath: string, module: string): string {
  const path = posix.relative(posix.dirname(outputPath), module);
  return path.startsWith(".") ? path : `./${path}`;
}

/**
 * Prints one element the way Biome's JSX formatter does for this restricted output: on one line
 * when it fits (or carries a single string attribute, which Biome never breaks), otherwise one
 * attribute per line with the closing bracket on its own line. Element children always break.
 */
function printElement(element: ReactSvgElement, depth: number, spread?: string): string[] {
  const indent = "  ".repeat(depth);
  const attributes = element.attributes.map(([name, value]) => `${name}="${value}"`);
  if (spread) attributes.push(spread);
  const hasChildren = element.children.length > 0;
  const close = hasChildren ? ">" : " />";
  const flat = `${indent}<${element.tag}${attributes.map((attribute) => ` ${attribute}`).join("")}${close}`;
  const singleString = attributes.length === 1 && !spread;

  const lines =
    attributes.length === 0 || singleString || flat.length <= lineWidth
      ? [flat]
      : [
          `${indent}<${element.tag}`,
          ...attributes.map((attribute) => `${indent}  ${attribute}`),
          `${indent}${close.trim()}`,
        ];
  if (!hasChildren) return lines;
  return [
    ...lines,
    ...element.children.flatMap((child) => printElement(child, depth + 1)),
    `${indent}</${element.tag}>`,
  ];
}

/** A `return (...)` of one drawing, with `resolveIconProps` spread last onto its root. */
function printReturn(svg: ReactSvgElement, depth: number): string[] {
  const indent = "  ".repeat(depth);
  return [
    `${indent}return (`,
    ...printElement(svg, depth + 1, "{...resolveIconProps(props)}"),
    `${indent});`,
  ];
}

/**
 * Renders the one component module of a concept.
 *
 * The props type is narrowed to the drawings that exist, so an unavailable `variant` is a type
 * error. Each non-default drawing is one `if` branch; the default drawing is the fall-through, so
 * an outline-only icon has no branch at all. Every branch spreads the same `resolveIconProps`,
 * which consumes `variant`, so size, native props, refs, and accessibility behave identically.
 *
 * The output is deterministic and already Biome-formatted: no timestamps, absolute paths, or
 * environment data; LF newlines; imports in Biome's order. Each source SVG's root attributes come
 * first and `resolveIconProps` is spread last, so caller props override the authored defaults.
 */
export function renderComponentSource({
  outputPath,
  componentName,
  variants,
}: ComponentSource): string {
  const [fallback, ...branches] = variants;
  if (!fallback) throw new Error(`${componentName} has no drawings.`);
  const props = `props: IconProps<${variants.map(({ variant }) => JSON.stringify(variant)).join(" | ")}>`;
  const signature = `export function ${componentName}(${props}) {`;
  const sources = variants.map(({ sourcePath }) => sourcePath).join(", ");
  return [
    `// Generated by @qeetrix/icons from ${sources}.`,
    `// Do not edit this file directly. Edit the source SVG${variants.length > 1 ? "s" : ""} and run \`bun run generate\`.`,
    "",
    `import { resolveIconProps } from ${JSON.stringify(importPath(outputPath, runtimeModule))};`,
    `import type { IconProps } from ${JSON.stringify(importPath(outputPath, propsModule))};`,
    "",
    ...(signature.length <= lineWidth
      ? [signature]
      : [`export function ${componentName}(`, `  ${props},`, ") {"]),
    ...branches.flatMap(({ variant, svg }) => [
      `  if (props.variant === ${JSON.stringify(variant)}) {`,
      ...printReturn(svg, 2),
      "  }",
    ]),
    ...printReturn(fallback.svg, 1),
    "}",
    "",
  ].join("\n");
}
