import type { LogoBackground, LogoManifestEntry } from "../../src/types/logo.js";

/**
 * The logo generator's output, inside the shared `src/generated/` folder. It owns exactly these
 * three paths (the icon generator skips them) and removes stale files only inside the directory.
 * Logo modules have their own directory, like icons, because slugs are arbitrary (a logo named
 * `manifest` exists).
 */
export const logoModuleDirectory = "src/generated/logos";
export const logoBarrelPath = "src/generated/logo-index.ts";
export const logoManifestPath = "src/generated/logo-manifest.ts";
export const logoGeneratedPaths: readonly string[] = [
  logoModuleDirectory,
  logoBarrelPath,
  logoManifestPath,
];

export const logoModulePath = (id: string) => `${logoModuleDirectory}/${id}.ts`;

export type PlannedLogoVariant = {
  readonly name: string;
  readonly background: LogoBackground;
  /** Repository-relative source file. */
  readonly file: string;
  /** The file as a lossless `data:image/svg+xml,` URI. */
  readonly src: string;
  /** The file's intrinsic size (only the ratio matters). */
  readonly width: number;
  readonly height: number;
};

export type PlannedLogo = {
  readonly id: string;
  readonly componentName: string;
  readonly title: string;
  readonly collection: string;
  readonly defaultVariant: string;
  readonly variants: readonly PlannedLogoVariant[];
  readonly hex: string | null;
  readonly categories: readonly string[];
  readonly aliases: readonly string[];
  readonly license: string;
  readonly website: string | null;
  readonly guidelines: string | null;
  readonly source: string | null;
};

export type LogoUpstream = {
  readonly source: string;
  readonly commit: string;
  readonly packageVersion: string;
};

const identifierName = /^[A-Za-z_$][\w$]*$/;

const key = (name: string) => (identifierName.test(name) ? name : JSON.stringify(name));
const text = (value: string) => JSON.stringify(value);

/** Text safe inside a `//` or `/** … *\/` comment. */
const commentText = (value: string) =>
  value.replace(/[\p{Cc}\u2028\u2029]/gu, " ").replace(/\*\//g, "*\\/");

/**
 * A data URI as a single-quoted literal. `svgDataUri` escapes `'`, `\` and every non-ASCII or
 * control byte, so the literal needs no escapes and its text is the URI itself.
 */
function uriLiteral(src: string): string {
  if (/[^\x20-\x7e]|['\\]/.test(src)) {
    throw new Error("A logo data URI must be printable ASCII without ' or \\.");
  }
  return `'${src}'`;
}

/**
 * One variant per line: `name: { width, height, src: '<data URI>' },`. Tests read the URI back
 * from this line, so keep the shape in step with {@link logoVariantLinePattern}.
 */
export function logoVariantLine(variant: PlannedLogoVariant): string {
  return `    ${key(variant.name)}: { width: ${variant.width}, height: ${variant.height}, src: ${uriLiteral(variant.src)} },`;
}

/** Matches a line written by {@link logoVariantLine}: name, width, height, data URI. */
export const logoVariantLinePattern =
  /^ {4}("[a-z0-9-]+"|[a-z0-9]+): \{ width: ([^,]+), height: ([^,]+), src: '([^']*)' \},$/gm;

/** The union of a logo's variant names, as TypeScript source. */
export const variantUnion = (logo: PlannedLogo) =>
  logo.variants.map(({ name }) => text(name)).join(" | ");

/**
 * One logo module: every variant's file embedded byte for byte as a data URI, declared against
 * `LogoData` so TypeScript checks a few string literals, and a function component that renders it.
 */
export function logoModuleSource(logo: PlannedLogo, upstream: LogoUpstream): string {
  const variantList = logo.variants
    .map(({ name }) => (name === logo.defaultVariant ? `\`${name}\` (default)` : `\`${name}\``))
    .join(", ");
  return [
    `// Generated by @qeetrix/icons from ${logo.variants.map(({ file }) => file).join(", ")}.`,
    "// Each file is embedded unmodified: percent-decoding its data URI gives back the file byte for byte.",
    `// Upstream: ${upstream.source} at ${upstream.commit} (${commentText(upstream.packageVersion)}).`,
    `// Logo license: ${commentText(logo.license)}. Trademarks belong to their owners.`,
    "// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.",
    "",
    'import type { ReactElement } from "react";',
    'import { renderLogo } from "../../runtime/render-logo.js";',
    'import type { LogoData, LogoProps } from "../../types/logo.js";',
    "",
    `type Variant = ${variantUnion(logo)};`,
    "",
    "const data: LogoData<Variant> = {",
    `  defaultVariant: ${text(logo.defaultVariant)},`,
    "  variants: {",
    ...logo.variants.map(logoVariantLine),
    "  },",
    "};",
    "",
    "/**",
    ` * ${commentText(logo.title)} logo. Variants: ${variantList}.`,
    ` * License: ${commentText(logo.license)}. Trademarks belong to their owners.`,
    " */",
    `export function ${logo.componentName}(props: LogoProps<Variant>): ReactElement {`,
    "  return renderLogo(data, props);",
    "}",
    "",
  ].join("\n");
}

const generatedNotice = (what: string, upstream: LogoUpstream) =>
  [
    `// Generated by @qeetrix/icons: ${what} from config/brands.json.`,
    `// Upstream: ${upstream.source} at ${upstream.commit} (${commentText(upstream.packageVersion)}).`,
    "// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.",
  ].join("\n");

/** `export { GithubLogo } from "./logos/github.js";` for every logo, in slug order. */
export function logoBarrelSource(logos: readonly PlannedLogo[], upstream: LogoUpstream): string {
  return [
    generatedNotice("brand logo exports", upstream),
    "",
    ...logos.map(({ id, componentName }) => `export { ${componentName} } from "./logos/${id}.js";`),
    "",
  ].join("\n");
}

export function logoManifestEntry(logo: PlannedLogo): LogoManifestEntry {
  return {
    id: logo.id,
    componentName: logo.componentName,
    title: logo.title,
    collection: logo.collection,
    variants: logo.variants.map(({ name, background }) => ({ name, background })),
    defaultVariant: logo.defaultVariant,
    hex: logo.hex,
    categories: logo.categories,
    aliases: logo.aliases,
    license: logo.license,
    website: logo.website,
    guidelines: logo.guidelines,
    source: logo.source,
  };
}

/** Text safe inside a template literal: escapes `\`, `` ` `` and `${`. */
const templateText = (value: string) => value.replace(/\\|`|\$\{/g, (match) => `\\${match}`);

/**
 * `logoManifest` as JSON text in a template literal, one logo per line. TypeScript checks one
 * string instead of typing 7,000+ object literals (whose union alone costs seconds and hundreds of
 * megabytes); the manifest is parsed once, when a tool imports it.
 */
export function logoManifestSource(logos: readonly PlannedLogo[], upstream: LogoUpstream): string {
  const entries = logos.map((logo) => JSON.stringify(logoManifestEntry(logo)));
  return [
    generatedNotice("brand logo catalogue", upstream),
    "",
    'import type { LogoManifest } from "../types/logo.js";',
    "",
    "export const logoManifest: LogoManifest = /* @__PURE__ */ JSON.parse(`{",
    '"schemaVersion": 1,',
    '"logos": [',
    ...entries.map((entry, index) => templateText(entry) + (index < entries.length - 1 ? "," : "")),
    "]",
    "}`);",
    "",
  ].join("\n");
}
