/**
 * Generate docs/icon-catalog.md — the coverage matrix.
 *
 * Reads:  icons/**, icon-metadata.json
 * Writes: docs/icon-catalog.md
 *
 *   bun run catalog
 *   bun run catalog -- --check      verify the committed doc is current (CI)
 *
 * The whole file is generated, prose included. A hand-maintained table of 300+
 * icons is guaranteed to drift from the icons themselves within a release or two,
 * and a coverage matrix that disagrees with the catalogue is worse than none. So
 * the editorial sections live here as templates and the tables are derived — the
 * doc cannot lie about what ships.
 *
 * `priority` comes from icon-metadata.json and exists only for this document. It
 * is deliberately not emitted into the published metadata: it describes our
 * backlog, not the icon.
 */

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { loadCategories } from "./lib/discover.mjs";
import { applyOrCheck, byString, report } from "./lib/io.mjs";
import { collect, loadMetadata } from "./lib/pipeline.mjs";

const PKG = join(dirname(fileURLToPath(import.meta.url)), "..");
const CHECK = process.argv.includes("--check");

const { entries, errors } = collect({ root: PKG });
if (errors.length > 0) {
  console.error("✗ fix validation errors first — run `bun run validate`.");
  process.exit(1);
}
const metadata = loadMetadata(PKG);
const categories = loadCategories(PKG);
const version = JSON.parse(readFileSync(join(PKG, "package.json"), "utf8")).version;

const sorted = [...entries].sort((a, b) => byString(a.name, b.name));
const priorityOf = (name) => metadata[name]?.priority ?? "—";
const byPriority = new Map([
  ["P0", []],
  ["P1", []],
  ["P2", []],
  ["P3", []],
]);
for (const entry of sorted) byPriority.get(priorityOf(entry.name))?.push(entry.name);

const inCategory = new Map(categories.map((c) => [c, []]));
for (const entry of sorted) inCategory.get(entry.category)?.push(entry);

const mirrored = sorted.filter((e) => metadata[e.name]?.mirror);

/** Families: a base icon plus every `<base>-<modifier>` that exists. */
const names = new Set(sorted.map((e) => e.name));
const families = new Map();
for (const entry of sorted) {
  const parts = entry.name.split("-");
  for (let i = parts.length - 1; i >= 1; i--) {
    const base = parts.slice(0, i).join("-");
    if (!names.has(base) || base === entry.name) continue;
    if (!families.has(base)) families.set(base, []);
    families.get(base).push(entry.name);
    break;
  }
}
const bigFamilies = [...families.entries()]
  .filter(([, kids]) => kids.length >= 3)
  .sort((a, b) => b[1].length - a[1].length || byString(a[0], b[0]));

const pct = (n) => `${Math.round((n / sorted.length) * 100)}%`;

const table = (rows) =>
  [
    "| Icon | Component | Pri | RTL | Aliases | Tags |",
    "|:--|:--|:--:|:--:|:--|:--|",
    ...rows.map((e) => {
      const m = metadata[e.name] ?? {};
      return `| \`${e.name}\` | \`${e.component}\` | ${priorityOf(e.name)} | ${m.mirror ? "↔" : ""} | ${(m.aliases ?? []).map((a) => `\`${a}\``).join(" ") || "—"} | ${(m.tags ?? []).join(", ") || "—"} |`;
    }),
  ].join("\n");

const doc = `<!-- GENERATED by scripts/catalog.mjs. Do not edit by hand — run \`bun run catalog\`. -->

# Icon catalogue

The coverage matrix for \`@qeetrix/icons\` v${version}: **${sorted.length} icons** across
**${categories.length} categories**, every one with tags, aliases, RTL behaviour and a coverage
priority.

This file is generated from \`icons/\` and \`icon-metadata.json\`, so it cannot disagree with what
actually ships. \`bun run catalog -- --check\` proves the committed copy is current, and CI runs it.

## How to use this

**Before adding an icon, search this file.** The catalogue is deliberately not exhaustive — it covers
concepts real Qeet interfaces need, and the fastest way to make it worse is to add a second glyph for
something already here under a different word. Search the \`Aliases\` and \`Tags\` columns, not just the
names: \`delete\` is an alias of \`trash\`, \`add\` of \`plus\`, \`gear\` of \`settings\`.

\`bun run explorer\` is the same data with pictures, which is usually the faster way to look.

## Priority

Priority is planning data. It records how essential a concept is to enterprise UI, and it drives what
gets built next — it is **not** part of the published package.

| | Meaning | Count | Share |
|:--|:--|--:|--:|
| **P0** | Essential. You cannot build a standard enterprise interface without it. | ${byPriority.get("P0").length} | ${pct(byPriority.get("P0").length)} |
| **P1** | Highly useful. Common in real product screens. | ${byPriority.get("P1").length} | ${pct(byPriority.get("P1").length)} |
| **P2** | Useful but specialised. | ${byPriority.get("P2").length} | ${pct(byPriority.get("P2").length)} |
| **P3** | Optional. | ${byPriority.get("P3").length} | ${pct(byPriority.get("P3").length)} |

P0 and P1 together are ${pct(byPriority.get("P0").length + byPriority.get("P1").length)} of the
catalogue, which is the intended shape: the set is weighted towards what products actually reach for.

## Categories

| Category | Icons | Share |
|:--|--:|--:|
${categories.map((c) => `| \`${c}\` | ${inCategory.get(c).length} | ${pct(inCategory.get(c).length)} |`).join("\n")}

The category is the source directory and is browse metadata only — it never appears in an icon's
export name, so moving an icon between categories is not a breaking change.

## Families

${bigFamilies.length} bases carry three or more variants. Families are the reason the set feels
designed rather than accumulated: the modifier vocabulary is fixed, so a consumer who has met
\`user-plus\` can guess \`folder-plus\` without looking.

${bigFamilies
  .map(
    ([base, kids]) =>
      `\`\`\`text\n${base}\n${kids.map((k, i) => `${i === kids.length - 1 ? "└──" : "├──"} ${k}`).join("\n")}\n\`\`\``,
  )
  .join("\n\n")}

## RTL mirroring

${mirrored.length} of ${sorted.length} icons (${pct(mirrored.length)}) are marked \`mirror: true\` and
must be flipped horizontally under \`dir="rtl"\`. The flag is metadata — this package does not read
layout direction; a consumer applies it.

Three rules decide the value, and the validator knows about all three:

- **Horizontal direction mirrors.** \`arrow-left\`, \`chevron-right\`, \`log-out\`, \`reply\`.
- **Vertical direction does not.** \`arrow-up\` means the same thing in every locale.
- **Media transport does not.** \`skip-forward\` points right everywhere, because playback direction
  is not reading direction.

${mirrored.map((e) => `\`${e.name}\``).join(" · ")}

## Deliberate non-duplicates

Judgement calls worth recording, so they are not "fixed" later by someone who assumes they were
oversights:

| | Decision |
|:--|:--|
| \`trash\` vs \`x\` vs \`minus\` | One glyph each for *destroy*, *dismiss* and *subtract*. \`delete\`, \`remove\` and \`close\` are aliases, not icons. |
| \`square\` doubles as stop | A media stop button is an outline square. Shipping a second, slightly smaller square would be catalogue bloat, so \`stop\` is an alias. |
| \`refresh\` vs \`sync\` | One arrow means *reload this*; two mean *reconcile two things*. Different operations. |
| \`edit\` vs \`file-edit\` | Editing a field versus renaming a document. Both appear in the same toolbars. |
| \`message-circle\` vs \`message-square\` | Shape variants, both in wide use. Modifier variants hang off \`message-square\`. |
| \`timer\` vs \`clock\` | Elapsed duration versus wall-clock time. \`stopwatch\` is an alias of \`timer\`. |

## Known gaps

Concepts checked and deliberately left out, with the reason. \`bun run doctor\` reports the family
gaps below on every run; they are decisions, not omissions.

| Missing | Why |
|:--|:--|
| \`calendar-minus\`, \`mail-minus\`, \`credit-card-minus\`, \`message-square-minus\` | \`-x\` already covers removal for these bases. \`-minus\` would be a second way to say it. |
| \`shield-plus\` | No product surface needs "add a shield". Add it when one does. |
| \`user-settings\` | A gear small enough to sit beside a head is illegible at 16px. Use \`user-edit\`, or \`settings\` beside the row. |
| \`rotate-left\` / \`rotate-right\` | Would be near-duplicates of \`refresh\`, \`sync\`, \`undo\` and \`redo\`. Needs a distinct object-rotation glyph first. |
| MIME-type icons beyond \`file-text\`/\`file-code\`/\`file-image\`/\`file-archive\` | A glyph per file extension is unbounded and unreadable at 16px. |
| Brand and product logos | Not a general-purpose icon concern. |
| Country and currency glyphs | \`percent\` and \`banknote\` cover the concepts; per-country marks are a different problem. |

## Full catalogue

${categories
  .filter((c) => inCategory.get(c).length > 0)
  .map((c) => `### \`${c}\` (${inCategory.get(c).length})\n\n${table(inCategory.get(c))}`)
  .join("\n\n")}
`;

const files = new Map([["docs/icon-catalog.md", doc]]);
const { written, stale, removed } = applyOrCheck({
  root: PKG,
  files,
  managedDirs: [],
  check: CHECK,
});
process.exit(
  report({
    label: "docs/icon-catalog.md",
    command: "bun run catalog",
    written,
    stale,
    removed,
    check: CHECK,
  }),
);
