// Generated by @qeetrix/icons from icons/brand-icons/brands/adobe/default.svg, icons/brand-icons/brands/adobe/color.svg, icons/brand-icons/brands/adobe/mono-lobe.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import { type ReactElement, useId } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default" | "color" | "mono-lobe";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 91, 80],
      props: { fill: "none" },
      scoped: true,
      children: '[["g",{"clipPath":"url(#\\u00010)"},["path",{"d":"M56.9686 0H90.4318V80L56.9686 0Z","fill":"#EB1000"}],["path",{"d":"M33.4632 0H0V80L33.4632 0Z","fill":"#EB1000"}],["path",{"d":"M45.1821 29.4668L66.5199 80.0002H52.5657L46.1982 63.9461H30.6182L45.1821 29.4668Z","fill":"#EB1000"}]],["defs",null,["clipPath",{"id":"\\u00010"},["rect",{"fill":"white","height":"80","width":"90.4318"}]]]]',
    },
    color: {
      viewBox: [0, 0, 24, 24],
      children: '[["path",{"d":"M14.86 3H23v19zM9.14 3H1v19zM11.992 9.998L17.182 22h-3.394l-1.549-3.813h-3.79z","fill":"#EB1000"}]]',
    },
    "mono-lobe": {
      viewBox: [0, 0, 24, 24],
      props: { fill: "currentColor", fillRule: "evenodd" },
      children: '[["path",{"d":"M14.86 3H23v19zM9.14 3H1v19zM11.992 9.998L17.182 22h-3.394l-1.549-3.813h-3.79z"}]]',
    },
  },
};

/**
 * Adobe logo. Variants: `default` (default), `color`, `mono-lobe`.
 * License: MIT. Trademarks belong to their owners.
 */
export function AdobeLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props, useId());
}
