// Generated by @qeetrix/icons from icons/brand-icons/brands/alibabacloud/color.svg, icons/brand-icons/brands/alibabacloud/default.svg, icons/brand-icons/brands/alibabacloud/mono.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "color" | "default" | "mono";

const data: LogoData<Variant> = {
  defaultVariant: "color",
  variants: {
    color: {
      viewBox: [0, 0, 24, 24],
      children: '[["path",{"d":"M14.752 4.64h5.274C22.242 4.64 24 6.475 24 8.691V15.8a3.947 3.947 0 01-3.974 3.975h-5.274l1.299-1.835 3.822-1.222c.688-.23 1.146-.918 1.146-1.605v-5.81c0-.687-.458-1.375-1.146-1.605L16.05 6.475l-1.3-1.835zM2.98 15.111c0 .688.46 1.376 1.147 1.606l3.822 1.146 1.3 1.835H3.974A3.947 3.947 0 010 15.723V8.69c0-2.216 1.758-4.05 3.975-4.05h5.273L7.95 6.474 4.127 7.697c-.688.23-1.146.918-1.146 1.606v5.808z","fill":"#FF6A00"}],["path",{"d":"M16.051 11.213H8.025v1.835h8.026v-1.835z","fill":"#FF6A00"}]]',
    },
    default: {
      viewBox: [0, 0, 24, 24],
      children: '[["path",{"d":"M14.752 4.64h5.274C22.242 4.64 24 6.475 24 8.691V15.8a3.947 3.947 0 01-3.974 3.975h-5.274l1.299-1.835 3.822-1.222c.688-.23 1.146-.918 1.146-1.605v-5.81c0-.687-.458-1.375-1.146-1.605L16.05 6.475l-1.3-1.835zM2.98 15.111c0 .688.46 1.376 1.147 1.606l3.822 1.146 1.3 1.835H3.974A3.947 3.947 0 010 15.723V8.69c0-2.216 1.758-4.05 3.975-4.05h5.273L7.95 6.474 4.127 7.697c-.688.23-1.146.918-1.146 1.606v5.808z","fill":"#FF6A00"}],["path",{"d":"M16.051 11.213H8.025v1.835h8.026v-1.835z","fill":"#FF6A00"}]]',
    },
    mono: {
      viewBox: [0, 0, 24, 24],
      props: { fill: "currentColor", fillRule: "evenodd" },
      children: '[["path",{"d":"M14.752 4.64h5.274C22.242 4.64 24 6.475 24 8.691V15.8a3.947 3.947 0 01-3.974 3.975h-5.274l1.299-1.835 3.822-1.222c.688-.23 1.146-.918 1.146-1.605v-5.81c0-.687-.458-1.375-1.146-1.605L16.05 6.475l-1.3-1.835zM2.98 15.111c0 .688.46 1.376 1.147 1.606l3.822 1.146 1.3 1.835H3.974A3.947 3.947 0 010 15.723V8.69c0-2.216 1.758-4.05 3.975-4.05h5.273L7.95 6.474 4.127 7.697c-.688.23-1.146.918-1.146 1.606v5.808z"}],["path",{"d":"M16.051 11.213H8.025v1.835h8.026v-1.835z"}]]',
    },
  },
};

/**
 * AlibabaCloud (阿里云) logo. Variants: `color` (default), `default`, `mono`.
 * License: MIT. Trademarks belong to their owners.
 */
export function AlibabacloudLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
