// Generated by @qeetrix/icons from icons/brand-icons/brands/amp/default.svg, icons/brand-icons/brands/amp/color.svg, icons/brand-icons/brands/amp/mono.svg, icons/brand-icons/brands/amp/mono-lobe.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC0-1.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default" | "color" | "mono" | "mono-lobe";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 24, 24],
      props: { fill: "#005AF0" },
      children: '[["path",{"d":"M12 0c6.628 0 12 5.373 12 12s-5.372 12-12 12C5.373 24 0 18.627 0 12S5.373 0 12 0zm-.92 19.278l5.034-8.377a.444.444 0 00.097-.268.455.455 0 00-.455-.455l-2.851.004.924-5.468-.927-.003-5.018 8.367s-.1.183-.1.291c0 .251.204.455.455.455l2.831-.004-.901 5.458z"}]]',
    },
    color: {
      viewBox: [0, 0, 24, 24],
      children: '[["path",{"d":"M15.087 23.18L12.03 24l-2.097-7.823-5.738 5.738-2.251-2.251 5.718-5.719-7.769-2.082.82-3.057 11.294 3.08 3.08 11.295z","fill":"#F34E3F"}],["path",{"d":"M19.505 18.762l-3.057.82-2.564-9.573-9.572-2.564.819-3.057 11.295 3.079 3.08 11.295z","fill":"#F34E3F"}],["path",{"d":"M23.893 14.374l-3.057.82-2.565-9.572L8.7 3.057 9.52 0l11.295 3.08 3.079 11.294z","fill":"#F34E3F"}]]',
    },
    mono: {
      viewBox: [0, 0, 24, 24],
      props: { fill: "currentColor" },
      children: '[["path",{"d":"M12 0c6.628 0 12 5.373 12 12s-5.372 12-12 12C5.373 24 0 18.627 0 12S5.373 0 12 0zm-.92 19.278l5.034-8.377a.444.444 0 00.097-.268.455.455 0 00-.455-.455l-2.851.004.924-5.468-.927-.003-5.018 8.367s-.1.183-.1.291c0 .251.204.455.455.455l2.831-.004-.901 5.458z"}]]',
    },
    "mono-lobe": {
      viewBox: [0, 0, 24, 24],
      props: { fill: "currentColor", fillRule: "evenodd" },
      children: '[["path",{"d":"M15.087 23.18L12.03 24l-2.097-7.823-5.738 5.738-2.251-2.251 5.718-5.719-7.769-2.082.82-3.057 11.294 3.08 3.08 11.295z"}],["path",{"d":"M19.505 18.762l-3.057.82-2.564-9.573-9.572-2.564.819-3.057 11.295 3.079 3.08 11.295z"}],["path",{"d":"M23.893 14.374l-3.057.82-2.565-9.572L8.7 3.057 9.52 0l11.295 3.08 3.079 11.294z"}]]',
    },
  },
};

/**
 * AMP logo. Variants: `default` (default), `color`, `mono`, `mono-lobe`.
 * License: CC0-1.0. Trademarks belong to their owners.
 */
export function AmpLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
