// Generated by @qeetrix/icons from icons/brand-icons/auth-badges/autodesk-badge/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC0-1.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 1024, 1024],
      children: '[["circle",{"cx":"512","cy":"512","r":"512"}],["path",{"d":"M568.73 316.73 256 511.12v156.15h2.7L572.27 472H735a9.58 9.58 0 0 1 9.62 9.62c0 4.59-2.09 6.48-4.59 7.94L586.05 582c-10 6.06-13.58 18-13.58 27l-.22 58.32H768V328.86a12.1 12.1 0 0 0-12.53-12.13Z","style":{"fill":"#fff"}}]]',
    },
  },
};

/**
 * Autodesk logo. Variants: `default` (default).
 * License: CC0-1.0. Trademarks belong to their owners.
 */
export function AutodeskBadgeLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
