// Generated by @qeetrix/icons from icons/brand-icons/aws/aws-res-aws-iot-action/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC-BY-ND-2.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 48, 48],
      children: '[["g",{"fill":"none","fillRule":"evenodd","stroke":"none","strokeWidth":"1"},["path",{"d":"M32.5463,23.2744 C32.9063,23.6594 32.9063,24.2564 32.5463,24.6414 L19.4483,38.6124 L17.9893,37.2454 L30.4453,23.9584 L17.9893,10.6704 L19.4483,9.3024 L32.5463,23.2744 Z M4.0003,23.9584 C4.0003,12.9534 12.9533,4.0004 23.9583,4.0004 C34.9623,4.0004 43.9153,12.9534 43.9153,23.9584 C43.9153,34.9624 34.9623,43.9154 23.9583,43.9154 C12.9533,43.9154 4.0003,34.9624 4.0003,23.9584 Z M2.0003,23.9584 C2.0003,36.0654 11.8513,45.9154 23.9583,45.9154 C36.0663,45.9154 45.9153,36.0654 45.9153,23.9584 C45.9153,11.8504 36.0663,2.0004 23.9583,2.0004 C11.8513,2.0004 2.0003,11.8504 2.0003,23.9584 Z","fill":"#7AA116"}]]]',
    },
  },
};

/**
 * AWS IoT Action logo. Variants: `default` (default).
 * License: CC-BY-ND-2.0. Trademarks belong to their owners.
 */
export function AwsResAwsIotActionLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
