// Generated by @qeetrix/icons from icons/brand-icons/aws/aws-cat-storage/default.svg, icons/brand-icons/aws/aws-cat-storage/16.svg, icons/brand-icons/aws/aws-cat-storage/32.svg, icons/brand-icons/aws/aws-cat-storage/64.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC-BY-ND-2.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default" | "16" | "32" | "64";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 74, 74],
      children: '[["g",{"fill":"none","fillRule":"evenodd","stroke":"none","strokeWidth":"1"},["rect",{"fill":"#7AA116","height":"64","width":"64","x":"5","y":"5"}],["rect",{"height":"72","stroke":"#879196","strokeWidth":"2","width":"72","x":"1","y":"1"}],["g",{"fill":"#FFFFFF","transform":"translate(17.000000, 15.000000)"},["path",{"d":"M14,30 L26,30 L26.001,33 L14,33 L14,30 Z M14,35 L26,35 C27.103,35 28,34.103 28,33 L28,30 C28,28.897 27.103,28 26,28 L14,28 C12.897,28 12,28.897 12,30 L12,33 C12,34.103 12.897,35 14,35 L14,35 Z M12,19 L28,19 L28,17 L12,17 L12,19 Z M12,9 L18,9 L18,7 L12,7 L12,9 Z M12,14 L19,14 L19,12 L12,12 L12,14 Z M38,40.746 C38,41.438 37.437,42 36.746,42 L3.254,42 C2.562,42 2,41.438 2,40.746 L2,25 L38,25 L38,40.746 Z M9,2 L23,2 L23,9 C23,9.552 23.447,10 24,10 L31,10 L31,23 L9,23 L9,2 Z M25,3.414 L29.586,8 L25,8 L25,3.414 Z M39,23 L33,23 L33,9 L32.991,9 C32.99,8.74 32.898,8.484 32.707,8.293 L24.707,0.293 C24.516,0.102 24.26,0.01 24,0.009 L24,0 L8,0 C7.447,0 7,0.448 7,1 L7,23 L1,23 C0.447,23 0,23.448 0,24 L0,40.746 C0,42.541 1.46,44 3.254,44 L36.746,44 C38.54,44 40,42.541 40,40.746 L40,24 C40,23.448 39.553,23 39,23 L39,23 Z"}]]]]',
    },
    "16": {
      viewBox: [0, 0, 32, 32],
      children: '[["g",{"fill":"none","fillRule":"evenodd","stroke":"none","strokeWidth":"1"},["rect",{"fill":"#7AA116","height":"24","width":"24","x":"4","y":"4"}],["rect",{"height":"30","stroke":"#879196","strokeWidth":"2","width":"30","x":"1","y":"1"}],["g",{"fill":"#FFFFFF","transform":"translate(9.000000, 8.000000)"},["path",{"d":"M4,7 L9.794,7 L9.794,6 L4,6 L4,7 Z M5,13 L9,13 L9,12 L5,12 L5,13 Z M10,11.5 L10,13.5 C10,13.776 9.776,14 9.5,14 L4.5,14 C4.224,14 4,13.776 4,13.5 L4,11.5 C4,11.224 4.224,11 4.5,11 L9.5,11 C9.776,11 10,11.224 10,11.5 L10,11.5 Z M13,10 L1,10 L1,14.735 C1,14.881 1.119,15 1.265,15 L12.735,15 C12.881,15 13,14.881 13,14.735 L13,10 Z M3,9 L11,9 L11,4 L8.5,4 C8.224,4 8,3.776 8,3.5 L8,1 L3,1 L3,9 Z M9,1.207 L9,3 L10.793,3 L9,1.207 Z M14,9.5 L14,14.735 C14,15.433 13.433,16 12.735,16 L1.265,16 C0.567,16 0,15.433 0,14.735 L0,9.5 C0,9.224 0.224,9 0.5,9 L2,9 L2,0.5 C2,0.224 2.224,0 2.5,0 L9,0 C9.133,0 9.26,0.053 9.354,0.146 L11.854,2.646 C11.947,2.74 12,2.867 12,3 L12,9 L13.5,9 C13.776,9 14,9.224 14,9.5 L14,9.5 Z M4,5 L7,5 L7,4 L4,4 L4,5 Z"}]]]]',
    },
    "32": {
      viewBox: [0, 0, 48, 48],
      children: '[["g",{"fill":"none","fillRule":"evenodd","stroke":"none","strokeWidth":"1"},["rect",{"fill":"#7AA116","height":"40","width":"40","x":"4","y":"4"}],["rect",{"height":"46","stroke":"#879196","strokeWidth":"2","width":"46","x":"1","y":"1"}],["g",{"fill":"#FFFFFF","transform":"translate(12.000000, 10.000000)"},["path",{"d":"M16,20.5 C16,20.776 15.775,21 15.5,21 L8.5,21 C8.225,21 8,20.776 8,20.5 L8,19.5 C8,19.224 8.225,19 8.5,19 L15.5,19 C15.775,19 16,19.224 16,19.5 L16,20.5 Z M15.5,18 L8.5,18 C7.673,18 7,18.673 7,19.5 L7,20.5 C7,21.327 7.673,22 8.5,22 L15.5,22 C16.327,22 17,21.327 17,20.5 L17,19.5 C17,18.673 16.327,18 15.5,18 L15.5,18 Z M7,10 L17,10 L17,9 L7,9 L7,10 Z M7,4 L10,4 L10,3 L7,3 L7,4 Z M7,7 L10,7 L10,6 L7,6 L7,7 Z M23,26.088 C23,26.591 22.503,27 22,27 L1.912,27 C1.409,27 1,26.591 1,26.088 L1,16 L23,16 L23,26.088 Z M5,1 L13,1 L13,6.5 C13,6.776 13.224,7 13.5,7 L19,7 L19,15 L5,15 L5,1 Z M14,1.707 L18.293,6 L14,6 L14,1.707 Z M23.412,15 L20,15 L20,6.5 L19.98,6.5 C19.98,6.37 19.949,6.242 19.854,6.146 L13.854,0.146 C13.758,0.051 13.63,0.02 13.5,0.02 L13.5,0 L4.5,0 C4.224,0 4,0.224 4,0.5 L4,15 L0.5,15 C0.224,15 0,15.224 0,15.5 L0,26.088 C0,27.143 0.857,28 1.912,28 L22,28 C23.055,28 23.912,27.143 23.912,26.088 L23.912,15.5 C23.912,15.224 23.688,15 23.412,15 L23.412,15 Z"}]]]]',
    },
    "64": {
      viewBox: [0, 0, 90, 90],
      children: '[["g",{"fill":"none","fillRule":"evenodd","stroke":"none","strokeWidth":"1"},["rect",{"fill":"#7AA116","height":"80","width":"80","x":"5","y":"5"}],["rect",{"height":"88","stroke":"#879196","strokeWidth":"2","width":"88","x":"1","y":"1"}],["g",{"fill":"#FFFFFF","transform":"translate(19.000000, 17.000000)"},["path",{"d":"M17,38 L35,38 L35.001,43 L17,43 L17,38 Z M17,45 L35,45 C36.103,45 37,44.103 37,43 L37,38 C37,36.897 36.103,36 35,36 L17,36 C15.897,36 15,36.897 15,38 L15,43 C15,44.103 15.897,45 17,45 L17,45 Z M15,23 L36,23 L36,21 L15,21 L15,23 Z M15,10 L23,10 L23,8 L15,8 L15,10 Z M15,16 L24,16 L24,14 L15,14 L15,16 Z M50,52.034 C50,53.118 49.118,54 48.034,54 L3.966,54 C2.882,54 2,53.118 2,52.034 L2,31 L50,31 L50,52.034 Z M11,2 L30,2 L30,12 C30,12.552 30.447,13 31,13 L41,13 L41,29 L11,29 L11,2 Z M32,3.414 L39.586,11 L32,11 L32,3.414 Z M51,29 L43,29 L43,12 L42.991,12 C42.99,11.74 42.898,11.484 42.707,11.293 L31.707,0.293 C31.516,0.102 31.26,0.01 31,0.01 L31,0 L10,0 C9.447,0 9,0.448 9,1 L9,29 L1,29 C0.447,29 0,29.448 0,30 L0,52.034 C0,54.221 1.779,56 3.966,56 L48.034,56 C50.221,56 52,54.221 52,52.034 L52,30 C52,29.448 51.553,29 51,29 L51,29 Z"}]]]]',
    },
  },
};

/**
 * AWS Storage logo. Variants: `default` (default), `16`, `32`, `64`.
 * License: CC-BY-ND-2.0. Trademarks belong to their owners.
 */
export function AwsCatStorageLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
