// Generated by @qeetrix/icons from icons/brand-icons/aws/aws-res-aws-systems-manager-run-command/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC-BY-ND-2.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 48, 48],
      children: '[["g",{"fill":"none","fillRule":"evenodd","stroke":"none","strokeWidth":"1"},["path",{"d":"M2,27.6299 L10.815,27.6299 L10.815,25.6299 L2,25.6299 L2,27.6299 Z M2,21.4599 L12.578,21.4599 L12.578,19.4599 L2,19.4599 L2,21.4599 Z M2,15.2889 L14.341,15.2889 L14.341,13.2889 L2,13.2889 L2,15.2889 Z M34.715,25.6299 L20.91,25.6299 L22.174,20.5779 L35.979,20.5779 L34.715,25.6299 Z M20.611,18.5779 L18.35,27.6299 L36.277,27.6299 L38.539,18.5779 L20.611,18.5779 Z M38.279,36.7729 C38.24,36.9559 38.076,37.0889 37.889,37.0889 L13.424,37.0889 C13.258,37.0889 13.158,36.9959 13.113,36.9409 C13.069,36.8859 12.999,36.7689 13.033,36.6069 L17.566,15.2399 L42.846,15.2399 L38.279,36.7729 Z M19,9.9999 L43.466,9.9999 C43.631,9.9999 43.731,10.0929 43.776,10.1479 C43.82,10.2029 43.891,10.3189 43.856,10.4829 L43.271,13.2399 L17.99,13.2399 L18.611,10.3169 C18.65,10.1329 18.813,9.9999 19,9.9999 L19,9.9999 Z M45.329,8.8889 C44.872,8.3239 44.193,7.9999 43.466,7.9999 L19,7.9999 C17.873,7.9999 16.887,8.7999 16.653,9.9019 L11.076,36.1929 C10.926,36.9029 11.102,37.6349 11.56,38.1999 C12.017,38.7649 12.696,39.0889 13.424,39.0889 L37.889,39.0889 C39.015,39.0889 40.001,38.2899 40.236,37.1879 L45.813,10.8969 C45.963,10.1859 45.787,9.4529 45.329,8.8889 L45.329,8.8889 Z","fill":"#E7157B"}]]]',
    },
  },
};

/**
 * AWS Systems Manager Run Command logo. Variants: `default` (default).
 * License: CC-BY-ND-2.0. Trademarks belong to their owners.
 */
export function AwsResAwsSystemsManagerRunCommandLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
