// Generated by @qeetrix/icons from icons/brand-icons/aws/aws-res-amazon-eventbridge-default-event-bus/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC-BY-ND-2.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 48, 48],
      children: '[["g",{"fill":"none","fillRule":"evenodd","stroke":"none","strokeWidth":"1"},["path",{"d":"M11.001,39.001 L37.001,39.001 L37.001,37.001 L11.001,37.001 L11.001,39.001 Z M35.88,12.009 L34.153,10.998 L30.544,17.16 L32.271,18.17 L35.88,12.009 Z M42.567,18.594 L36.323,22.147 L37.312,23.885 L43.556,20.332 L42.567,18.594 Z M39.002,28.995 L39,30.995 L46,31.001 L46.002,29.001 L39.002,28.995 Z M2,31.001 L9,31.007 L9.002,29.007 L2.002,29.001 L2,31.001 Z M5.454,18.562 L4.462,20.298 L10.701,23.863 L11.693,22.126 L5.454,18.562 Z M17.48,17.148 L13.882,10.981 L12.153,11.989 L15.751,18.156 L17.48,17.148 Z M25.001,9.002 L23.001,9 L22.994,16 L24.994,16.002 L25.001,9.002 Z M13.095,27.196 L18.114,18.501 C18.293,18.192 18.623,18.001 18.981,18.001 L29.021,18.001 C29.378,18.001 29.708,18.192 29.887,18.501 L34.907,27.196 C35.086,27.505 35.086,27.886 34.907,28.196 L31.071,34.838 L29.339,33.838 L32.887,27.696 L28.443,20.001 L19.558,20.001 L15.115,27.696 L18.662,33.838 L16.93,34.838 L13.095,28.196 C12.916,27.886 12.916,27.505 13.095,27.196 L13.095,27.196 Z","fill":"#E7157B"}]]]',
    },
  },
};

/**
 * Amazon EventBridge Default Event Bus logo. Variants: `default` (default).
 * License: CC-BY-ND-2.0. Trademarks belong to their owners.
 */
export function AwsResAmazonEventbridgeDefaultEventBusLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
