// Generated by @qeetrix/icons from icons/brand-icons/aws/aws-group-server-contents/default.svg.
// Each file is embedded unmodified: percent-decoding its data URI gives back the file byte for byte.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC-BY-ND-2.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: { width: 40, height: 40, src: 'data:image/svg+xml,<?xml version="1.0" encoding="UTF-8"?>%0A<svg width="40px" height="40px" viewBox="0 0 40 40" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">%0A    <title>Icon-Architecture-Group/32/Server-contents_32</title>%0A    <g id="Icon-Architecture-Group/32/Server-contents_32" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">%0A        <rect id="Rectangle" fill="%237D8998" x="0" y="0" width="40" height="40"></rect>%0A        <path d="M12,34 L28,34 L28,6 L12,6 L12,34 Z M13,33 L27,33 L27,7 L13,7 L13,33 Z M15,11 L25,11 L25,10 L15,10 L15,11 Z M15,15 L25,15 L25,14 L15,14 L15,15 Z M15,19 L25,19 L25,18 L15,18 L15,19 Z" id="Fill-1" fill="%23FFFFFF"></path>%0A    </g>%0A</svg>' },
  },
};

/**
 * Server contents logo. Variants: `default` (default).
 * License: CC-BY-ND-2.0. Trademarks belong to their owners.
 */
export function AwsGroupServerContentsLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
