// Generated by @qeetrix/icons from icons/brand-icons/aws/aws-cat-management-tools/default.svg, icons/brand-icons/aws/aws-cat-management-tools/16.svg, icons/brand-icons/aws/aws-cat-management-tools/32.svg, icons/brand-icons/aws/aws-cat-management-tools/64.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC-BY-ND-2.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default" | "16" | "32" | "64";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 74, 74],
      children: '[["g",{"fill":"none","fillRule":"evenodd","stroke":"none","strokeWidth":"1"},["rect",{"fill":"#E7157B","height":"64","width":"64","x":"5","y":"5"}],["rect",{"height":"72","stroke":"#879196","strokeWidth":"2","width":"72","x":"1","y":"1"}],["g",{"fill":"#FFFFFF","transform":"translate(15.000000, 15.000000)"},["path",{"d":"M22,28 L5,28 L5,26 L22,26 L22,24 L24,24 L24,26 L28,26 L28,28 L24,28 L24,30 L22,30 L22,28 Z M10,20 L5,20 L5,18 L10,18 L10,16 L12,16 L12,18 L28,18 L28,20 L12,20 L12,22 L10,22 L10,20 Z M22,5 L32,5 L32,2 L22,2 L22,5 Z M40.842,2 L34,2 L34,1 C34,0.448 33.553,0 33,0 L21,0 C20.447,0 20,0.448 20,1 L20,2 L13.158,2 C11.417,2 10,3.417 10,5.158 L10,9 L12,9 L12,5.158 C12,4.52 12.52,4 13.158,4 L20,4 L20,6 C20,6.552 20.447,7 21,7 L33,7 C33.553,7 34,6.552 34,6 L34,4 L40.842,4 C41.48,4 42,4.52 42,5.158 L42,40.842 C42,41.48 41.48,42 40.842,42 L14.158,42 C13.52,42 13,41.48 13,40.842 L13,38 L11,38 L11,40.842 C11,42.583 12.417,44 14.158,44 L40.842,44 C42.583,44 44,42.583 44,40.842 L44,5.158 C44,3.417 42.583,2 40.842,2 L40.842,2 Z M2,34 L31,34 L31,13 L2,13 L2,34 Z M33,35 L33,12 C33,11.448 32.553,11 32,11 L1,11 C0.447,11 0,11.448 0,12 L0,35 C0,35.552 0.447,36 1,36 L32,36 C32.553,36 33,35.552 33,35 L33,35 Z"}]]]]',
    },
    "16": {
      viewBox: [0, 0, 32, 32],
      children: '[["g",{"fill":"none","fillRule":"evenodd","stroke":"none","strokeWidth":"1"},["rect",{"fill":"#E7157B","height":"24","width":"24","x":"4","y":"4"}],["rect",{"height":"30","stroke":"#879196","strokeWidth":"2","width":"30","x":"1","y":"1"}],["g",{"fill":"#FFFFFF","transform":"translate(8.000000, 8.000000)"},["path",{"d":"M3,9 L2,9 L2,8 L3,8 L3,7 L4,7 L4,8 L9,8 L9,9 L4,9 L4,10 L3,10 L3,9 Z M8,2 L11,2 L11,1 L8,1 L8,2 Z M14.463,1 L12,1 L12,0.5 C12,0.224 11.776,0 11.5,0 L7.5,0 C7.224,0 7,0.224 7,0.5 L7,1 L4.537,1 C3.689,1 3,1.689 3,2.537 L3,4 L4,4 L4,2.537 C4,2.241 4.241,2 4.537,2 L7,2 L7,2.5 C7,2.776 7.224,3 7.5,3 L11.5,3 C11.776,3 12,2.776 12,2.5 L12,2 L14.463,2 C14.754,2 15,2.282 15,2.617 L15,14.383 C15,14.718 14.754,15 14.463,15 L4.537,15 C4.246,15 4,14.718 4,14.383 L4,13 L3,13 L3,14.383 C3,15.275 3.689,16 4.537,16 L14.463,16 C15.311,16 16,15.275 16,14.383 L16,2.617 C16,1.725 15.311,1 14.463,1 L14.463,1 Z M1,11 L10,11 L10,6 L1,6 L1,11 Z M11,11.5 L11,5.5 C11,5.224 10.776,5 10.5,5 L0.5,5 C0.224,5 0,5.224 0,5.5 L0,11.5 C0,11.776 0.224,12 0.5,12 L10.5,12 C10.776,12 11,11.776 11,11.5 L11,11.5 Z"}]]]]',
    },
    "32": {
      viewBox: [0, 0, 48, 48],
      children: '[["g",{"fill":"none","fillRule":"evenodd","stroke":"none","strokeWidth":"1"},["rect",{"fill":"#E7157B","height":"40","width":"40","x":"4","y":"4"}],["rect",{"height":"46","stroke":"#879196","strokeWidth":"2","width":"46","x":"1","y":"1"}],["g",{"fill":"#FFFFFF","transform":"translate(10.000000, 10.000000)"},["path",{"d":"M13,3 L20,3 L20,1 L13,1 L13,3 Z M25.5,1 L21,1 L21,0.5 C21,0.224 20.776,0 20.5,0 L12.5,0 C12.224,0 12,0.224 12,0.5 L12,1 L8.5,1 C7.121,1 6,2.122 6,3.5 L6,6 L7,6 L7,3.5 C7,2.673 7.673,2 8.5,2 L12,2 L12,3.5 C12,3.776 12.224,4 12.5,4 L20.5,4 C20.776,4 21,3.776 21,3.5 L21,2 L25.5,2 C26.327,2 27,2.673 27,3.5 L27,25.5 C27,26.327 26.327,27 25.5,27 L8.5,27 C7.673,27 7,26.327 7,25.5 L7,24 L6,24 L6,25.5 C6,26.878 7.121,28 8.5,28 L25.5,28 C26.879,28 28,26.878 28,25.5 L28,3.5 C28,2.122 26.879,1 25.5,1 L25.5,1 Z M14,18 L4,18 L4,17 L14,17 L14,16 L15,16 L15,17 L17,17 L17,18 L15,18 L15,19 L14,19 L14,18 Z M7,13 L4,13 L4,12 L7,12 L7,11 L8,11 L8,12 L17,12 L17,13 L8,13 L8,14 L7,14 L7,13 Z M1,22 L20,22 L20,8 L1,8 L1,22 Z M21,22.5 L21,7.5 C21,7.224 20.776,7 20.5,7 L0.5,7 C0.224,7 0,7.224 0,7.5 L0,22.5 C0,22.776 0.224,23 0.5,23 L20.5,23 C20.776,23 21,22.776 21,22.5 L21,22.5 Z"}]]]]',
    },
    "64": {
      viewBox: [0, 0, 90, 90],
      children: '[["g",{"fill":"none","fillRule":"evenodd","stroke":"none","strokeWidth":"1"},["rect",{"fill":"#E7157B","height":"80","width":"80","x":"5","y":"5"}],["rect",{"height":"88","stroke":"#879196","strokeWidth":"2","width":"88","x":"1","y":"1"}],["g",{"fill":"#FFFFFF","transform":"translate(17.000000, 17.000000)"},["path",{"d":"M28,36 L7,36 L7,34 L28,34 L28,31 L30,31 L30,34 L35,34 L35,36 L30,36 L30,39 L28,39 L28,36 Z M13,26 L7,26 L7,24 L13,24 L13,21 L15,21 L15,24 L35,24 L35,26 L15,26 L15,29 L13,29 L13,26 Z M27,6 L41,6 L41,2 L27,2 L27,6 Z M52.211,2 L43,2 L43,1 C43,0.448 42.553,0 42,0 L26,0 C25.447,0 25,0.448 25,1 L25,2 L15.789,2 C13.7,2 12,3.7 12,5.79 L12,13 L14,13 L14,5.79 C14,4.803 14.803,4 15.789,4 L25,4 L25,7 C25,7.552 25.447,8 26,8 L42,8 C42.553,8 43,7.552 43,7 L43,4 L52.211,4 C53.197,4 54,4.803 54,5.79 L54,52.21 C54,53.197 53.197,54 52.211,54 L17.789,54 C16.803,54 16,53.197 16,52.21 L16,49 L14,49 L14,52.21 C14,54.3 15.7,56 17.789,56 L52.211,56 C54.3,56 56,54.3 56,52.21 L56,5.79 C56,3.7 54.3,2 52.211,2 L52.211,2 Z M2,45 L40,45 L40,17 L2,17 L2,45 Z M42,46 L42,16 C42,15.448 41.553,15 41,15 L1,15 C0.447,15 0,15.448 0,16 L0,46 C0,46.552 0.447,47 1,47 L41,47 C41.553,47 42,46.552 42,46 L42,46 Z"}]]]]',
    },
  },
};

/**
 * AWS Management Tools logo. Variants: `default` (default), `16`, `32`, `64`.
 * License: CC-BY-ND-2.0. Trademarks belong to their owners.
 */
export function AwsCatManagementToolsLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
