// Generated by @qeetrix/icons from icons/brand-icons/azure/azure-integration-service-environments/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import { type ReactElement, useId } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 18, 18],
      scoped: true,
      children: '[["defs",null,["radialGradient",{"cx":"9.044","cy":"8.913","gradientUnits":"userSpaceOnUse","id":"\\u00010","r":"10.514"},["stop",{"offset":"0.183","stopColor":"#5ea0ef"}],["stop",{"offset":"1","stopColor":"#0078d4"}]],["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00011","x1":"5.344","x2":"5.344","y1":"10.72","y2":"13.464"},["stop",{"offset":"0.001","stopColor":"#76bc2d"}],["stop",{"offset":"1","stopColor":"#5e9624"}]],["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00012","x1":"12.646","x2":"12.646","y1":"10.72","y2":"13.464"},["stop",{"offset":"0.001","stopColor":"#76bc2d"}],["stop",{"offset":"1","stopColor":"#5e9624"}]]],["g",null,["g",null,["circle",{"cx":"9","cy":"9","fill":"url(#\\u00010)","r":"8.863"}],["circle",{"cx":"9","cy":"9","fill":"#fff","r":"7.386"}],["path",{"d":"M9.432,8.665V7.475H8.594v1.19a.168.168,0,0,1-.168.168H5.272a.335.335,0,0,0-.335.335v1.545h.838V9.857a.167.167,0,0,1,.167-.167h6.105a.167.167,0,0,1,.167.167v.874h.838V9.168a.335.335,0,0,0-.335-.335H9.6A.168.168,0,0,1,9.432,8.665Z","fill":"#0078d4"}],["path",{"d":"M10.551,3.862H7.41a.347.347,0,0,0-.347.347V7.35A.347.347,0,0,0,7.41,7.7h3.141A.347.347,0,0,0,10.9,7.35V4.209A.347.347,0,0,0,10.551,3.862Z","fill":"#fff"}],["path",{"d":"M10.551,3.862H7.41a.347.347,0,0,0-.347.347V7.35A.347.347,0,0,0,7.41,7.7h3.141A.347.347,0,0,0,10.9,7.35V4.209A.347.347,0,0,0,10.551,3.862Zm-.3,2.96a.23.23,0,0,1-.23.23H7.938a.23.23,0,0,1-.23-.23V4.737a.23.23,0,0,1,.23-.23h2.085a.23.23,0,0,1,.23.23Z","fill":"#a67af4"}],["g",null,["path",{"d":"M6.715,13.185V11a.279.279,0,0,0-.279-.279H4.251A.279.279,0,0,0,3.972,11v2.186a.279.279,0,0,0,.279.279H6.436A.279.279,0,0,0,6.715,13.185Z","fill":"url(#\\u00011)"}],["path",{"d":"M14.018,13.185V11a.279.279,0,0,0-.279-.279H11.553a.279.279,0,0,0-.279.279v2.186a.279.279,0,0,0,.279.279h2.186A.279.279,0,0,0,14.018,13.185Z","fill":"url(#\\u00012)"}]]]]]',
    },
  },
};

/**
 * Integration Service Environments logo. Variants: `default` (default).
 * License: MIT. Trademarks belong to their owners.
 */
export function AzureIntegrationServiceEnvironmentsLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props, useId());
}
