// Generated by @qeetrix/icons from icons/brand-icons/azure/azure-applens/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import { type ReactElement, useId } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 18, 18],
      scoped: true,
      children: '[["defs",null,["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00010","x2":"18","y1":"9","y2":"9"},["stop",{"offset":"0","stopColor":"#5ea0ef"}],["stop",{"offset":"1","stopColor":"#0078d4"}]],["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00011","x1":"3.092","x2":"14.9","y1":"8.98","y2":"8.98"},["stop",{"offset":"0","stopColor":"#50e6ff"}],["stop",{"offset":"1","stopColor":"#32bedd"}]],["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00012","x1":"3.154","x2":"10.922","y1":"6.215","y2":"6.215"},["stop",{"offset":"0","stopColor":"#5ea0ef"}],["stop",{"offset":"0.432","stopColor":"#3890e4"}],["stop",{"offset":"1","stopColor":"#0078d4"}]]],["g",null,["path",{"d":"M9.276,0A8.957,8.957,0,0,0,3.968,1.54a.6.6,0,0,0-.138.873l.788.993A7.1,7.1,0,1,1,2.084,7.359a.6.6,0,0,0-.412-.707l-.657-.2a.6.6,0,0,0-.763.434A9,9,0,1,0,9.276,0Z","fill":"url(#\\u00010)"}],["circle",{"cx":"13.69","cy":"7.663","fill":"#f78d1e","r":"1.437"}],["circle",{"cx":"7.896","cy":"13.799","fill":"#f78d1e","r":"1.437"}],["path",{"d":"M6.125,6.191,4.993,4.659a5.9,5.9,0,0,1,8.859.983c-.054,0-.106-.016-.162-.016a2.027,2.027,0,0,0-1.617.812,3.984,3.984,0,0,0-5.948-.247ZM5.859,13.8a2.027,2.027,0,0,1,.761-1.575A4,4,0,0,1,5.022,9.6a4.043,4.043,0,0,1,.024-1.338.6.6,0,0,0-.409-.689l-.66-.205a.6.6,0,0,0-.766.448A5.876,5.876,0,0,0,5.879,14C5.873,13.93,5.859,13.866,5.859,13.8ZM13.69,9.7a2.01,2.01,0,0,1-.721-.138,4.016,4.016,0,0,1-3.233,3.376,1.987,1.987,0,0,1-.114,1.93A5.9,5.9,0,0,0,14.9,9.293,2.025,2.025,0,0,1,13.69,9.7Z","fill":"url(#\\u00011)"}],["path",{"d":"M9.253,7.094a1.929,1.929,0,0,0-.834.074L3.973,1.507l-.59.463a.6.6,0,0,0-.1.843L7.359,8A1.909,1.909,0,0,0,7.1,9.26,1.923,1.923,0,1,0,9.253,7.094Z","fill":"url(#\\u00012)"}]]]',
    },
  },
};

/**
 * Applens logo. Variants: `default` (default).
 * License: MIT. Trademarks belong to their owners.
 */
export function AzureApplensLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props, useId());
}
