// Generated by @qeetrix/icons from icons/brand-icons/azure/azure-virtual-router/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import { type ReactElement, useId } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 18, 18],
      scoped: true,
      children: '[["defs",null,["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00010","x1":"9","x2":"9","y1":"17.329","y2":"0.671"},["stop",{"offset":"0","stopColor":"#005ba1"}],["stop",{"offset":"0.15","stopColor":"#0063af"}],["stop",{"offset":"0.439","stopColor":"#006fc3"}],["stop",{"offset":"0.724","stopColor":"#0076d0"}],["stop",{"offset":"1","stopColor":"#0078d4"}]]],["g",null,["g",null,["circle",{"cx":"9","cy":"9","fill":"url(#\\u00010)","r":"8.329"}],["g",null,["path",{"d":"M6.6,4.138l2.3-2.3a.273.273,0,0,1,.387,0l2.3,2.3a.122.122,0,0,1-.086.209H10.086a.122.122,0,0,0-.122.123V7.343a.1.1,0,0,1-.1.1H8.321a.1.1,0,0,1-.1-.1V4.47A.122.122,0,0,0,8.1,4.347H6.687A.123.123,0,0,1,6.6,4.138Z","fill":"#9cebff"}],["path",{"d":"M11.586,13.862l-2.3,2.3a.273.273,0,0,1-.387,0l-2.3-2.3a.123.123,0,0,1,.087-.209H8.1a.122.122,0,0,0,.122-.123V10.657a.1.1,0,0,1,.1-.1H9.866a.1.1,0,0,1,.1.1V13.53a.122.122,0,0,0,.122.123H11.5A.122.122,0,0,1,11.586,13.862Z","fill":"#9cebff"}],["path",{"d":"M12.884,11.513l-2.3-2.3a.273.273,0,0,1,0-.387l2.3-2.3a.122.122,0,0,1,.209.086V8.027a.123.123,0,0,0,.122.123h2.874a.1.1,0,0,1,.1.1V9.792a.1.1,0,0,1-.1.1H13.215a.122.122,0,0,0-.122.122v1.414A.123.123,0,0,1,12.884,11.513Z","fill":"#f2f2f2"}],["path",{"d":"M5.116,6.527l2.3,2.3a.273.273,0,0,1,0,.387l-2.3,2.3a.123.123,0,0,1-.209-.087V10.012a.122.122,0,0,0-.122-.122H1.911a.1.1,0,0,1-.1-.1V8.247a.1.1,0,0,1,.1-.1H4.785a.123.123,0,0,0,.122-.123V6.613A.122.122,0,0,1,5.116,6.527Z","fill":"#f2f2f2"}]]]]]',
    },
  },
};

/**
 * Virtual Router logo. Variants: `default` (default).
 * License: MIT. Trademarks belong to their owners.
 */
export function AzureVirtualRouterLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props, useId());
}
