// Generated by @qeetrix/icons from icons/brand-icons/azure/azure-azure-chaos-studio/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import { type ReactElement, useId } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 18, 18],
      scoped: true,
      children: '[["defs",null,["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00010","x1":"9","x2":"9","y2":"13.5"},["stop",{"offset":"0","stopColor":"#e83231"}],["stop",{"offset":"1","stopColor":"#ce1817"}]],["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00011","x1":"16.61","x2":"4.38","y1":"16.75","y2":"4.3"},["stop",{"offset":"0.04","stopColor":"#a80000"}],["stop",{"offset":"0.32","stopColor":"#a30302"}],["stop",{"offset":"0.63","stopColor":"#960c06"}],["stop",{"offset":"0.71","stopColor":"#910f08"}],["stop",{"offset":"0.74","stopColor":"#8b0e07"}],["stop",{"offset":"0.79","stopColor":"#790a05"}],["stop",{"offset":"0.85","stopColor":"#5b0502"}],["stop",{"offset":"0.89","stopColor":"#400"}]],["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00012","x1":"17.38","x2":"11.61","y1":"16.32","y2":"7.64"},["stop",{"offset":"0.35","stopColor":"#a80000"}],["stop",{"offset":"0.52","stopColor":"#a20402"}],["stop",{"offset":"0.75","stopColor":"#910f08"}],["stop",{"offset":"0.8","stopColor":"#8b0e07"}],["stop",{"offset":"0.87","stopColor":"#790a05"}],["stop",{"offset":"0.94","stopColor":"#5b0502"}],["stop",{"offset":"0.99","stopColor":"#400"}]]],["path",{"d":"M10.18,9V3.32L0,13.5V4A4.9,4.9,0,0,1,1.33,1.31,4.43,4.43,0,0,1,4.27,0H13.5L18,4.5,13.5,9Z","fill":"url(#\\u00010)"}],["path",{"d":"M7.82,9v5.68L18,4.5V14a4.9,4.9,0,0,1-1.33,2.71A4.49,4.49,0,0,1,13.73,18H4.5L0,13.5,4.5,9Z","fill":"url(#\\u00011)"}],["path",{"d":"M7.82,14.68,18,4.5V14a4.9,4.9,0,0,1-1.33,2.71A4.49,4.49,0,0,1,13.73,18Z","fill":"url(#\\u00012)"}]]',
    },
  },
};

/**
 * Azure Chaos Studio logo. Variants: `default` (default).
 * License: MIT. Trademarks belong to their owners.
 */
export function AzureAzureChaosStudioLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props, useId());
}
