// Generated by @qeetrix/icons from icons/brand-icons/azure/azure-customer-lockbox-for-microsoft-azure/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import { type ReactElement, useId } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 18, 18],
      scoped: true,
      children: '[["defs",null,["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00010","x1":"7.86","x2":"7.86","y1":"17.94","y2":"5.72"},["stop",{"offset":"0","stopColor":"#773adc"}],["stop",{"offset":"1","stopColor":"#b77af4"}]],["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00011","x1":"7.87","x2":"7.87","y1":"9.28","y2":"-1.85"},["stop",{"offset":"0","stopColor":"#773adc"}],["stop",{"offset":"1","stopColor":"#b77af4"}]]],["path",{"d":"M13.9,16.85a1.31,1.31,0,0,0,1.32-1.3c0-.05,0-.11,0-.16-.52-4.11-2.86-7.46-7.34-7.46S1,10.76.51,15.4a1.32,1.32,0,0,0,1.17,1.45H13.9Z","fill":"url(#\\u00010)"}],["path",{"d":"M7.87,8.9a4.13,4.13,0,0,1-2.23-.65L7.85,14,10,8.28A4,4,0,0,1,7.87,8.9Z","fill":"#fff"}],["circle",{"cx":"7.87","cy":"4.78","fill":"url(#\\u00011)","r":"4.13"}],["rect",{"fill":"#50e6ff","height":"4.15","rx":"0.56","width":"8.42","x":"9.08","y":"13.2"}],["path",{"d":"M13.29,13.2H9.64a.56.56,0,0,0-.56.56v3a.56.56,0,0,0,.56.56h3.65Z","fill":"#32bedd"}],["path",{"d":"M12.68,14.36l-.09-.1a.15.15,0,0,0-.2,0L10.63,16,10,15.37a.17.17,0,0,0-.21,0l-.09.1a.13.13,0,0,0,0,.2l.84.85.05,0a.16.16,0,0,0,.16,0l1.95-2A.13.13,0,0,0,12.68,14.36Z","fill":"#fff"}],["path",{"d":"M16.51,16.22l-.84-.83.83-.83a.14.14,0,0,0,0-.19l-.11-.11a.12.12,0,0,0-.19,0l-.83.83-.82-.82a.14.14,0,0,0-.21,0l-.1.09a.14.14,0,0,0,0,.19l.83.84-.82.82a.16.16,0,0,0,0,.22l.1.09a.11.11,0,0,0,.18,0l.84-.83.84.83a.14.14,0,0,0,.19,0l.11-.11A.14.14,0,0,0,16.51,16.22Z","fill":"#f2f2f2"}]]',
    },
  },
};

/**
 * Customer Lockbox for Microsoft Azure logo. Variants: `default` (default).
 * License: MIT. Trademarks belong to their owners.
 */
export function AzureCustomerLockboxForMicrosoftAzureLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props, useId());
}
