// Generated by @qeetrix/icons from icons/brand-icons/azure/azure-business-process-tracking/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 18, 18],
      children: '[["path",{"d":"M14.609,11.297l-5.609,1.781-5.609-1.781c-.34-.108-.691.133-.691.474v3.869c0,.215.145.406.359.474l5.941,1.886,5.941-1.886c.214-.068.359-.259.359-.474v-3.869c0-.341-.351-.582-.691-.474Z","fill":"#76d263"}],["path",{"d":"M15.3,9.641v-3.869c0-.341-.351-.582-.691-.474l-5.609,1.781-5.609-1.781c-.34-.108-.691.133-.691.474v3.869c0,.215.145.406.359.474l5.941,1.886,5.941-1.886c.214-.068.359-.259.359-.474Z","fill":"#399a91"}],["path",{"d":"M2.7,3.64V.5c0-.276.235-.5.525-.5h11.55c.29,0,.525.224.525.5v3.14c0,.215-.145.406-.359.474l-5.941,1.886-5.941-1.886c-.214-.068-.359-.259-.359-.474Z","fill":"#225b62"}]]',
    },
  },
};

/**
 * Business Process Tracking logo. Variants: `default` (default).
 * License: MIT. Trademarks belong to their owners.
 */
export function AzureBusinessProcessTrackingLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
