// Generated by @qeetrix/icons from icons/brand-icons/azure/azure-media-file/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import { type ReactElement, useId } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 18, 18],
      scoped: true,
      children: '[["defs",null,["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00010","x1":"9","x2":"9","y1":"17.5","y2":"0.5"},["stop",{"offset":"0","stopColor":"#0078d4"}],["stop",{"offset":"0.817","stopColor":"#5ea0ef"}]]],["g",null,["g",null,["g",null,["path",{"d":"M9.966.627H2.731A.571.571,0,0,0,2.16,1.2V16.8a.571.571,0,0,0,.571.572H15.269a.571.571,0,0,0,.571-.572V6.475a.571.571,0,0,0-.571-.572H11.108a.571.571,0,0,1-.571-.571V1.2A.572.572,0,0,0,9.966.627Z","fill":"#fff"}],["path",{"d":"M9.7,1.357V5.276a1.438,1.438,0,0,0,1.436,1.438h3.947v9.929H2.915V1.357H9.7M9.978.5H2.638a.581.581,0,0,0-.58.581V16.919a.581.581,0,0,0,.58.581H15.362a.581.581,0,0,0,.58-.581V6.437a.58.58,0,0,0-.58-.58H11.138a.58.58,0,0,1-.58-.581V1.081A.581.581,0,0,0,9.978.5Z","fill":"url(#\\u00010)"}],["path",{"d":"M15.72,5.972,10.358.627V4.982a.984.984,0,0,0,.978.99Z","fill":"#0078d4"}]],["path",{"d":"M4.639,5.231V8.775a.285.285,0,0,0,.426.247l3.1-1.772a.284.284,0,0,0,0-.494l-3.1-1.772A.285.285,0,0,0,4.639,5.231Z","fill":"#32bedd"}],["rect",{"fill":"#5ea0ef","height":"0.989","rx":"0.444","width":"7.37","x":"4.588","y":"10.418"}],["rect",{"fill":"#5ea0ef","height":"0.989","rx":"0.444","width":"7.37","x":"4.588","y":"12.189"}],["rect",{"fill":"#5ea0ef","height":"0.989","rx":"0.444","width":"4.645","x":"4.588","y":"13.961"}]]]]',
    },
  },
};

/**
 * Media File logo. Variants: `default` (default).
 * License: MIT. Trademarks belong to their owners.
 */
export function AzureMediaFileLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props, useId());
}
