// Generated by @qeetrix/icons from icons/brand-icons/azure/azure-app-space-component/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import { type ReactElement, useId } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 18, 18],
      scoped: true,
      children: '[["defs",null,["linearGradient",{"gradientTransform":"translate(0 791.516) scale(1 -1)","gradientUnits":"userSpaceOnUse","id":"\\u00010","x1":"9.355","x2":"8.403","y1":"790.98","y2":"768.301"},["stop",{"offset":".003","stopColor":"#6eccbc"}],["stop",{"offset":".82","stopColor":"#318581"}]]],["path",{"d":"M10.036,0H2.264c-.163,0-.319.065-.434.18-.115.115-.18.272-.18.435v16.77c0,.163.065.319.18.434s.271.18.434.181h13.472c.163,0,.319-.065.434-.181.115-.115.18-.272.18-.434V6.286c0-.163-.065-.319-.18-.434-.115-.115-.271-.18-.434-.18h-4.472c-.163,0-.319-.065-.434-.18-.115-.115-.18-.271-.18-.434V.615c0-.163-.065-.319-.18-.434-.115-.115-.271-.18-.434-.181Z","fill":"url(#\\u00010)"}],["path",{"d":"M16.115,5.794L10.438.134v4.612c-.002.276.107.542.301.738.194.197.458.308.734.31h4.642Z","fill":"#318581"}],["g",{"opacity":".8"},["path",{"d":"M7.06,13.437l.003-.003c.061-.063.058-.163-.005-.224l-2.804-2.797-.349.35c-.124.124-.124.324,0,.448l2.583,2.575c.062.062.162.062.224,0l.348-.349Z","fill":"#fff"}],["path",{"d":"M14.1,10.766l-.349-.35-2.807,2.799c-.062.062-.062.162,0,.224l.349.35c.062.062.162.062.224,0l2.583-2.575c.123-.124.124-.324,0-.448Z","fill":"#fff"}]],["path",{"d":"M7.425,14.514l2.278-7.116c.018-.059.082-.092.141-.073l.56.179c.059.018.092.082.073.141l-2.278,7.116c-.018.059-.082.092-.141.073l-.56-.179c-.059-.018-.092-.082-.073-.141Z","fill":"#fff"}],["path",{"d":"M6.658,8.225l.35.349c.062.062.062.162,0,.224l-2.757,2.765-.35-.349c-.124-.124-.124-.324,0-.448l2.535-2.541c.062-.062.16-.062.222,0Z","fill":"#fff"}],["path",{"d":"M14.096,11.213l-.35.349-2.754-2.761c-.062-.062-.062-.162,0-.224l.35-.349c.062-.062.162-.062.224,0l2.531,2.539c.124.124.123.324,0,.448h-.001v-.002Z","fill":"#fff"}]]',
    },
  },
};

/**
 * App Space Component logo. Variants: `default` (default).
 * License: MIT. Trademarks belong to their owners.
 */
export function AzureAppSpaceComponentLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props, useId());
}
