// Generated by @qeetrix/icons from icons/brand-icons/azure/azure-storage-explorer/default.svg.
// Each file is embedded unmodified: percent-decoding its data URI gives back the file byte for byte.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: { width: 18, height: 18, src: 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18"><defs><linearGradient id="bee6f948-729b-4fc1-971c-9b33c93b461f" x1="9.286" y1="7.103" x2="8.876" y2="19.415" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="%23e6e6e6" /><stop offset="1" stop-color="%23b3b3b3" /></linearGradient></defs><title>Icon-613-Storage-Explorer-blue</title><g id="eba65084-93f2-4c1d-af99-2c8b228075b7"><g><path d="M16.218,6.589H11.293a.259.259,0,0,0-.259.259V9.829a.259.259,0,0,1-.259.259H6.406a.257.257,0,0,0-.257.257v3.043a.26.26,0,0,1-.26.259H1.521a.258.258,0,0,0-.258.257v3.581A.516.516,0,0,0,1.778,18h9.816a.233.233,0,0,0,.053-.006h4.571a.518.518,0,0,0,.519-.518V7.107A.518.518,0,0,0,16.218,6.589Z" fill="url(%23bee6f948-729b-4fc1-971c-9b33c93b461f)" /><rect x="11.851" y="14.495" width="4.068" height="2.711" rx="0.259" fill="%23005ba1" /><rect x="11.851" y="10.936" width="4.068" height="2.711" rx="0.259" fill="%235ea0ef" /><rect x="11.851" y="7.377" width="4.068" height="2.711" rx="0.259" fill="%23fff" /><rect x="6.966" y="14.5" width="4.068" height="2.711" rx="0.259" fill="%23005ba1" /><rect x="6.966" y="10.942" width="4.068" height="2.711" rx="0.259" fill="%23fff" /><rect x="2.081" y="14.5" width="4.068" height="2.711" rx="0.259" fill="%23005ba1" /><rect x="6.097" y="3.396" width="4.834" height="3.221" rx="0.308" fill="%235ea0ef" /><rect x="1.263" y="6.76" width="4.834" height="3.221" rx="0.308" fill="%230078d4" /><rect x="1.263" width="4.834" height="3.221" rx="0.308" fill="%2383b9f9" /></g></g></svg>' },
  },
};

/**
 * Storage Explorer logo. Variants: `default` (default).
 * License: MIT. Trademarks belong to their owners.
 */
export function AzureStorageExplorerLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
