// Generated by @qeetrix/icons from icons/brand-icons/azure/azure-private-link-services/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import { type ReactElement, useId } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 18, 18],
      scoped: true,
      children: '[["defs",null,["linearGradient",{"gradientTransform":"translate(0 32)","gradientUnits":"userSpaceOnUse","id":"\\u00010","x1":"7.688","x2":"7.688","y1":"-26.771","y2":"-21.482"},["stop",{"offset":"0.23","stopColor":"#5ea0ef"}],["stop",{"offset":"0.32","stopColor":"#5b9fee"}],["stop",{"offset":"0.48","stopColor":"#509aeb"}],["stop",{"offset":"0.57","stopColor":"#3f92e6"}],["stop",{"offset":"0.75","stopColor":"#2688df"}],["stop",{"offset":"0.93","stopColor":"#127fd9"}]],["linearGradient",{"gradientTransform":"translate(0 32)","gradientUnits":"userSpaceOnUse","id":"\\u00011","x1":"10.312","x2":"10.312","y1":"-24.568","y2":"-19.279"},["stop",{"offset":"0.2","stopColor":"#50e6ff"}],["stop",{"offset":"0.65","stopColor":"#32bedd"}],["stop",{"offset":"1","stopColor":"#198ab3"}]],["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00012","x1":"9","x2":"9","y1":"5.38"},["stop",{"offset":"0.199","stopColor":"#005ba1"}],["stop",{"offset":"1","stopColor":"#0078d4"}]]],["g",null,["g",null,["g",null,["path",{"d":"M8.736,5.229H6.62a2.644,2.644,0,0,0-.41,5.253A2.824,2.824,0,0,1,6.237,9.5,1.67,1.67,0,0,1,6.62,6.2H8.736a1.675,1.675,0,0,1,0,3.35H8.154a1.275,1.275,0,0,0-.124.529,1.234,1.234,0,0,0,.084.441h.622a2.645,2.645,0,0,0,0-5.289Z","fill":"url(#\\u00010)"}],["path",{"d":"M11.79,7.468a3.042,3.042,0,0,1,.031.405,2.722,2.722,0,0,1-.058.577,1.671,1.671,0,0,1-.383,3.3H9.264a1.675,1.675,0,0,1,0-3.35h.582a1.195,1.195,0,0,0,.04-.97H9.264a2.645,2.645,0,0,0,0,5.289H11.38a2.644,2.644,0,0,0,.41-5.253Z","fill":"url(#\\u00011)"}]],["path",{"d":"M9-.025,1.15,4.465v8.97L9,17.975l7.85-4.49v-9Zm6.4,12.57L9,16.245,2.6,12.584V5.355L9,1.655l6.4,3.71Z","fill":"#0078d4"}]],["polygon",{"fill":"url(#\\u00012)","points":"9 0 9 0 1.15 4.49 2.6 5.38 9 1.68 9 1.68 15.4 5.38 16.85 4.49 9 0"}]]]',
    },
  },
};

/**
 * Private Link Services logo. Variants: `default` (default).
 * License: MIT. Trademarks belong to their owners.
 */
export function AzurePrivateLinkServicesLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props, useId());
}
