// Generated by @qeetrix/icons from icons/brand-icons/azure/azure-multi-tenancy/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import { type ReactElement, useId } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 18, 18],
      scoped: true,
      children: '[["defs",null,["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00010","x1":"6.234","x2":"6.234","y1":"5.679","y2":"16.03"},["stop",{"offset":"0.227","stopColor":"#a67af4"}],["stop",{"offset":"1","stopColor":"#773adc"}]],["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00011","x1":"5.972","x2":"6.727","y1":"0.13","y2":"9.529"},["stop",{"offset":"0.225","stopColor":"#a67af4"}],["stop",{"offset":"1","stopColor":"#773adc"}]],["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00012","x1":"9.128","x2":"18","y1":"13.552","y2":"13.552"},["stop",{"offset":"0","stopColor":"#1988d9"}],["stop",{"offset":"0.9","stopColor":"#54aef0"}]]],["g",null,["g",null,["g",null,["path",{"d":"M16.312,11.946a.74.74,0,0,0,.742-.738.532.532,0,0,0,0-.089C16.758,8.792,15.431,6.9,12.9,6.9c-2.577,0-3.907,1.605-4.166,4.228a.745.745,0,0,0,.664.817.628.628,0,0,0,.075,0Z","fill":"#773adc"}],["circle",{"cx":"12.898","cy":"5.114","fill":"#773adc","r":"2.335"}],["path",{"d":"M11.355,14.162a1.109,1.109,0,0,0,1.112-1.105,1,1,0,0,0-.008-.134C12.024,9.439,10.036,6.6,6.243,6.6,2.385,6.6.394,9,.006,12.933A1.115,1.115,0,0,0,1,14.156a1.051,1.051,0,0,0,.112.006Z","fill":"url(#\\u00010)"}],["path",{"d":"M6.3,7.428A3.481,3.481,0,0,1,4.41,6.871l1.874,4.895L8.144,6.9A3.468,3.468,0,0,1,6.3,7.428Z","fill":"#fff","opacity":"0.8"}],["circle",{"cx":"6.277","cy":"3.932","fill":"url(#\\u00011)","r":"3.496"}]],["polygon",{"fill":"url(#\\u00012)","points":"13.564 9.54 9.128 15.751 13.564 17.564 18 15.751 13.564 9.54"}],["polygon",{"fill":"#50e6ff","points":"13.564 9.54 9.128 15.751 13.564 17.564 13.564 9.54"}]]]]',
    },
  },
};

/**
 * Multi Tenancy logo. Variants: `default` (default).
 * License: MIT. Trademarks belong to their owners.
 */
export function AzureMultiTenancyLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props, useId());
}
