// Generated by @qeetrix/icons from icons/brand-icons/azure/azure-cost-export/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import { type ReactElement, useId } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 18, 18],
      scoped: true,
      children: '[["defs",null,["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00010","x1":"5.782","x2":"5.782","y1":"1.789","y2":"15.749"},["stop",{"offset":"0","stopColor":"#5ea0ef"}],["stop",{"offset":"1","stopColor":"#0078d4"}]]],["g",null,["path",{"d":"M4.667,5.35H.319A.319.319,0,0,1,0,5.031V2.108a.319.319,0,0,1,.319-.319H4.667a.319.319,0,0,1,.319.319V5.031A.319.319,0,0,1,4.667,5.35Zm0,5.2H.319A.319.319,0,0,1,0,10.23V7.307a.319.319,0,0,1,.319-.319H4.667a.319.319,0,0,1,.319.319V10.23A.319.319,0,0,1,4.667,10.549Zm6.578-5.2H6.9a.319.319,0,0,1-.32-.319V2.108a.319.319,0,0,1,.32-.319h4.347a.319.319,0,0,1,.319.319V5.031A.319.319,0,0,1,11.245,5.35Zm0,10.4H6.9a.32.32,0,0,1-.32-.32V12.506a.319.319,0,0,1,.32-.319h4.347a.319.319,0,0,1,.319.319v2.923A.319.319,0,0,1,11.245,15.749Zm-6.578,0H.319A.319.319,0,0,1,0,15.429V12.506a.319.319,0,0,1,.319-.319H4.667a.319.319,0,0,1,.319.319v2.923A.319.319,0,0,1,4.667,15.749Z","fill":"url(#\\u00010)"}],["path",{"d":"M13.217,3.758l4.622,4.621a.551.551,0,0,1,0,.779L13.217,13.78a.246.246,0,0,1-.42-.174V10.764a.246.246,0,0,0-.246-.246H6.775a.2.2,0,0,1-.2-.2v-3.1a.2.2,0,0,1,.2-.2h5.776a.246.246,0,0,0,.246-.246V3.932A.246.246,0,0,1,13.217,3.758Z","fill":"#86d633"}]]]',
    },
  },
};

/**
 * Cost Export logo. Variants: `default` (default).
 * License: MIT. Trademarks belong to their owners.
 */
export function AzureCostExportLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props, useId());
}
