// Generated by @qeetrix/icons from icons/brand-icons/azure/azure-feature-previews/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import { type ReactElement, useId } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 18, 18],
      scoped: true,
      children: '[["defs",null,["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00010","x1":"9","x2":"9","y1":"19.682","y2":"1.099"},["stop",{"offset":"0","stopColor":"#76bc2d"}],["stop",{"offset":"0.192","stopColor":"#7fcb30"}],["stop",{"offset":"0.42","stopColor":"#84d332"}],["stop",{"offset":"0.775","stopColor":"#86d633"}]]],["g",null,["g",null,["path",{"d":"M14.315.5H3.685a.574.574,0,0,0-.573.573V17.159a.287.287,0,0,0,.464.225l5.247-4.112a.282.282,0,0,1,.118-.051l-.018-.014,5.965-4.65V1.073A.574.574,0,0,0,14.315.5Z","fill":"url(#\\u00010)"}],["path",{"d":"M8.923,13.207l5.965-4.65v8.656a.287.287,0,0,1-.462.227Z","fill":"#76bc2d"}]]]]',
    },
  },
};

/**
 * Feature Previews logo. Variants: `default` (default).
 * License: MIT. Trademarks belong to their owners.
 */
export function AzureFeaturePreviewsLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props, useId());
}
