// Generated by @qeetrix/icons from icons/brand-icons/azure/azure-azure-managed-grafana/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import { type ReactElement, useId } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 18, 18],
      scoped: true,
      children: '[["defs",null,["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00010","x1":"9","x2":"9","y1":"2","y2":"16"},["stop",{"offset":"0.18","stopColor":"#5ea0ef"}],["stop",{"offset":"1","stopColor":"#0078d4"}]]],["g",null,["g",null,["rect",{"fill":"url(#\\u00010)","height":"14","rx":"0.76","width":"18","y":"2"}],["path",{"d":"M8.3178,4.81s-.0039.0158-.0088.0425a3.9705,3.9705,0,0,0-1.213.573A2.8294,2.8294,0,0,0,4.9338,5.5a3.0919,3.0919,0,0,0,.5588,2.0973A5.2491,5.2491,0,0,0,5.2178,8.789a2.7967,2.7967,0,0,0-1.3537,1.5729,2.9791,2.9791,0,0,0,1.888,1.0647l.0027-.0021a4.4086,4.4086,0,0,0,.6684.9033,2.3478,2.3478,0,0,0,.0447,1.665,2.7075,2.7075,0,0,0,1.7419-.531,4.3848,4.3848,0,0,0,1.5871.2225,1.9523,1.9523,0,0,0,1.2621.7458,2.0114,2.0114,0,0,0,.6046-1.33h0l-.0006-.0267h0l-.0016-.0278a3.5138,3.5138,0,0,0,.9835-1.0413,1.6,1.6,0,0,0,1.1035-.4007,1.6822,1.6822,0,0,0-.5719-1.0653h0l-.0158-.0115h0l-.0142-.0092a2.8079,2.8079,0,0,0-2.8519-3.1529c-2.8346-.103-2.5312,4.8885.2838,3.5118.1731-.4159-.4839.0239-.6621-.0694A1.1684,1.1684,0,0,1,8.8341,9.58a1.47,1.47,0,0,1,2.2554-1.1c1.8829,1.0529.5374,3.9916-1.4289,3.8272.0136,0-.0022,0-.0017-.0006a3.0673,3.0673,0,0,1-2.99-3.0487A3.3064,3.3064,0,0,1,9.8666,5.8439C11.7835,5.6625,13.24,7.22,13.7853,8.8311a3.4406,3.4406,0,0,0-1.1344-2.95,1.581,1.581,0,0,0-.1859-1.134,1.68,1.68,0,0,0-1.0942.2813,4.253,4.253,0,0,0-1.0947-.3036A2.0325,2.0325,0,0,0,9.29,3.57a2.1574,2.1574,0,0,0-.972,1.24","fill":"#f2f2f2"}]]]]',
    },
  },
};

/**
 * Azure Managed Grafana logo. Variants: `default` (default).
 * License: MIT. Trademarks belong to their owners.
 */
export function AzureAzureManagedGrafanaLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props, useId());
}
