// Generated by @qeetrix/icons from icons/brand-icons/azure/azure-table/default.svg.
// Each file is embedded unmodified: percent-decoding its data URI gives back the file byte for byte.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: { width: 18, height: 18, src: 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18"><defs><linearGradient id="fc742b2b-5750-4864-b8dc-cdccaac6f13c" x1="9" y1="15.834" x2="9" y2="5.788" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="%230078d4" /><stop offset="0.502" stop-color="%234093e6" /><stop offset="0.775" stop-color="%235ea0ef" /></linearGradient></defs><title>MsPortalFx.base.images-4</title><g id="fb33f902-6783-4db3-88ea-a4524e356c77"><g><path d="M.5,5.788h17a0,0,0,0,1,0,0v9.478a.568.568,0,0,1-.568.568H1.068A.568.568,0,0,1,.5,15.266V5.788A0,0,0,0,1,.5,5.788Z" fill="url(%23fc742b2b-5750-4864-b8dc-cdccaac6f13c)" /><path d="M1.071,2.166H16.929a.568.568,0,0,1,.568.568V5.788a0,0,0,0,1,0,0H.5a0,0,0,0,1,0,0V2.734A.568.568,0,0,1,1.071,2.166Z" fill="%230078d4" /><rect x="2.304" y="7.121" width="3.65" height="1.85" rx="0.283" fill="%23fff" opacity="0.9" /><rect x="7.2" y="7.095" width="3.65" height="1.85" rx="0.283" fill="%23fff" opacity="0.9" /><rect x="12.096" y="7.095" width="3.65" height="1.85" rx="0.283" fill="%23fff" opacity="0.9" /><rect x="2.358" y="9.767" width="3.65" height="1.85" rx="0.283" fill="%23fff" opacity="0.9" /><rect x="7.254" y="9.741" width="3.65" height="1.85" rx="0.283" fill="%23ffd400" /><rect x="12.15" y="9.741" width="3.65" height="1.85" rx="0.283" fill="%23ffd400" /><rect x="2.358" y="12.439" width="3.65" height="1.85" rx="0.283" fill="%23ffd400" /><rect x="7.254" y="12.413" width="3.65" height="1.85" rx="0.283" fill="%23ffd400" /><rect x="12.15" y="12.413" width="3.65" height="1.85" rx="0.283" fill="%23ffd400" /></g></g></svg>' },
  },
};

/**
 * Table logo. Variants: `default` (default).
 * License: MIT. Trademarks belong to their owners.
 */
export function AzureTableLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
