// Generated by @qeetrix/icons from icons/brand-icons/azure/azure-time-series-insights-environments/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import { type ReactElement, useId } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 18, 18],
      scoped: true,
      children: '[["defs",null,["linearGradient",{"gradientTransform":"matrix(1, 0, 0, -1, 0, -3108)","gradientUnits":"userSpaceOnUse","id":"\\u00010","x1":"8.999","x2":"8.999","y1":"-3108.081","y2":"-3125.919"},["stop",{"offset":"0","stopColor":"#b3b2b3"}],["stop",{"offset":"0.216","stopColor":"#afaeaf"}],["stop",{"offset":"0.44","stopColor":"#a2a2a2"}],["stop",{"offset":"0.577","stopColor":"#979797"}]]],["g",null,["path",{"d":"M.407,6.621a8.914,8.914,0,0,1,17.183,0h-1.7a7.293,7.293,0,0,0-13.789,0Zm15.451,4.863a7.295,7.295,0,0,1-13.718,0H.437a8.914,8.914,0,0,0,17.123,0Z","fill":"url(#\\u00010)"}],["path",{"d":"M9.64,13.141,7.5,8.33,6.6,9.885H1.093a.811.811,0,0,1,0-1.622H5.666l2.025-3.5,2.332,5.246L11.4,8.246l5.51.012a.811.811,0,0,1,0,1.622h0l-4.716-.011Z","fill":"#50e6ff"}]]]',
    },
  },
};

/**
 * Time Series Insights Environments logo. Variants: `default` (default).
 * License: MIT. Trademarks belong to their owners.
 */
export function AzureTimeSeriesInsightsEnvironmentsLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props, useId());
}
