// Generated by @qeetrix/icons from icons/brand-icons/azure/azure-app-registrations/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import { type ReactElement, useId } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 18, 18],
      scoped: true,
      children: '[["defs",null,["linearGradient",{"gradientTransform":"matrix(0.5, 0, 0, -0.5, 3267.42, 559.99)","gradientUnits":"userSpaceOnUse","id":"\\u00010","x1":"-6518.78","x2":"-6518.78","y1":"1118.86","y2":"1090.06"},["stop",{"offset":"0","stopColor":"#5ea0ef"}],["stop",{"offset":"0.18","stopColor":"#589eed"}],["stop",{"offset":"0.41","stopColor":"#4897e9"}],["stop",{"offset":"0.66","stopColor":"#2e8ce1"}],["stop",{"offset":"0.94","stopColor":"#0a7cd7"}],["stop",{"offset":"1","stopColor":"#0078d4"}]]],["path",{"d":"M5.67,10.61H10v4.32H5.67Zm-5-5.76H5V.53H1.23a.6.6,0,0,0-.6.6Zm.6,10.08H5V10.61H.63v3.72A.6.6,0,0,0,1.23,14.93Zm-.6-5H5V5.57H.63Zm10.08,5h3.72a.6.6,0,0,0,.6-.6V10.61H10.71Zm-5-5H10V5.57H5.67Zm5,0H15V5.57H10.71Zm0-9.36V4.85H15V1.13a.6.6,0,0,0-.6-.6Zm-5,4.32H10V.53H5.67Z","fill":"url(#\\u00010)"}],["polygon",{"fill":"#32bedd","points":"17.37 10.7 17.37 15.21 13.5 17.47 13.5 12.96 17.37 10.7"}],["polygon",{"fill":"#9cebff","points":"17.37 10.7 13.5 12.97 9.63 10.7 13.5 8.44 17.37 10.7"}],["polygon",{"fill":"#50e6ff","points":"13.5 12.97 13.5 17.47 9.63 15.21 9.63 10.7 13.5 12.97"}],["polygon",{"fill":"#9cebff","points":"9.63 15.21 13.5 12.96 13.5 17.47 9.63 15.21"}],["polygon",{"fill":"#50e6ff","points":"17.37 15.21 13.5 12.96 13.5 17.47 17.37 15.21"}]]',
    },
  },
};

/**
 * App Registrations logo. Variants: `default` (default).
 * License: MIT. Trademarks belong to their owners.
 */
export function AzureAppRegistrationsLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props, useId());
}
