// Generated by @qeetrix/icons from icons/brand-icons/azure/azure-collaborative-service/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import { type ReactElement, useId } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 18, 18],
      scoped: true,
      children: '[["defs",null,["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00010","x1":"13.398","x2":"13.398","y1":"1.747","y2":"7.447"},["stop",{"offset":"0","stopColor":"#5ea0ef"}],["stop",{"offset":"1","stopColor":"#0078d4"}]],["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00011","x1":"2.85","x2":"2.85","y1":"5.341","y2":"11.041"},["stop",{"offset":"0","stopColor":"#a67af4"}],["stop",{"offset":"1","stopColor":"#773adc"}]],["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00012","x1":"11.829","x2":"11.829","y1":"12.149","y2":"20.004"},["stop",{"offset":"0","stopColor":"#3cd4c2"}],["stop",{"offset":"1","stopColor":"#258277"}]]],["path",{"d":"M14.428,6.615a.526.526,0,0,1-.438-.235L11.351,2.415a2.643,2.643,0,0,0-4.443,0L5.43,4.7a.525.525,0,0,1-.882-.57L6.026,1.839a3.694,3.694,0,0,1,6.2,0L14.865,5.8a.526.526,0,0,1-.437.817Z","fill":"#0078d4"}],["path",{"d":"M14.3,15.538H11.131a.526.526,0,0,1,0-1.051H14.3a2.644,2.644,0,0,0,2.22-4.078L15.342,8.581a.525.525,0,0,1,.883-.569L17.4,9.84a3.694,3.694,0,0,1-3.1,5.7Z","fill":"#37c2b1"}],["path",{"d":"M7.269,15.538H4.322a3.694,3.694,0,0,1-3.1-5.7L3.166,6.863a.525.525,0,0,1,.879.575L2.1,10.412a2.643,2.643,0,0,0,2.221,4.075H7.269a.526.526,0,0,1,0,1.051Z","fill":"#a67af4"}],["circle",{"cx":"13.398","cy":"4.597","fill":"url(#\\u00010)","r":"2.85"}],["path",{"d":"M2.849,5.382A2.85,2.85,0,1,0,5.7,8.231,2.85,2.85,0,0,0,2.849,5.382Z","fill":"url(#\\u00011)"}],["path",{"d":"M11.828,12.149A2.85,2.85,0,1,0,14.679,15,2.851,2.851,0,0,0,11.828,12.149Z","fill":"url(#\\u00012)"}]]',
    },
  },
};

/**
 * Collaborative Service logo. Variants: `default` (default).
 * License: MIT. Trademarks belong to their owners.
 */
export function AzureCollaborativeServiceLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props, useId());
}
