// Generated by @qeetrix/icons from icons/brand-icons/azure/azure-hosts/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import { type ReactElement, useId } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 18, 18],
      scoped: true,
      children: '[["defs",null,["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00010","x1":"9.02","x2":"9.02","y1":"5.46","y2":"0.65"},["stop",{"offset":"0","stopColor":"#198ab3"}],["stop",{"offset":"1","stopColor":"#32d4f5"}]],["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00011","x1":"8.98","x2":"8.98","y1":"11.97","y2":"7.17"},["stop",{"offset":"0","stopColor":"#198ab3"}],["stop",{"offset":"1","stopColor":"#32d4f5"}]],["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00012","x1":"9.02","x2":"9.02","y1":"17.34","y2":"14.32"},["stop",{"offset":"0","stopColor":"#198ab3"}],["stop",{"offset":"1","stopColor":"#32d4f5"}]]],["g",null,["path",{"d":"M8.46,5.46h1v9.6h-1Z","fill":"#32bedd"}],["path",{"d":"M15.48.65H2.56A.58.58,0,0,0,2,1.23V4.88a.58.58,0,0,0,.57.58H15.48a.57.57,0,0,0,.57-.58V1.23A.57.57,0,0,0,15.48.65Z","fill":"url(#\\u00010)"}],["path",{"d":"M15.44,7.17H2.52A.57.57,0,0,0,2,7.74V11.4a.56.56,0,0,0,.57.57H15.44A.57.57,0,0,0,16,11.4V7.74A.58.58,0,0,0,15.44,7.17Z","fill":"url(#\\u00011)"}],["circle",{"cx":"9.06","cy":"15.84","fill":"#7fba00","r":"1.51"}],["circle",{"cx":"9.02","cy":"15.83","fill":"url(#\\u00012)","r":"1.51"}],["g",null,["rect",{"fill":"#b4ec36","height":"1.05","rx":"0.15","width":"1.05","x":"13.72","y":"1.55"}],["rect",{"fill":"#b4ec36","height":"1.05","rx":"0.15","width":"1.05","x":"13.72","y":"3.36"}]],["g",null,["rect",{"fill":"#b4ec36","height":"1.05","rx":"0.15","width":"1.05","x":"13.72","y":"8.04"}],["rect",{"fill":"#b4ec36","height":"1.05","rx":"0.15","width":"1.05","x":"13.72","y":"9.85"}]]]]',
    },
  },
};

/**
 * Hosts logo. Variants: `default` (default).
 * License: MIT. Trademarks belong to their owners.
 */
export function AzureHostsLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props, useId());
}
