// Generated by @qeetrix/icons from icons/brand-icons/azure/azure-cost-alerts/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import { type ReactElement, useId } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 18, 18],
      scoped: true,
      children: '[["defs",null,["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00010","x1":"9","x2":"9","y1":"17.198","y2":"-3.282"},["stop",{"offset":"0","stopColor":"#5e9624"}],["stop",{"offset":"0.183","stopColor":"#629c25"}],["stop",{"offset":"0.435","stopColor":"#6dae2a"}],["stop",{"offset":"0.726","stopColor":"#7fcb30"}],["stop",{"offset":"0.822","stopColor":"#86d633"}]]],["g",null,["g",null,["path",{"d":"M17.5,2.5V13.332a.583.583,0,0,1-.584.581H12.4a.142.142,0,0,0-.142.141V15.8a.284.284,0,0,1-.456.224L9.079,13.943a.145.145,0,0,0-.087-.03H1.084A.583.583,0,0,1,.5,13.332V2.5a.584.584,0,0,1,.584-.582H16.916A.584.584,0,0,1,17.5,2.5Z","fill":"url(#\\u00010)"}],["path",{"d":"M10.772,7.857h0a3.811,3.811,0,0,0-1.424-.839V5.454a3.444,3.444,0,0,1,1.286.455.11.11,0,0,0,.111,0,.109.109,0,0,0,.056-.1V4.556a.11.11,0,0,0-.056-.1,3.37,3.37,0,0,0-1.4-.325V3.392a.11.11,0,0,0-.11-.11H8.563a.11.11,0,0,0-.11.11v.766a2.3,2.3,0,0,0-1.313.614A1.8,1.8,0,0,0,6.584,6.1a1.788,1.788,0,0,0,.454,1.271,3.874,3.874,0,0,0,1.415.836V9.7a3.684,3.684,0,0,1-.8-.2,2.6,2.6,0,0,1-.763-.382.111.111,0,0,0-.176.089V10.5a.112.112,0,0,0,.059.1,3.883,3.883,0,0,0,1.685.439v.874a.111.111,0,0,0,.11.111h.675a.111.111,0,0,0,.11-.111V11A2.39,2.39,0,0,0,10.72,10.4a1.77,1.77,0,0,0,.514-1.319A1.721,1.721,0,0,0,10.772,7.857ZM9.787,9.135v.008a.5.5,0,0,1-.438.53v-1.1C9.636,8.734,9.783,8.922,9.787,9.135ZM8.033,6.023a.512.512,0,0,1,.42-.536V6.639A.726.726,0,0,1,8.033,6.023Z","fill":"#f2f2f2"}]]]]',
    },
  },
};

/**
 * Cost Alerts logo. Variants: `default` (default).
 * License: MIT. Trademarks belong to their owners.
 */
export function AzureCostAlertsLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props, useId());
}
