// Generated by @qeetrix/icons from icons/brand-icons/azure/azure-data-lake-analytics/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import { type ReactElement, useId } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 18, 18],
      scoped: true,
      children: '[["defs",null,["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00010","x1":"8.98","x2":"8.98","y1":"15.81","y2":"2.19"},["stop",{"offset":"0","stopColor":"#1988d9"}],["stop",{"offset":"0.9","stopColor":"#54aef0"}]]],["path",{"d":"M11.08,17.37,1.37,13a1.48,1.48,0,0,1-.74-1.95L5,1.37a1.48,1.48,0,0,1,2-.74L16.63,5a1.48,1.48,0,0,1,.74,2L13,16.63A1.48,1.48,0,0,1,11.08,17.37Z","fill":"#50e6ff"}],["path",{"d":"M14.3,15.81H3.65a1.49,1.49,0,0,1-1.48-1.48V3.67A1.49,1.49,0,0,1,3.65,2.19H14.3a1.48,1.48,0,0,1,1.48,1.48V14.33A1.48,1.48,0,0,1,14.3,15.81Z","fill":"url(#\\u00010)"}],["path",{"d":"M8.73,9.9H7.12A.09.09,0,0,1,7,9.8a0,0,0,0,1,0,0L9,5.49a.11.11,0,0,1,.09,0h1.89a.09.09,0,0,1,.09.09.07.07,0,0,1,0,0L8.76,8.93H11a.09.09,0,0,1,.09.09.14.14,0,0,1,0,.06L7.37,13.36s-.28.25-.16-.1h0Z","fill":"#f2f2f2"}]]',
    },
  },
};

/**
 * Data Lake Analytics logo. Variants: `default` (default).
 * License: MIT. Trademarks belong to their owners.
 */
export function AzureDataLakeAnalyticsLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props, useId());
}
