// Generated by @qeetrix/icons from icons/brand-icons/azure/azure-offers/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import { type ReactElement, useId } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 18, 18],
      scoped: true,
      children: '[["defs",null,["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00010","x1":"13.41","x2":"7","y1":"14.43","y2":"3.72"},["stop",{"offset":"0","stopColor":"#0078d4"}],["stop",{"offset":"0.16","stopColor":"#1380da"}],["stop",{"offset":"0.53","stopColor":"#3c91e5"}],["stop",{"offset":"0.82","stopColor":"#559cec"}],["stop",{"offset":"1","stopColor":"#5ea0ef"}]]],["g",null,["g",null,["path",{"d":"M17.33,3.09,15,.81a.61.61,0,0,0-.42-.17L10.36.8A.53.53,0,0,0,10,1L.67,10.22a.55.55,0,0,0,0,.8l6.2,6.17a.57.57,0,0,0,.8,0L17,7.92a.53.53,0,0,0,.17-.35l.34-4A.58.58,0,0,0,17.33,3.09ZM14.56,4.6a1,1,0,1,1,1-1A1,1,0,0,1,14.56,4.6Z","fill":"url(#\\u00010)"}],["path",{"d":"M14.56,1.72a1.85,1.85,0,1,0,1.86,1.85A1.85,1.85,0,0,0,14.56,1.72Zm1,2.05a1,1,0,0,1-2-.4,1,1,0,0,1,.81-.81A1,1,0,0,1,15.58,3.77Z","fill":"#005ba1"}],["path",{"d":"M9.74,5.21l-.38-.38L9,5.21l-.49-.49.84-.87.87.87ZM5.13,9.05l-.49-.49L5.72,7.48,6,7.73l-.25-.25L6.21,8ZM7.65,5.57l.49.5L7.08,7.13l-.49-.49ZM3.8,11.15l-.87-.87.87-.84.49.49-.38.35.38.38Zm1.4.42,1.16,1.17-.5.49L4.7,12.07ZM7.64,15l-.87-.87.53-.49.34.35L8,13.67l.49.49ZM10,11.73l.5.49L9.39,13.28l-.49-.49Zm1.35-.37-.52-.49,1.08-1.08.49.49-1,1.08-.24-.24Zm1.93-1.92L12.75,9Zm0,0L12.75,9l.35-.39-.35-.34.49-.53.87.87ZM11.16,5.65l1.16,1.16-.5.5L10.66,6.15Z","fill":"#fff"}]]]]',
    },
  },
};

/**
 * Offers logo. Variants: `default` (default).
 * License: MIT. Trademarks belong to their owners.
 */
export function AzureOffersLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props, useId());
}
