// Generated by @qeetrix/icons from icons/brand-icons/azure/azure-container-apps-environments/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import { type ReactElement, useId } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 18, 18],
      scoped: true,
      children: '[["defs",null,["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00010","x1":"11.729","x2":"11.729","y1":"4.88","y2":"13.099"},["stop",{"offset":"0.001","stopColor":"#773adc"}],["stop",{"offset":"0.528","stopColor":"#6635bb"}],["stop",{"offset":"1","stopColor":"#552f99"}]],["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00011","x1":"6.35","x2":"6.35","y1":"13.914","y2":"4.198"},["stop",{"offset":"0.001","stopColor":"#773adc"}],["stop",{"offset":"0.307","stopColor":"#793ddd"}],["stop",{"offset":"0.532","stopColor":"#8046e1"}],["stop",{"offset":"0.731","stopColor":"#8c56e7"}],["stop",{"offset":"0.915","stopColor":"#9c6def"}],["stop",{"offset":"1","stopColor":"#a67af4"}]]],["g",null,["g",null,["path",{"d":"M8.617,8.644H.639V1.784A1.16,1.16,0,0,1,1.788.624H8.617ZM1.63,7.653h6V1.594H1.788a.158.158,0,0,0-.158.158h0Z","fill":"#949494"}],["path",{"d":"M17.5,8.644H9.523V.624h6.828A1.16,1.16,0,0,1,17.5,1.784Zm-6.987-.991h6V1.784a.157.157,0,0,0-.123-.187.2.2,0,0,0-.035,0H10.513Z","fill":"#949494"}],["path",{"d":"M8.617,17.485H1.788A1.149,1.149,0,0,1,.639,16.347V9.476H8.617ZM1.63,10.467v5.88a.158.158,0,0,0,.158.158H7.626V10.467Z","fill":"#949494"}],["path",{"d":"M16.351,17.485H9.523V9.476H17.5v6.871A1.149,1.149,0,0,1,16.351,17.485Zm-5.838-.991h5.838a.157.157,0,0,0,.158-.158V10.467h-6Z","fill":"#949494"}],["path",{"d":"M14.6,6.294a.294.294,0,0,0-.2-.278L9.044,4.205A.128.128,0,0,0,9,4.2H9a.132.132,0,0,0-.133.133v9.445A.133.133,0,0,0,9,13.911H9a.138.138,0,0,0,.049-.01l5.365-2.145a.292.292,0,0,0,.184-.272Z","fill":"url(#\\u00010)"}],["path",{"d":"M8.966,4.2l-5.293.966a.161.161,0,0,0-.13.158V12.63a.16.16,0,0,0,.126.157L8.962,13.91a.161.161,0,0,0,.191-.121.22.22,0,0,0,0-.036V4.358A.16.16,0,0,0,9,4.2.163.163,0,0,0,8.966,4.2Z","fill":"url(#\\u00011)"}],["path",{"d":"M6.52,5.656v6.8l1.842.3V5.335Zm-2.262.367v5.955l1.6.326V5.754Z","fill":"#b796f9","opacity":"0.5"}]]]]',
    },
  },
};

/**
 * Container Apps Environments logo. Variants: `default` (default).
 * License: MIT. Trademarks belong to their owners.
 */
export function AzureContainerAppsEnvironmentsLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props, useId());
}
