// Generated by @qeetrix/icons from icons/brand-icons/azure/azure-gear/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import { type ReactElement, useId } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 18, 18],
      scoped: true,
      children: '[["defs",null,["linearGradient",{"gradientTransform":"translate(0 -280)","gradientUnits":"userSpaceOnUse","id":"\\u00010","x1":"9","x2":"9","y1":"297.5","y2":"280.5"},["stop",{"offset":"0","stopColor":"#32bedd"}],["stop",{"offset":"1","stopColor":"#32d4f5"}]]],["path",{"d":"M17.5,9.9V8l-.3-.1-2.1-.7-.5-1.3,1.1-2.2L14.3,2.3l-.3.1-1.9,1-1.3-.5L9.9.5H8L7.9.8l-.7,2-1.3.6L3.7,2.3,2.3,3.7l.1.3,1,1.9L2.9,7.2.5,8.1V10l.3.1,2.1.7.5,1.3L2.3,14.3l1.4,1.4.3-.1,1.9-1,1.3.5.9,2.3H10l.1-.3.7-2.1,1.3-.5,2.2,1.1,1.4-1.4-.1-.2-1-1.9.5-1.3Z","fill":"url(#\\u00010)"}],["path",{"d":"M12.3,6.5l-.8.7a2.911,2.911,0,0,1-.3,4.2A2.906,2.906,0,0,1,7,11.1,2.91,2.91,0,0,1,7,7.2h.1l.6.5h.1V7.6l-.2-2c0-.1-.1-.1-.2-.1l-1.9.3a.1.1,0,0,0-.1.1h0l.6.5H6v.1H6a3.976,3.976,0,1,0,6.1,5.1A3.63,3.63,0,0,0,12.3,6.5Z","fill":"#fff"}]]',
    },
  },
};

/**
 * Gear logo. Variants: `default` (default).
 * License: MIT. Trademarks belong to their owners.
 */
export function AzureGearLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props, useId());
}
