// Generated by @qeetrix/icons from icons/brand-icons/azure/azure-mindaro/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import { type ReactElement, useId } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 18, 18],
      scoped: true,
      children: '[["defs",null,["linearGradient",{"gradientTransform":"matrix(1, 0, 0, -1, 0, 20)","gradientUnits":"userSpaceOnUse","id":"\\u00010","x1":"13.8","x2":"13.8","y1":"4.27","y2":"9.34"},["stop",{"offset":"0","stopColor":"#0078d4"}],["stop",{"offset":"0.16","stopColor":"#1380da"}],["stop",{"offset":"0.53","stopColor":"#3c91e5"}],["stop",{"offset":"0.82","stopColor":"#559cec"}],["stop",{"offset":"1","stopColor":"#5ea0ef"}]]],["g",null,["polygon",{"fill":"#949494","points":"13.23 2.49 13.23 7.33 9.08 9.76 9.08 4.91 13.23 2.49"}],["polygon",{"fill":"#b3b3b3","points":"13.23 2.49 9.08 4.92 4.93 2.49 9.08 0.07 13.23 2.49"}],["polygon",{"fill":"#e6e6e6","points":"9.08 4.92 9.08 9.76 4.93 7.33 4.93 2.49 9.08 4.92"}],["polygon",{"fill":"#949494","points":"8.61 10.67 8.61 15.49 4.47 17.92 4.47 13.09 8.61 10.67"}],["polygon",{"fill":"#b3b3b3","points":"8.61 10.67 4.47 13.1 0.31 10.67 4.47 8.24 8.61 10.67"}],["polygon",{"fill":"#e6e6e6","points":"4.47 13.1 4.47 17.92 0.31 15.49 0.31 10.67 4.47 13.1"}],["polygon",{"fill":"#50e6ff","points":"13.74 8.23 9.59 10.66 9.59 15.51 13.74 17.93 17.9 15.51 17.9 10.66 13.74 8.23"}],["path",{"d":"M16.75,15.74H10.89a.57.57,0,0,1-.56-.58h0V11.21a.51.51,0,0,1,.47-.55h5.91a.6.6,0,0,1,.56.59v3.9a.52.52,0,0,1-.43.59h-.09Z","fill":"url(#\\u00010)"}],["g",null,["path",{"d":"M12.84,14.78l-1.57-1.55a.18.18,0,0,1,0-.24l1.6-1.49a.18.18,0,0,1,.22,0l.14.14a.15.15,0,0,1,0,.22h0L12,13a.17.17,0,0,0,0,.23l1.21,1.24a.14.14,0,0,1,0,.21h0l-.1.1a.16.16,0,0,1-.22,0Z","fill":"#f2f2f2"}]],["g",null,["path",{"d":"M14.72,14.78l1.56-1.55a.16.16,0,0,0,0-.24L14.64,11.5a.15.15,0,0,0-.22,0h0l-.11.12a.16.16,0,0,0,0,.22L15.55,13a.16.16,0,0,1,0,.24l-1.19,1.22a.14.14,0,0,0,0,.21h0l.09.09a.14.14,0,0,0,.2.07A.16.16,0,0,0,14.72,14.78Z","fill":"#f2f2f2"}]]]]',
    },
  },
};

/**
 * Mindaro logo. Variants: `default` (default).
 * License: MIT. Trademarks belong to their owners.
 */
export function AzureMindaroLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props, useId());
}
