// Generated by @qeetrix/icons from icons/brand-icons/brands/black-forest-labs-bfl/mono.svg, icons/brand-icons/brands/black-forest-labs-bfl/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "mono" | "default";

const data: LogoData<Variant> = {
  defaultVariant: "mono",
  variants: {
    mono: {
      viewBox: [0, 0, 24, 24],
      props: { fill: "currentColor", fillRule: "evenodd" },
      children: '[["path",{"d":"M17.113 10.248H14.56l-2.553-3.616-7.963 11.27h2.558l5.405-7.654h2.552l-5.404 7.653h2.565l5.392-7.653L24 20 19.97 20v-2.091l-2.857-4.044-2.842 4.037V20H0L12.008 3l5.105 7.249z"}]]',
    },
    default: {
      viewBox: [0, 0, 24, 24],
      props: { fill: "currentColor", fillRule: "evenodd" },
      children: '[["path",{"d":"M17.113 10.248H14.56l-2.553-3.616-7.963 11.27h2.558l5.405-7.654h2.552l-5.404 7.653h2.565l5.392-7.653L24 20 19.97 20v-2.091l-2.857-4.044-2.842 4.037V20H0L12.008 3l5.105 7.249z"}]]',
    },
  },
};

/**
 * Black Forest Labs (bfl) logo. Variants: `mono` (default), `default`.
 * License: MIT. Trademarks belong to their owners.
 */
export function BlackForestLabsBflLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
