// Generated by @qeetrix/icons from icons/brand-icons/community/brainjs/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: brand-use. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 256, 256],
      children: '[["path",{"d":"M0 0h256v256H0z","fill":"#f3df49"}],["path",{"d":"m175.744 196.096l33.024 18.432l-10.112 23.808h-8.704l-7.168-10.88l-53.12-14.208zm-41.6-54.784l37.504 29.696v19.328l-50.304 19.456l-26.24 1.28l-20.224-27.136l19.072-26.112zm55.808-8.832l46.848 28.8l-5.76 35.328l-18.048 13.312l-34.56-19.584v-19.328l-6.528-37.376zm-24.96 2.304l5.888 27.776l-28.672-23.936z","fill":"#2e2e2c"}]]',
    },
  },
};

/**
 * Brain.js logo. Variants: `default` (default).
 * License: brand-use. Trademarks belong to their owners.
 */
export function BrainjsLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
