// Generated by @qeetrix/icons from icons/brand-icons/community/browsersync/default.svg.
// Each file is embedded unmodified: percent-decoding its data URI gives back the file byte for byte.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: brand-use. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: { width: 256, height: 387, src: 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 387"><path fill="%23f14646" d="M146.438 115.038V382.03c0 2.837 2.836 4.61 5.318 3.191l102.471-55.667c1.064-.71 1.773-1.773 1.773-3.191V174.96c0-1.418-.71-2.482-1.773-3.191l-102.116-59.923c-2.482-1.418-5.673.355-5.673 3.191M131.9 383.094V3.704c0-2.483-2.482-4.256-4.964-3.546L2.482 46.252C1.064 46.96 0 48.025 0 49.797v288.621c0 1.418 1.064 2.837 2.482 3.546l124.454 44.676c2.482.709 4.964-1.064 4.964-3.546"/></svg>' },
  },
};

/**
 * BrowserSync logo. Variants: `default` (default).
 * License: brand-use. Trademarks belong to their owners.
 */
export function BrowsersyncLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
