// Generated by @qeetrix/icons from icons/brand-icons/auth-badges/cointracker-badge/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC0-1.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 1024, 1024],
      children: '[["circle",{"cx":"512","cy":"512","r":"512","style":{"fill":"#0182ff"}}],["path",{"d":"M623.89 232a28.11 28.11 0 0 0-10.3 1.81l-226.27 98.86-.89.38a61.06 61.06 0 0 0-35 42.38 61 61 0 0 0 31.38 40.65L413.7 430l240.92-105.11v-62.84A30.7 30.7 0 0 0 623.89 232Zm30.79 119.24-209.54 91.49 93.36 40.72h.18v.18l31.09 13.58 68.46-29.94.62-.33a30.59 30.59 0 0 0 15.83-26.78Zm-305.36 38.33v149.28L654 671.87v-89.66a30.26 30.26 0 0 0-17.52-26.92l-98.5-43v-.18h-.18L413.12 457.7l-30.91-13.92-.81-.43a61 61 0 0 1-32.08-53.79Zm0 176.7V638a60.7 60.7 0 0 0 37.41 53.49l224.65 98.14a32.62 32.62 0 0 0 11.93 2.37A30.7 30.7 0 0 0 654 761.27v-62Z","style":{"fill":"#fff"}}]]',
    },
  },
};

/**
 * CoinTracker logo. Variants: `default` (default).
 * License: CC0-1.0. Trademarks belong to their owners.
 */
export function CointrackerBadgeLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
