// Generated by @qeetrix/icons from icons/brand-icons/auth-badges/derpibooru-badge/default.svg.
// Each file is embedded unmodified: percent-decoding its data URI gives back the file byte for byte.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC0-1.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: { width: 1024, height: 1024, src: 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024">%0A   <circle cx="512" cy="512" r="512" style="fill:%2394c1dd"/>%0A   <path d="m369.95 555.8-41.97 74.03c-29.11-9.78-63.23-15.3-104.33-13.83 36.86-48.21 90.9-60.41 146.3-60.2ZM292.6 692.22l14.52 7.26 36.23-63.89c-4.97-2.05-10.08-3.97-15.37-5.75l-35.37 62.39Zm214.14-344.8 21.78 65.33 18.15-72.59 79.85-3.63-65.33-39.93 21.78-72.59-61.71 50.81-61.71-43.56 29.03 72.59-61.71 36.29h65.33L369.93 555.78c6.11.02 12.23.2 18.35.49l118.43-208.88v.02Zm50.81 431.91c-74.57-5.53-111.33-101.41-214.2-143.74l44.96-79.29c80.49 3.87 160.2 28.35 191.02 1.63 54.44-47.18 134.28-195.99 83.47-333.91 181.47 333.91-7.26 562.56-105.25 555.31Zm-83.47-123.4c0-10.03-8.12-18.15-18.15-18.15s-18.15 8.12-18.15 18.15 8.12 18.15 18.15 18.15 18.15-8.12 18.15-18.15Zm116.14 72.59c0-10.03-8.12-18.15-18.15-18.15s-18.15 8.12-18.15 18.15 8.12 18.15 18.15 18.15 18.15-8.12 18.15-18.15Zm29.03-108.88c0-10.03-8.12-18.15-18.15-18.15s-18.15 8.12-18.15 18.15 8.12 18.15 18.15 18.15 18.15-8.12 18.15-18.15Zm72.59-108.88c0-10.03-8.12-18.15-18.15-18.15s-18.15 8.12-18.15 18.15 8.12 18.15 18.15 18.15 18.15-8.12 18.15-18.15Z" style="fill:%23fff"/>%0A</svg>%0A' },
  },
};

/**
 * Derpibooru logo. Variants: `default` (default).
 * License: CC0-1.0. Trademarks belong to their owners.
 */
export function DerpibooruBadgeLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
