// Generated by @qeetrix/icons from icons/brand-icons/brands/discourse/default.svg, icons/brand-icons/brands/discourse/mono.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC0-1.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default" | "mono";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 256, 259],
      props: { preserveAspectRatio: "xMidYMid" },
      children: '[["path",{"d":"M129.1 0C59.1 0 0 56.8 0 127v131.4l129-.2c70.2 0 127-59 127-129C256 59 199.1 0 129.1 0Z"}],["path",{"d":"M130.3 49.1a78.7 78.7 0 0 0-69.1 116.2L46.9 211l51.2-11.6a78.7 78.7 0 1 0 32.3-150.4Z","fill":"#FFF9AE"}],["path",{"d":"M191.9 176.5A78.6 78.6 0 0 1 98 199.4l-51.2 11.7 52-6.1a78.6 78.6 0 0 0 93.9-125 78.6 78.6 0 0 1-1 96.5Z","fill":"#00AEEF"}],["path",{"d":"M187.5 161.5a78.6 78.6 0 0 1-91 32.6l-49.6 17 51.2-11.6a78.6 78.6 0 0 0 80.2-134 78.6 78.6 0 0 1 9.2 96Z","fill":"#00A94F"}],["path",{"d":"M65.9 167a78.7 78.7 0 0 1 127-87 78.7 78.7 0 0 0-131.7 85.3L46.9 211l19-44Z","fill":"#F15D22"}],["path",{"d":"M61.2 165.3a78.7 78.7 0 0 1 117-99.9 78.7 78.7 0 0 0-121.9 98.7L47 211l14.2-45.8Z","fill":"#D0232B"}]]',
    },
    mono: {
      viewBox: [0, 0, 24, 24],
      props: { fill: "currentColor" },
      children: '[["path",{"d":"M12.103 0C18.666 0 24 5.485 24 11.997c0 6.51-5.33 11.99-11.9 11.99L0 24V11.79C0 5.28 5.532 0 12.103 0zm.116 4.563c-2.593-.003-4.996 1.352-6.337 3.57-1.33 2.208-1.387 4.957-.148 7.22L4.4 19.61l4.794-1.074c2.745 1.225 5.965.676 8.136-1.39 2.17-2.054 2.86-5.228 1.737-7.997-1.135-2.778-3.84-4.59-6.84-4.585h-.008z"}]]',
    },
  },
};

/**
 * Discourse logo. Variants: `default` (default), `mono`.
 * License: CC0-1.0. Trademarks belong to their owners.
 */
export function DiscourseLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
