// Generated by @qeetrix/icons from icons/brand-icons/brands/domo/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: Proprietary. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 24, 24],
      props: { fill: "currentColor" },
      children: '[["path",{"d":"M4.516 14.126c.37-.416.635-.929.75-1.496a3.206 3.206 0 0 0 6.282 0v2.567h1.062v-3.833l2.143 2.143 2.133-2.143v3.833h1.08V12.63a3.206 3.206 0 0 0 6.034.745v-2.766a3.205 3.205 0 0 0-6.033.745V8.787l-3.214 3.205-3.205-3.205v2.567a3.206 3.206 0 0 0-6.282 0 3.2 3.2 0 0 0-.75-1.495 3.2 3.2 0 0 0-2.391-1.072H0v6.41h2.125c.95 0 1.804-.414 2.39-1.071m16.592-4.272a2.139 2.139 0 1 1 0 4.277 2.139 2.139 0 0 1 0-4.277m-12.701 0a2.139 2.139 0 1 1 0 4.277 2.139 2.139 0 0 1 0-4.277m-7.345.005h1.203a2.138 2.138 0 0 1-.001 4.267H1.062ZM0 0h24v24H0Z"}]]',
    },
  },
};

/**
 * Domo logo. Variants: `default` (default).
 * License: Proprietary. Trademarks belong to their owners.
 */
export function DomoLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
