// Generated by @qeetrix/icons from icons/brand-icons/brands/entityframeworkcore/default.svg, icons/brand-icons/brands/entityframeworkcore/line.svg, icons/brand-icons/brands/entityframeworkcore/mono.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default" | "line" | "mono";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 128, 128],
      children: '[["path",{"d":"M0 0h128v128H0z","fill":"#512bd4"}],["path",{"d":"M73.022 80.632h-5.415V47.368H86.4v4.596H73.022V62.34h12.514v4.574H73.022v13.72zm-12.582 0H41.601V47.368h18.84v4.596H47.06v9.033h12.537v4.573H47.062v10.443H60.44v4.62z","fill":"#fff"}]]',
    },
    line: {
      viewBox: [0, 0, 128, 128],
      children: '[["path",{"d":"M73.022 80.632h-5.415V47.368H86.4v4.596H73.022V62.34h12.514v4.574H73.022v13.72zm-12.582 0H41.601V47.368h18.84v4.596H47.06v9.033h12.537v4.573H47.062v10.443H60.44v4.62zM0 0v128h128V0zm5.46 5.46H122.54V122.54H5.461z","fill":"#512bd4"}]]',
    },
    mono: {
      viewBox: [0, 0, 128, 128],
      props: { fill: "currentColor" },
      children: '[["path",{"d":"M0 0v128h128V0H0zm41.602 47.37h18.837v4.595H47.063v9.031h12.535v4.574H47.063v10.444h13.376v4.617H41.602V47.369zm26.005 0H86.4v4.595H73.021V62.34h12.514v4.572H73.021v13.719h-5.414V47.369z","fill":"currentColor"}]]',
    },
  },
};

/**
 * Entityframeworkcore logo. Variants: `default` (default), `line`, `mono`.
 * License: MIT. Trademarks belong to their owners.
 */
export function EntityframeworkcoreLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
