// Generated by @qeetrix/icons from icons/brand-icons/auth-badges/esea-badge/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC0-1.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 1024, 1024],
      children: '[["circle",{"cx":"512","cy":"512","r":"512","style":{"fill":"#0e9648"}}],["path",{"d":"m585.95 274.94-121.6 160.8L251 439l139 106.51-114.15 164L478.21 612l136.11 103V545.51L823 442.46l-411.25 95.85q27.93-29.72 37.88-46.59t14.7-42.57l133.28-3.58-11.66-170.63Z","style":{"fill":"#fff"}}]]',
    },
  },
};

/**
 * ESEA logo. Variants: `default` (default).
 * License: CC0-1.0. Trademarks belong to their owners.
 */
export function EseaBadgeLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
