// Generated by @qeetrix/icons from icons/brand-icons/brands/espn/default.svg.
// Each file is embedded unmodified: percent-decoding its data URI gives back the file byte for byte.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: Fair Use. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: { width: 554, height: 137, src: 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="554" height="137" viewBox="0 0 554 137"><path fill="%23E52534" d="M181.064.348c-20.608-.027-34.256 10.836-36.176 27.079a1600 1600 0 0 1-1.384 11.257H411.64s.504-3.957.896-7.133C414.552 15.188 407.6.35 382.312.35v.002S191.928.36 181.064.348M17.424.353l-4.706 38.331h121.6l4.688-38.33H17.422h.002zm408.184 0-4.696 38.331h131.824s.16-1.386.744-5.898C556.688 7.626 540.456.353 524.784.353zm-6.512 52.926-10.272 83.656 45.48-.016 10.28-83.624-45.488-.018zm86.4 0-10.288 83.656 45.48-.016 10.28-83.624-45.472-.018zm-494.552.012L.654 136.939h121.592l4.48-36.288-76.138-.008 1.926-15.648h76.108l3.896-31.702H10.95zm130.776 0c-3.336 21.832 7.592 31.701 23.08 31.701 8.424 0 61.52-.024 61.52-.024l-1.92 15.672-88.488.008-4.456 36.288s96.336.032 100.24 0c3.224-.232 25.76-.848 33.432-19.28 2.488-5.984 4.688-27.44 5.304-31.944 3.544-26.16-14.568-32.397-28.832-32.397-7.864 0-84.352-.024-99.88-.024m141.552 0L273 136.939h45.456l6.4-51.944h57.096c16.192 0 24.896-8.706 26.512-20.397a431 431 0 0 0 1.4-11.305H283.272z"/></svg>' },
  },
};

/**
 * ESPN logo. Variants: `default` (default).
 * License: Fair Use. Trademarks belong to their owners.
 */
export function EspnLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
