// Generated by @qeetrix/icons from icons/brand-icons/brands/everydotorg/default.svg, icons/brand-icons/brands/everydotorg/mono.svg.
// Each file is embedded unmodified: percent-decoding its data URI gives back the file byte for byte.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC0-1.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default" | "mono";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: { width: 24, height: 24, src: 'data:image/svg+xml,<svg fill="%232BD7B0" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Every.org</title><path d="M18.151 9.36c0-4.467-3.728-7.855-8.517-7.855C4.278 1.505 0 6.028 0 11.63c0 6.038 4.808 10.864 11.28 10.864 6.474 0 12.266-5.13 12.72-11.848h-2.953c-.549 5.034-4.807 8.896-9.766 8.896-4.77 0-8.31-3.502-8.31-7.912 0-3.975 2.953-7.174 6.663-7.174 3.104 0 5.546 2.12 5.546 4.903 0 2.309-1.666 4.24-3.88 4.24v2.952c3.918 0 6.851-3.274 6.851-7.192"/></svg>' },
    mono: { width: 24, height: 24, src: 'data:image/svg+xml,<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Every.org</title><path d="M18.151 9.36c0-4.467-3.728-7.855-8.517-7.855C4.278 1.505 0 6.028 0 11.63c0 6.038 4.808 10.864 11.28 10.864 6.474 0 12.266-5.13 12.72-11.848h-2.953c-.549 5.034-4.807 8.896-9.766 8.896-4.77 0-8.31-3.502-8.31-7.912 0-3.975 2.953-7.174 6.663-7.174 3.104 0 5.546 2.12 5.546 4.903 0 2.309-1.666 4.24-3.88 4.24v2.952c3.918 0 6.851-3.274 6.851-7.192"/></svg>' },
  },
};

/**
 * Every.org logo. Variants: `default` (default), `mono`.
 * License: CC0-1.0. Trademarks belong to their owners.
 */
export function EverydotorgLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
