// Generated by @qeetrix/icons from icons/brand-icons/auth-badges/expo-badge/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC0-1.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 1024, 1024],
      children: '[["circle",{"cx":"512","cy":"512","r":"512","style":{"fill":"#002"}}],["path",{"d":"M498.62 441c4.18-6.17 8.77-7 12.49-7s9.91.79 14.1 7c33 45.33 87.48 135.63 127.67 202.25 26.2 43.44 46.33 76.8 50.46 81 15.51 15.94 36.77 6 49.12-12.07C764.62 694.46 768 682 768 668.62c0-9.08-176.21-336.8-194-364.07-17.06-26.24-22.62-32.87-51.83-32.87h-21.82c-29.12 0-33.33 6.63-50.39 32.87-17.75 27.27-194 355-194 364.07 0 13.34 3.38 25.84 15.54 43.64 12.35 18.08 33.61 28 49.12 12.07 4.13-4.25 24.26-37.61 50.46-81 40.23-66.67 94.53-156.97 127.54-202.33Z","style":{"fill":"#fff"}}]]',
    },
  },
};

/**
 * Expo logo. Variants: `default` (default).
 * License: CC0-1.0. Trademarks belong to their owners.
 */
export function ExpoBadgeLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
