// Generated by @qeetrix/icons from icons/brand-icons/brands/flutter/default.svg, icons/brand-icons/brands/flutter/mono.svg.
// Each file is embedded unmodified: percent-decoding its data URI gives back the file byte for byte.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC0-1.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default" | "mono";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: { width: 256, height: 317, src: 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 317">%0A  <defs>%0A    <linearGradient x1="4%25" y1="27%25" x2="75.9%25" y2="52.9%25" id="a">%0A      <stop offset="0%25"/>%0A      <stop stop-opacity="0" offset="100%25"/>%0A    </linearGradient>%0A  </defs>%0A  <path fill="%2347C5FB" d="M158 0 0 158l49 48L255 0zM157 145l-85 85 49 50 49-49 85-86z"/>%0A  <path fill="%2300569E" d="m121 280 37 37h97l-85-86z"/>%0A  <path fill="%2300B5F8" d="m72 230 48-48 50 49-49 49z"/>%0A  <path fill-opacity=".8" fill="url(%23a)" d="m121 280 41-14 4-31z"/>%0A</svg>%0A' },
    mono: { width: 24, height: 24, src: 'data:image/svg+xml,<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Flutter</title><path d="M14.314 0L2.3 12 6 15.7 21.684.013h-7.357zm.014 11.072L7.857 17.53l6.47 6.47H21.7l-6.46-6.468 6.46-6.46h-7.37z"/></svg>' },
  },
};

/**
 * Flutter logo. Variants: `default` (default), `mono`.
 * License: CC0-1.0. Trademarks belong to their owners.
 */
export function FlutterLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
