// Generated by @qeetrix/icons from icons/brand-icons/gcp/gcp-permissions/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: Apache-2.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 24, 24],
      props: { xmlSpace: "preserve" },
      children: '[["path",{"d":"M0 0h24v24H0z","fill":"none"}],["g",{"fillRule":"evenodd"},["path",{"d":"M12 12c2.9 0 5.2-2.3 5.2-5.2S14.9 1.6 12 1.6 6.8 3.9 6.8 6.8 9.1 12 12 12m0 2.7c-3.5 0-10.5 1.7-10.5 5.2v2.6h21v-2.6c0-3.5-7-5.2-10.5-5.2","fill":"#5C85DE"}],["path",{"d":"M12 12c2.9 0 5.2-2.3 5.2-5.2S14.9 1.6 12 1.6zm0 2.7v7.8h10.5v-2.6c0-3.5-7-5.2-10.5-5.2","fill":"#3367D6"}]]]',
    },
  },
};

/**
 * Permissions logo. Variants: `default` (default).
 * License: Apache-2.0. Trademarks belong to their owners.
 */
export function GcpPermissionsLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
