// Generated by @qeetrix/icons from icons/brand-icons/gcp/gcp-configuration-management/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: Apache-2.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 24, 24],
      children: '[["path",{"d":"M5.76 8.64v3.88A8.16 8.16 0 0 0 12 20.29V5.73Z","style":{"fill":"#4285f4"}}],["path",{"d":"m12 20.29.66-.19a8.16 8.16 0 0 0 5.58-7.58V8.64L12 5.73Zm5.79-16.15a3 3 0 0 0-.29 0l.83-1-.57-.48-1.67 2 2 1.66.48-.57-1-.85a2 2 0 0 1 .26 0 2.64 2.64 0 0 1 2.64 2.64 2.6 2.6 0 0 1-.29 1.19l.55.56.09-.13a3.5 3.5 0 0 0 .4-1.62 3.39 3.39 0 0 0-3.43-3.4","style":{"fill":"#aecbfa"}}],["path",{"d":"m5.67 17.7-.61.44.76 1.06a3 3 0 0 1-.27 0 2.64 2.64 0 0 1-1.33-4.29l-.39-.68a1 1 0 0 0-.11.11 3.38 3.38 0 0 0 1.65 5.58 3 3 0 0 0 .29.05l-1 .74.44.61 2.11-1.5Z","style":{"fill":"#4285f4"}}]]',
    },
  },
};

/**
 * Configuration Management logo. Variants: `default` (default).
 * License: Apache-2.0. Trademarks belong to their owners.
 */
export function GcpConfigurationManagementLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
