// Generated by @qeetrix/icons from icons/brand-icons/gcp/gcp-cloud-audit-logs/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: Apache-2.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 24, 24],
      children: '[["defs",null],["g",null,["g",null,["path",{"d":"M12.77 12.72a1.07 1.07 0 0 1-1.52 0l-1.49-1.49.76-.76L12 11.93l4.2-4.2.81.79Z","style":{"fill":"#4285f4"}}],["path",{"d":"M16 11.59a.91.91 0 0 0-.81.81 3.21 3.21 0 0 1-2.86 2.76 3.25 3.25 0 0 1-1.84-.36 3.19 3.19 0 0 1 1.2-6 3.1 3.1 0 0 1 1.21.13.9.9 0 0 0 1-.28.91.91 0 0 0-.4-1.45A5 5 0 0 0 7 12.49 5 5 0 0 0 12.48 17 5 5 0 0 0 17 12.63a.91.91 0 0 0-1-1Z","style":{"fill":"#669df6"}}],["path",{"d":"M12 18a2 2 0 1 1-2 2 2 2 0 0 1 2-2","style":{"fill":"#aecbfa"}}],["path",{"d":"M12 2a2 2 0 1 1-2 2 2 2 0 0 1 2-2","style":{"fill":"#aecbfa"}}],["path",{"d":"M0 0h24v24H0z","style":{"fill":"none"}}]],["path",{"d":"M18 20a1 1 0 0 1-.71-1.7L20 15.59V8.41L17.31 5.7a1 1 0 0 1 0-1.41 1 1 0 0 1 1.42 0l3 3A1 1 0 0 1 22 8v8a1 1 0 0 1-.29.7l-3 3a1 1 0 0 1-.71.3","style":{"fill":"#4285f4"}}],["path",{"d":"M6 20a1 1 0 0 1-.71-.3l-3-3A1 1 0 0 1 2 16V8a1 1 0 0 1 .29-.71l3-3a1 1 0 0 1 1.42 0 1 1 0 0 1 0 1.41L4 8.41v7.18l2.69 2.71a1 1 0 0 1 0 1.42A1 1 0 0 1 6 20","style":{"fill":"#669df6"}}]]]',
    },
  },
};

/**
 * Cloud Audit Logs logo. Variants: `default` (default).
 * License: Apache-2.0. Trademarks belong to their owners.
 */
export function GcpCloudAuditLogsLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
