// Generated by @qeetrix/icons from icons/brand-icons/gcp/gcp-network-tiers/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: Apache-2.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 24, 24],
      children: '[["defs",null],["g",null,["path",{"d":"M7.3 15.7A5.92 5.92 0 0 1 6 12H2a9.9 9.9 0 0 0 2.46 6.54ZM12 2a10 10 0 0 0-6.55 2.45l2.84 2.84A6 6 0 0 1 18 12h4A10 10 0 0 0 12 2","style":{"fill":"#669df6"}}],["circle",{"cx":"8","cy":"19","r":"2","style":{"fill":"#aecbfa"}}],["circle",{"cx":"19","cy":"16","r":"2","style":{"fill":"#4285f4"}}],["circle",{"cx":"14","cy":"20","r":"2","style":{"fill":"#669df6"}}],["path",{"d":"M6 12H2a10 10 0 0 0 .44 2.91l4-.79A6 6 0 0 1 6 12","style":{"fill":"#4285f4"}}],["g",null,["circle",{"cx":"5","cy":"8","r":"2","style":{"fill":"#aecbfa"}}]],["path",{"d":"M17.61 9.88A6 6 0 0 1 18 12h4a10 10 0 0 0-.43-2.91Z","style":{"fill":"#4285f4"}}]]]',
    },
  },
};

/**
 * Network Tiers logo. Variants: `default` (default).
 * License: Apache-2.0. Trademarks belong to their owners.
 */
export function GcpNetworkTiersLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
