// Generated by @qeetrix/icons from icons/brand-icons/gcp/gcp-bare-metal-solutions/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: Apache-2.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 24, 24],
      children: '[["g",{"fill":"#4285f4"},["path",{"d":"m12 20.99-9-4.276 4.5-1.428L12 19.57l4.5-4.285 4.5 1.428z"}],["path",{"d":"m12 3 7.5 7.143-7.5 7.143-7.5-7.143zm0 1.429-6 5.714 6 5.714 6-5.714z"}],["path",{"d":"m18.841 12.285.659.63-7.5 7.228-7.501-7.228.659-.63.627.6-.062.06L12 18.835l6.276-5.89-.063-.06z"}]]]',
    },
  },
};

/**
 * Bare Metal Solutions logo. Variants: `default` (default).
 * License: Apache-2.0. Trademarks belong to their owners.
 */
export function GcpBareMetalSolutionsLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
