// Generated by @qeetrix/icons from icons/brand-icons/gcp/gcp-datapol/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: Apache-2.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 24, 24],
      children: '[["defs",null],["g",null,["path",{"d":"M9.65 3.87h8.29v1.87H9.65z","style":{"fill":"#4285f4"}}],["path",{"d":"M4.55 11.35h8.29v1.87H4.55z","style":{"fill":"#4285f4"}}],["path",{"d":"M9.65 18.21h8.29v1.87H9.65z","style":{"fill":"#4285f4"}}],["path",{"d":"m6.57 13.38 3.25 5.51-1.66.93-3.25-5.51z","style":{"fill":"#4285f4","fillRule":"evenodd"}}],["path",{"d":"m6.8 10.91 3.25-5.51-1.61-.91L5.19 10z","style":{"fill":"#4285f4","fillRule":"evenodd"}}],["path",{"d":"M7.48 7.66 5.82 4.85 7.48 2h3.31l1.65 2.85-1.65 2.81z","style":{"fillRule":"evenodd","fill":"#aecbfa"}}],["path",{"d":"m13.21 15.14-1.65-2.8 1.65-2.86h3.31l1.66 2.86-1.66 2.8z","style":{"fillRule":"evenodd","fill":"#aecbfa"}}],["path",{"d":"M3.65 15.14 2 12.34l1.65-2.86h3.31l1.65 2.86-1.65 2.8z","style":{"fillRule":"evenodd","fill":"#aecbfa"}}],["path",{"d":"m17.04 7.66-1.65-2.81L17.04 2h3.31L22 4.85l-1.65 2.81z","style":{"fillRule":"evenodd","fill":"#aecbfa"}}],["path",{"d":"m17.04 22-1.65-2.81 1.65-2.85h3.31L22 19.19 20.35 22z","style":{"fillRule":"evenodd","fill":"#aecbfa"}}],["path",{"d":"m7.48 22-1.66-2.81 1.66-2.85h3.31l1.65 2.85L10.79 22z","style":{"fillRule":"evenodd","fill":"#aecbfa"}}]]]',
    },
  },
};

/**
 * Datapol logo. Variants: `default` (default).
 * License: Apache-2.0. Trademarks belong to their owners.
 */
export function GcpDatapolLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
