// Generated by @qeetrix/icons from icons/brand-icons/gcp/gcp-iot-core/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: Apache-2.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 24, 24],
      children: '[["g",null,["path",{"d":"M12.54 12.43V8a1.14 1.14 0 1 0-1 0v4.42H7.27V9.6a1.14 1.14 0 0 0-.53-2.15 1.14 1.14 0 0 0-.52 2.15v2.83H6a3.82 3.82 0 1 1 1.4-7.38A5.22 5.22 0 0 1 16.84 5a4 4 0 0 1 1.23-.2 3.83 3.83 0 0 1 0 7.66h-.25V9.6a1.14 1.14 0 1 0-1.06 0v2.83Z","style":{"fillRule":"evenodd","fill":"#4285f4"}}],["path",{"d":"M7.27 15.39a2 2 0 0 1 1.54 2 2.07 2.07 0 1 1-2.59-2v-2.96h1Zm-.53 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2m11.08-3a2.07 2.07 0 1 1-1.06 0v-2.95h1.06Zm-.53 3a1 1 0 0 0 .39-1.94 1 1 0 1 0-.39 1.94m-4.75-.43a2.06 2.06 0 1 1-1 0v-5.5h1.06Zm-.54 3a1 1 0 1 0-.93-.62 1 1 0 0 0 .93.6Z","style":{"fill":"#669df6","fillRule":"evenodd"}}]]]',
    },
  },
};

/**
 * Iot Core logo. Variants: `default` (default).
 * License: Apache-2.0. Trademarks belong to their owners.
 */
export function GcpIotCoreLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
