// Generated by @qeetrix/icons from icons/brand-icons/gcp/gcp-data-labeling/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: Apache-2.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 24, 24],
      children: '[["defs",null],["g",null,["path",{"d":"M20 4H7.7a1.12 1.12 0 0 0-1 .63L3 12h2l3-6h11v1h2V5a1 1 0 0 0-1-1","style":{"fill":"#a6cafd"}}],["circle",{"cx":"10","cy":"12","r":"3","style":{"fill":"#559cfc"}}],["circle",{"cx":"10","cy":"12","r":"1","style":{"fill":"#fff"}}],["path",{"d":"M0 0h8v1H0z","style":{"fill":"#fff"}}],["rect",{"height":"2","rx":"1","style":{"fill":"#669df6"},"width":"5","x":"17","y":"8"}],["rect",{"height":"2","rx":"1","style":{"fill":"#669df6"},"width":"8","x":"14","y":"11"}],["rect",{"height":"2","rx":"1","style":{"fill":"#669df6"},"width":"5","x":"17","y":"14"}],["path",{"d":"M19 17v1H8l-2-4H4l2.69 5.37a1.12 1.12 0 0 0 1 .63H20a1 1 0 0 0 1-1v-2Z","style":{"fill":"#a6cafd"}}],["path",{"d":"M10 12H2","style":{"fill":"none","stroke":"#2683fb","strokeMiterlimit":"10"}}]]]',
    },
  },
};

/**
 * Data Labeling logo. Variants: `default` (default).
 * License: Apache-2.0. Trademarks belong to their owners.
 */
export function GcpDataLabelingLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
