// Generated by @qeetrix/icons from icons/brand-icons/gcp/gcp-artifact-registry/default.svg.
// Each file is embedded unmodified: percent-decoding its data URI gives back the file byte for byte.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: Apache-2.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: { width: 24, height: 24, src: 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" width="24" height="24" baseProfile="tiny" overflow="visible" viewBox="0 0 24 24"><path fill="none" d="M0 0h24v24H0z"/><path fill="%235C85DE" fill-rule="evenodd" d="m6 2.4-5.2 3v13.7l5.2 3v-2.6l-3-1.7V6.7L6 5z"/><path fill="%233367D6" fill-rule="evenodd" d="M.8 8v8.5L3 17.8V6.7z"/><path fill="%233367D6" fill-rule="evenodd" d="M.8 8 3 7.5v-.8z"/><path fill="%235C85DE" fill-rule="evenodd" d="M18 2.4V5l3 1.7v11.1l-3 1.7v2.6l5.2-3V5.4z"/><path fill="%233367D6" fill-rule="evenodd" d="m21 17.8 2.2-1.3V8L21 6.7z"/><path fill="%233367D6" fill-rule="evenodd" d="m21 7.5 2.2.5L21 6.7zm0 9.6v.7l2.2-1.3z"/><g fill-rule="evenodd"><path fill="%235C85DE" d="M12 5.5 9 7.1l3 1.6 3-1.6z"/><path fill="%233367D6" d="m12.4 12.4 2.9-1.6V7.7l-2.9 1.6zm-.7-3.1-3-1.6v3.1l3 1.6z"/><path fill="%235C85DE" d="m8.56 11.376-2.9 1.6 2.9 1.6 2.8-1.6z"/><path fill="%233367D6" d="m8.76 18.276 2.9-1.6v-3.2l-2.9 1.6zm-.5-3.2-2.9-1.6v3.2l2.9 1.6z"/><path fill="%235C85DE" d="m15.52 11.376-2.9 1.6 2.9 1.6 2.9-1.6z"/><path fill="%233367D6" d="m15.82 18.276 2.9-1.6v-3.2l-2.9 1.6zm-.6-3.2-2.9-1.6v3.2l2.9 1.6z"/></g></svg>' },
  },
};

/**
 * Artifact Registry logo. Variants: `default` (default).
 * License: Apache-2.0. Trademarks belong to their owners.
 */
export function GcpArtifactRegistryLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
