// Generated by @qeetrix/icons from icons/brand-icons/gcp/gcp-compute-engine/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: Apache-2.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 24, 24],
      children: '[["defs",null],["g",null,["path",{"d":"M9 9h6v6H9z","style":{"fill":"#aecbfa"}}],["path",{"d":"M11 2h2v4h-2zM7 2h2v4H7zm8 0h2v4h-2z","style":{"fill":"#669df6"}}],["path",{"d":"M11 18h2v4h-2zm-4 0h2v4H7zm8 0h2v4h-2zm3-5v-2h4v2zm0 4v-2h4v2zm0-8V7h4v2z","style":{"fill":"#4285f4"}}],["path",{"d":"M2 13v-2h4v2zm0 4v-2h4v2zm0-8V7h4v2z","style":{"fill":"#669df6"}}],["path",{"d":"M5 5v14h14V5Zm12 12H7V7h10Z","style":{"fill":"#aecbfa"}}],["path",{"d":"M9 15h6l-3-3z","style":{"fill":"#669df6"}}],["path",{"d":"m12 12 3 3V9z","style":{"fill":"#4285f4"}}]]]',
    },
  },
};

/**
 * Compute Engine logo. Variants: `default` (default).
 * License: Apache-2.0. Trademarks belong to their owners.
 */
export function GcpComputeEngineLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
