// Generated by @qeetrix/icons from icons/brand-icons/gcp/gcp-network-topology/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: Apache-2.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 24, 24],
      children: '[["path",{"d":"M3.95 8.261a2.37 2.37 0 0 0 1.526.001v8.123c0 1.668 1.29 3.02 2.881 3.02 1.534 0 2.789-1.257 2.876-2.843l.005-.177v-1.347a2.37 2.37 0 0 0 1.524.097v1.25c0 2.548-1.972 4.615-4.405 4.615-2.363 0-4.292-1.95-4.4-4.398l-.005-.217zm15.336 9.15c.946 0 1.714.803 1.714 1.794S20.232 21 19.286 21c-.947 0-1.715-.804-1.715-1.795s.768-1.794 1.715-1.794M15.643 4.075c2.433 0 4.405 2.066 4.405 4.615v8.048a2.37 2.37 0 0 0-1.524 0V8.69c0-1.668-1.29-3.02-2.881-3.02s-2.881 1.352-2.881 3.02v1.424a2.38 2.38 0 0 0-1.525.097l.001-1.521c0-2.549 1.972-4.615 4.405-4.615m-3.5 6.755c.947 0 1.714.803 1.714 1.795 0 .99-.767 1.794-1.714 1.794s-1.714-.803-1.714-1.794c0-.992.767-1.795 1.714-1.795M4.714 4c.947 0 1.715.804 1.715 1.795s-.768 1.794-1.715 1.794C3.768 7.59 3 6.786 3 5.795S3.768 4 4.714 4","fill":"#4285F4"}]]',
    },
  },
};

/**
 * Network Topology logo. Variants: `default` (default).
 * License: Apache-2.0. Trademarks belong to their owners.
 */
export function GcpNetworkTopologyLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
