// Generated by @qeetrix/icons from icons/brand-icons/auth-badges/glimesh-badge/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC0-1.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 1024, 1024],
      children: '[["circle",{"cx":"512","cy":"512","r":"512","style":{"fill":"#2c49cb"}}],["path",{"d":"m362.42 256 168 248.74H803zM803 519.26H530.39L362.42 768zm-453.14-256v497.48L517.83 512z","style":{"fill":"#fff"}}]]',
    },
  },
};

/**
 * Glimesh logo. Variants: `default` (default).
 * License: CC0-1.0. Trademarks belong to their owners.
 */
export function GlimeshBadgeLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
