// Generated by @qeetrix/icons from icons/brand-icons/brands/gmail/default.svg, icons/brand-icons/brands/gmail/mono.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC0-1.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default" | "mono";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 49.4, 512, 399.42],
      children: '[["g",{"fill":"none","fillRule":"evenodd"},["g",{"fillRule":"nonzero"},["path",{"d":"M34.91 448.818h81.454V251L0 163.727V413.91c0 19.287 15.622 34.91 34.91 34.91z","fill":"#4285f4"}],["path",{"d":"M395.636 448.818h81.455c19.287 0 34.909-15.622 34.909-34.909V163.727L395.636 251z","fill":"#34a853"}],["path",{"d":"M395.636 99.727V251L512 163.727v-46.545c0-43.142-49.25-67.782-83.782-41.891z","fill":"#fbbc04"}]],["path",{"d":"M116.364 251V99.727L256 204.455 395.636 99.727V251L256 355.727z","fill":"#ea4335"}],["path",{"d":"M0 117.182v46.545L116.364 251V99.727L83.782 75.291C49.25 49.4 0 74.04 0 117.18z","fill":"#c5221f","fillRule":"nonzero"}]]]',
    },
    mono: {
      viewBox: [0, 0, 24, 24],
      props: { fill: "currentColor" },
      children: '[["path",{"d":"M24 5.457v13.909c0 .904-.732 1.636-1.636 1.636h-3.819V11.73L12 16.64l-6.545-4.91v9.273H1.636A1.636 1.636 0 0 1 0 19.366V5.457c0-2.023 2.309-3.178 3.927-1.964L5.455 4.64 12 9.548l6.545-4.91 1.528-1.145C21.69 2.28 24 3.434 24 5.457z"}]]',
    },
  },
};

/**
 * Gmail logo. Variants: `default` (default), `mono`.
 * License: CC0-1.0. Trademarks belong to their owners.
 */
export function GmailLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
