// Generated by @qeetrix/icons from icons/brand-icons/brands/gozle/default.svg.
// Each file is embedded unmodified: percent-decoding its data URI gives back the file byte for byte.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC0-1.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: { width: 109, height: 87, src: 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 109 87"><path fill="%2300ACEE" d="M43.081 71.275c-15.506 0-28.076-12.57-28.076-28.077S27.575 15.122 43.081 15.122c12.247 0 22.653 7.84 26.494 18.776l16.428 5.427C84.102 17.291 65.613 0 43.081 0 19.286 0 0 19.29 0 43.081c0 23.796 19.29 43.086 43.081 43.086 19.642 0 36.216-13.146 41.4-31.12L70.24 50.34c-3.16 12.046-14.12 20.935-27.158 20.935m65.09-14.071L59.977 41.281l-4.834 14.63 48.194 15.922z"/></svg>%0A' },
  },
};

/**
 * Gozle logo. Variants: `default` (default).
 * License: CC0-1.0. Trademarks belong to their owners.
 */
export function GozleLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
