// Generated by @qeetrix/icons from icons/brand-icons/brands/inference/mono.svg, icons/brand-icons/brands/inference/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "mono" | "default";

const data: LogoData<Variant> = {
  defaultVariant: "mono",
  variants: {
    mono: {
      viewBox: [0, 0, 24, 24],
      props: { fill: "currentColor", fillRule: "evenodd" },
      children: '[["path",{"d":"M22 21.376h-4.89V2.62H22v18.756zM14.532 21.376h-3.469V2.62h3.469v18.756zM8.764 21.376h-2.66V2.62h2.66v18.756zM3.903 21.376H2V2.62h1.903v18.756z"}]]',
    },
    default: {
      viewBox: [0, 0, 24, 24],
      props: { fill: "currentColor", fillRule: "evenodd" },
      children: '[["path",{"d":"M22 21.376h-4.89V2.62H22v18.756zM14.532 21.376h-3.469V2.62h3.469v18.756zM8.764 21.376h-2.66V2.62h2.66v18.756zM3.903 21.376H2V2.62h1.903v18.756z"}]]',
    },
  },
};

/**
 * Inference logo. Variants: `mono` (default), `default`.
 * License: MIT. Trademarks belong to their owners.
 */
export function InferenceLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
