// Generated by @qeetrix/icons from icons/brand-icons/auth-badges/intuit-badge/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC0-1.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 1024, 1024],
      children: '[["circle",{"cx":"512","cy":"512","r":"512","style":{"fill":"#236cff"}}],["path",{"d":"M520.55 522.12c0 31.32 25.97 54.23 58.96 54.23s58.98-22.91 58.98-54.23v-71.95h-31.94v68.24c0 16.9-11.72 28.29-27.13 28.29s-27.13-11.33-27.13-28.29v-68.24h-31.94l.2 71.95Zm203.28-43.15h38.11v95h31.94v-95h38.11v-28.85H723.82v28.85Zm-20.64-28.85h-31.94v123.85h31.94V450.12Zm-311.68 28.85h38.11v95h31.94v-95h38.08v-28.85H391.5v28.85Zm-167.57-28.85H192v123.85h31.94V450.12Zm150.75 51.73c0-31.32-25.97-54.2-58.98-54.2s-58.98 22.88-58.98 54.2v72.12h31.94v-68.24c0-16.9 11.72-28.29 27.13-28.29s27.13 11.33 27.13 28.29v68.24h31.94l-.2-72.12h.03Z","style":{"fill":"#fff"}}]]',
    },
  },
};

/**
 * Intuit logo. Variants: `default` (default).
 * License: CC0-1.0. Trademarks belong to their owners.
 */
export function IntuitBadgeLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
