// Generated by @qeetrix/icons from icons/brand-icons/auth-badges/jagex-badge/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC0-1.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 1024, 1024],
      children: '[["circle",{"cx":"512","cy":"512","r":"512","style":{"fill":"#ef7d00"}}],["path",{"d":"M370.81 512 256 740.59l167.42.25 206.26-410.87h62.42l-91.37 181.9 91.25 181.89H577.21l23.37 46.83H768L653.18 512 768 283.41l-167.42-.25-16.36 32.79L394.3 694.03h-62.41l91.35-181.91-91.21-181.86h114.75l-23.36-46.85H256L370.81 512z","style":{"fill":"#fff"}}]]',
    },
  },
};

/**
 * Jagex logo. Variants: `default` (default).
 * License: CC0-1.0. Trademarks belong to their owners.
 */
export function JagexBadgeLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
