// Generated by @qeetrix/icons from icons/brand-icons/auth-badges/kaspersky-badge/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC0-1.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 1024, 1024],
      children: '[["circle",{"cx":"512","cy":"512","r":"512","style":{"fill":"#00a88e"}}],["path",{"d":"M357.67 736h81.46V224h-81.46v512Zm342.11-373.91h-99.3L481.79 518.02v48.87L603.58 736h100.85L561.69 542.06l138.09-179.97Z","style":{"fill":"#fff"}}]]',
    },
  },
};

/**
 * Kaspersky logo. Variants: `default` (default).
 * License: CC0-1.0. Trademarks belong to their owners.
 */
export function KasperskyBadgeLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
