// Generated by @qeetrix/icons from icons/brand-icons/brands/knowbe4/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: Trademark. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [98.6385, 11.193, 62.8462, 60.4853],
      children: '[["path",{"d":"M121.5383,63.581h-22.8998l6.6871-6.606c-2.7363-4.5543-4.3104-9.8869-4.3104-15.587,0-16.7368,13.4588-30.195,30.1956-30.195s30.2739,13.4582,30.2739,30.195c0,16.4197-12.9182,29.7889-29.216,30.2903l.055-13.275c9.0196-.519,16.1741-7.9974,16.1741-17.1475,0-9.4858-7.69-16.9535-17.1764-16.9535s-17.1759,7.4676-17.1759,16.9535c0,2.0143.3466,3.948.9836,5.7438l6.4307-6.34v22.9566","fill":"#EF4623"}]]',
    },
  },
};

/**
 * KnowBe4 logo. Variants: `default` (default).
 * License: Trademark. Trademarks belong to their owners.
 */
export function Knowbe4Logo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
