// Generated by @qeetrix/icons from icons/brand-icons/community/lexical/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: brand-use. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 256, 243],
      children: '[["path",{"d":"M43.39 75.932h47.729v21.695H43.39z","fill":"#76b6ff"}],["path",{"d":"M101.966 75.932h47.729v21.695h-47.729z"}],["path",{"d":"M160.542 75.932h19.526v21.695h-19.526zM43.39 110.644h78.102v21.695H43.39zm88.949 0h47.729v21.695h-47.729z","fill":"#76b6ff"}],["path",{"d":"M43.39 145.356h47.729v21.695H43.39z"}],["path",{"d":"M101.966 145.356h47.729v21.695h-47.729z","fill":"#76b6ff"}],["path",{"d":"M160.542 145.356h19.526v21.695h-19.526z"}],["path",{"d":"M236.475 0v21.695H212.61v199.593h23.865v21.695H169.22v-21.695h21.695V21.695H169.22V0zm-56.407 32.542v21.695H21.695v134.509h158.373v21.695H0V32.542zm75.932 0v177.899h-32.542v-21.695h10.847V54.237h-10.847V32.542z"}]]',
    },
  },
};

/**
 * Lexical logo. Variants: `default` (default).
 * License: brand-use. Trademarks belong to their owners.
 */
export function LexicalLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
