// Generated by @qeetrix/icons from icons/brand-icons/brands/luma/color.svg, icons/brand-icons/brands/luma/mono.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import { type ReactElement, useId } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "color" | "mono";

const data: LogoData<Variant> = {
  defaultVariant: "color",
  variants: {
    color: {
      viewBox: [0, 0, 24, 24],
      scoped: true,
      children: '[["path",{"d":"M2 5.999L12.392 0v24L2 18V5.999z","fill":"#000"}],["path",{"d":"M12.392 24L2 18l10.392-6 10.393 6-10.393 6z","fill":"url(#\\u00010)"}],["path",{"d":"M12.392 24L2 18l10.392-6 10.393 6-10.393 6z","fill":"url(#\\u00011)"}],["path",{"d":"M2 5.999L12.392 0v24L2 18V5.999z","fill":"url(#\\u00012)"}],["path",{"d":"M12.392 24L2 18l10.392-6 10.393 6-10.393 6z","fill":"url(#\\u00013)"}],["path",{"d":"M2 5.999L12.392 0v24L2 18V5.999z","fill":"url(#\\u00014)"}],["defs",null,["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00010","x1":"2","x2":"22.785","y1":"18","y2":"18"},["stop",{"stopColor":"#00A"}],["stop",{"offset":"1","stopColor":"#A78DFF"}]],["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00011","x1":"2","x2":"22.785","y1":"18","y2":"18"},["stop",{"stopColor":"#00A"}],["stop",{"offset":"1","stopColor":"#A78DFF"}]],["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00012","x1":"13.748","x2":"4.672","y1":"22.642","y2":"3.745"},["stop",{"stopColor":"#004EFF"}],["stop",{"offset":"1","stopColor":"#0FF"}]],["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00013","x1":"2","x2":"22.785","y1":"18","y2":"18"},["stop",{"stopColor":"#00A"}],["stop",{"offset":"1","stopColor":"#A78DFF"}]],["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00014","x1":"13.748","x2":"4.672","y1":"22.642","y2":"3.745"},["stop",{"stopColor":"#004EFF"}],["stop",{"offset":"1","stopColor":"#0FF"}]]]]',
    },
    mono: {
      viewBox: [0, 0, 24, 24],
      props: { fill: "currentColor", fillRule: "evenodd" },
      children: '[["path",{"d":"M12.393 24L2 17.998l10.393-6 10.392 6-10.393 6z","fillOpacity":".66"}],["path",{"d":"M2 5.999L12.393 0v24L2 18V5.999z","fillOpacity":".66"}]]',
    },
  },
};

/**
 * Luma logo. Variants: `color` (default), `mono`.
 * License: MIT. Trademarks belong to their owners.
 */
export function LumaLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props, useId());
}
