// Generated by @qeetrix/icons from icons/brand-icons/community/mesos/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: brand-use. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 256, 291],
      children: '[["path",{"d":"M190.18 177.17v-63.366l-54.642 31.735z","fill":"#fff"}],["path",{"d":"M186.645 107.622L131.907 75.97v63.379zm-61.852 31.725V75.968L70.016 107.62zm-3.541-69.46L66.527 38.052v63.472z","fill":"#00aede"}],["path",{"d":"m186.645 183.26l-54.738-31.624v63.368zm-61.852 31.745v-63.371L70.016 183.26z","fill":"#fff"}],["path",{"d":"m252.113 145.538l-54.818-31.73v63.36zM59.399 101.524V38.052L4.263 69.887z","fill":"#00aede"}],["path",{"d":"m121.252 221.095l-54.725-31.72v63.451z","fill":"#fff"}],["path",{"d":"M59.399 252.827v-63.45l-55.136 31.72z","fill":"#00aede"}],["path",{"d":"m121.252 145.538l-54.725-31.73v63.36z","fill":"#fff"}],["path",{"d":"M190.18 101.524V38.052l-54.642 31.835z","fill":"#00aede"}],["path",{"d":"M131.909.319v63.357l54.738-31.72zM70.015 31.956l54.777 31.72V.32zm116.63 226.954l-54.738-31.616v63.348zm-61.852 31.734v-63.352l-54.777 31.62z","fill":"#fff"}],["path",{"d":"M255.66 215.005v-63.371l-54.676 31.627zM59.399 177.17v-63.465L4.263 145.539zm-3.527 6.09L.656 151.635v63.368zm199.788-43.913V75.968l-54.676 31.652zm-3.547-69.46l-54.818-31.835v63.472zm0 151.208l-54.818-31.72v63.451z","fill":"#00aede"}],["path",{"d":"M190.18 252.827v-63.45l-54.642 31.72z","fill":"#fff"}],["path",{"d":"M55.872 107.622L.656 75.97v63.379z","fill":"#00aede"}]]',
    },
  },
};

/**
 * Apache Mesos logo. Variants: `default` (default).
 * License: brand-use. Trademarks belong to their owners.
 */
export function MesosLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
