// Generated by @qeetrix/icons from icons/brand-icons/brands/microsoft-fabric-iq/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: Microsoft proprietary product icon; no express redistribution license supplied; maintainer review required. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import { type ReactElement, useId } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [5.550000190734863, 4.09999942779541, 421, 491.1999816894531],
      scoped: true,
      children: '[["defs",null,["radialGradient",{"cx":"-717.9","cy":"537.3","fx":"-717.9","fy":"537.3","gradientTransform":"translate(-13124.9 13698.3) rotate(88.8) scale(18.1 -25.3) skewX(-1.2)","gradientUnits":"userSpaceOnUse","id":"\\u00010","r":"16.4"},["stop",{"offset":"0","stopColor":"#1c154f"}],["stop",{"offset":".5","stopColor":"#02573a"}],["stop",{"offset":"1","stopColor":"#5dbf87"}]],["radialGradient",{"cx":"-714.2","cy":"544","fx":"-714.2","fy":"544","gradientTransform":"translate(-6843.4 15947.5) rotate(75.7) scale(18.3 -19.7) skewX(-3.3)","gradientUnits":"userSpaceOnUse","id":"\\u00011","r":"16.4"},["stop",{"offset":"0","stopColor":"#092231"}],["stop",{"offset":".3","stopColor":"#084348"}],["stop",{"offset":".7","stopColor":"#17844a"}],["stop",{"offset":".9","stopColor":"#5bbe81"}]],["linearGradient",{"gradientTransform":"translate(0 502) scale(1 -1)","gradientUnits":"userSpaceOnUse","id":"\\u00012","x1":"147.6","x2":"268.9","y1":"255.5","y2":"444"},["stop",{"offset":"0","stopColor":"#5cc098"}],["stop",{"offset":".6","stopColor":"#82ca9c"}],["stop",{"offset":"1","stopColor":"#b6dba8"}]]],["path",{"d":"M199.5,228.2c10.2-6.4,22.9-6.4,33.1,0l185.7,115.8c11,6.8,11,23.9,0,30.7l-185.7,115.8c-10.2,6.4-22.9,6.4-33.1,0L13.8,374.7c-11-6.8-11-23.9,0-30.7l185.7-115.8Z","style":{"fill":"url(#\\u00010)"}}],["path",{"d":"M199.5,118.6c10.2-6.4,22.9-6.4,33.1,0l185.7,115.8c11,6.8,11,23.9,0,30.7l-185.7,115.8c-10.2,6.4-22.9,6.4-33.1,0L13.8,265c-11-6.8-11-23.9,0-30.7l185.7-115.8Z","style":{"fill":"url(#\\u00011)"}}],["path",{"d":"M199.5,8.9c10.2-6.4,22.9-6.4,33.1,0l185.7,115.8c11,6.8,11,23.9,0,30.7l-185.7,115.8c-10.2,6.4-22.9,6.4-33.1,0L13.8,155.4c-11-6.8-11-23.9,0-30.7L199.5,8.9Z","style":{"fill":"url(#\\u00012)"}}]]',
    },
  },
};

/**
 * Microsoft Fabric IQ logo. Variants: `default` (default).
 * License: Microsoft proprietary product icon; no express redistribution license supplied; maintainer review required. Trademarks belong to their owners.
 */
export function MicrosoftFabricIqLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props, useId());
}
