// Generated by @qeetrix/icons from icons/brand-icons/brands/microsoft-fabric-data-science/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: Microsoft proprietary product icon; no express redistribution license supplied; maintainer review required. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import { type ReactElement, useId } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 48, 48],
      props: { fill: "currentColor" },
      scoped: true,
      children: '[["path",{"d":"M25.328 43.834c-.73.28-1.58.21-2.27-.25-1.15-.76-1.81-2.5-1.04-3.65l9.729-14.467 8.938 10.028c.61.69.55 1.74-.14 2.35-.14.13-.3.23-.47.3z","fill":"url(#\\u00010)"}],["path",{"d":"M17.488 26.517 8.02 12.27a1.6 1.6 0 0 1-.25-.87c0-.92.75-1.67 1.67-1.67.23 0 .54-.04.74.04l15.397 7.24-.88 1.75z","fill":"url(#\\u00011)"}],["path",{"d":"M23.548 43.844c-.17-.06-.33-.15-.49-.25a2.51 2.51 0 0 1-.7-3.47L40.855 12.28a1.663 1.663 0 0 0-.78-2.41L25.328 4.18c-.28-.11-.58-.17-.89-.17s-.61.06-.89.16L8.8 9.86c.2-.08.42-.13.65-.13s.44.05.64.13l11.638 5.61c.85.44 1.45 1.259 1.45 2.269 0 .63-.23 1.2-.62 1.64L8.2 35.495c-.61.69-.55 1.74.14 2.35.14.13.3.23.47.3l14.748 5.69","fill":"url(#\\u00012)"}],["path",{"d":"m10.12 9.86 11.638 5.608c.69.35 1.2.96 1.38 1.71l17.967-6.029c-.09-.58-.46-1.07-.99-1.29L25.369 4.17c-.28-.11-.58-.17-.89-.17s-.61.06-.89.16L8.84 9.85c.2-.08.42-.13.65-.13s.44.05.64.13z","fill":"url(#\\u00013)"}],["defs",null,["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00010","x1":"24.758","x2":"35.906","y1":"32.326","y2":"41.684"},["stop",{"stopColor":"#292941"}],["stop",{"offset":".22","stopColor":"#114A85"}],["stop",{"offset":".44","stopColor":"#0A5BA0"}],["stop",{"offset":".65","stopColor":"#0669B6"}]],["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00011","x1":"11.729","x2":"22.428","y1":"7.77","y2":"23.058"},["stop",{"offset":".22","stopColor":"#114A85"}],["stop",{"offset":".85","stopColor":"#0669B6"}]],["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00012","x1":"24.438","x2":"24.438","y1":"43.844","y2":"4.01"},["stop",{"offset":".1","stopColor":"#288CD9"}],["stop",{"offset":".75","stopColor":"#3CC5EE"}]],["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00013","x1":"23.288","x2":"26.517","y1":"4.24","y2":"16.268"},["stop",{"stopColor":"#A1ECFF","stopOpacity":".9"}],["stop",{"offset":".92","stopColor":"#A1ECFF","stopOpacity":"0"}]]]]',
    },
  },
};

/**
 * Microsoft Fabric Data Science logo. Variants: `default` (default).
 * License: Microsoft proprietary product icon; no express redistribution license supplied; maintainer review required. Trademarks belong to their owners.
 */
export function MicrosoftFabricDataScienceLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props, useId());
}
