// Generated by @qeetrix/icons from icons/brand-icons/brands/microsoft-azure/default.svg, icons/brand-icons/brands/microsoft-azure/mono-lobe.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import { type ReactElement, useId } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default" | "mono-lobe";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 96, 96],
      scoped: true,
      children: '[["defs",null,["linearGradient",{"gradientTransform":"matrix(1 0 0 -1 1075 158)","gradientUnits":"userSpaceOnUse","id":"\\u00010","x1":"-1032.17","x2":"-1059.21","y1":"145.31","y2":"65.43"},["stop",{"offset":"0","stopColor":"#114a8b"}],["stop",{"offset":"1","stopColor":"#0669bc"}]],["linearGradient",{"gradientTransform":"matrix(1 0 0 -1 1075 158)","gradientUnits":"userSpaceOnUse","id":"\\u00011","x1":"-1023.73","x2":"-1029.98","y1":"108.08","y2":"105.97"},["stop",{"offset":"0","stopOpacity":".3"}],["stop",{"offset":".07","stopOpacity":".2"}],["stop",{"offset":".32","stopOpacity":".1"}],["stop",{"offset":".62","stopOpacity":".05"}],["stop",{"offset":"1","stopOpacity":"0"}]],["linearGradient",{"gradientTransform":"matrix(1 0 0 -1 1075 158)","gradientUnits":"userSpaceOnUse","id":"\\u00012","x1":"-1027.16","x2":"-997.48","y1":"147.64","y2":"68.56"},["stop",{"offset":"0","stopColor":"#3ccbf4"}],["stop",{"offset":"1","stopColor":"#2892df"}]]],["path",{"d":"M33.34 6.54h26.04l-27.03 80.1a4.15 4.15 0 0 1-3.94 2.81H8.15a4.14 4.14 0 0 1-3.93-5.47L29.4 9.38a4.15 4.15 0 0 1 3.94-2.83z","fill":"url(#\\u00010)"}],["path",{"d":"M71.17 60.26H29.88a1.91 1.91 0 0 0-1.3 3.31l26.53 24.76a4.17 4.17 0 0 0 2.85 1.13h23.38z","fill":"#0078d4"}],["path",{"d":"M33.34 6.54a4.12 4.12 0 0 0-3.95 2.88L4.25 83.92a4.14 4.14 0 0 0 3.91 5.54h20.79a4.44 4.44 0 0 0 3.4-2.9l5.02-14.78 17.91 16.7a4.24 4.24 0 0 0 2.67.97h23.29L71.02 60.26H41.24L59.47 6.55z","fill":"url(#\\u00011)"}],["path",{"d":"M66.6 9.36a4.14 4.14 0 0 0-3.93-2.82H33.65a4.15 4.15 0 0 1 3.93 2.82l25.18 74.62a4.15 4.15 0 0 1-3.93 5.48h29.02a4.15 4.15 0 0 0 3.93-5.48z","fill":"url(#\\u00012)"}]]',
    },
    "mono-lobe": {
      viewBox: [0, 0, 24, 24],
      props: { fill: "currentColor", fillRule: "evenodd" },
      children: '[["path",{"d":"M18.397 15.296H7.4a.51.51 0 00-.347.882l7.066 6.595c.206.192.477.298.758.298h6.226l-2.706-7.775z","fillOpacity":".75"}],["path",{"d":"M8.295.857c-.477 0-.9.304-1.053.756L.495 21.605a1.11 1.11 0 001.052 1.466h5.43c.477 0 .9-.304 1.053-.755l1.341-3.975-2.318-2.163a.51.51 0 01.347-.882h3L15.271.857H8.295z","fillOpacity":".5"}],["path",{"d":"M17.193 1.613a1.11 1.11 0 00-1.052-.756h-7.81.035c.477 0 .9.304 1.052.756l6.748 19.992a1.11 1.11 0 01-1.052 1.466h-.12 7.895a1.11 1.11 0 001.052-1.466L17.193 1.613z"}]]',
    },
  },
};

/**
 * Microsoft Azure logo. Variants: `default` (default), `mono-lobe`.
 * License: MIT. Trademarks belong to their owners.
 */
export function MicrosoftAzureLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props, useId());
}
