// Generated by @qeetrix/icons from icons/brand-icons/community/micro-python/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: brand-use. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 256, 256],
      props: { fill: "currentColor" },
      children: '[["path",{"d":"M0 0h122.76v199.86h10.48V0H256v256h-56.14V56.14h-10.48V256H66.62V56.14l-10.48.375V256H0zm237.287 208.094h-14.971v25.45h14.97z"}]]',
    },
  },
};

/**
 * MicroPython logo. Variants: `default` (default).
 * License: brand-use. Trademarks belong to their owners.
 */
export function MicroPythonLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
