// Generated by @qeetrix/icons from icons/brand-icons/brands/midudev/default.svg.
// Each file is embedded unmodified: percent-decoding its data URI gives back the file byte for byte.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: { width: 228, height: 198, src: 'data:image/svg+xml,<svg viewBox="0 0 228 198" xmlns="http://www.w3.org/2000/svg" width="228" height="198" preserveAspectRatio="xMidYMid"><path fill="%23199afc" d="M73.2 126.4c-15 15-15 39.3 0 54.3L19 126.4C4 111.5 4 87.2 19 72.2L73.2 18c15-15 39.2-15 54.2 0s15 39.2 0 54.2z"/><path fill="%231d5682" d="m73.2 126.4 27.1-27.1 27.1 27.1c15 15 15 39.3 0 54.3-15 14.9-39.2 14.9-54.2 0-15-15-15-39.3 0-54.3"/><path fill="%23199afc" d="M185.5 84.3c8.3-8.2 8.3-21.7 0-29.9l30 29.9c8.2 8.3 8.2 21.7 0 30l-30 30c-8.3 8.3-21.7 8.3-30 0s-8.3-21.7 0-30z"/><path fill="%231d5682" d="m185.5 84.3-15 15-15-15c-8.3-8.2-8.3-21.7 0-29.9 8.3-8.3 21.7-8.3 30 0 8.3 8.2 8.3 21.7 0 29.9"/></svg>' },
  },
};

/**
 * midudev logo. Variants: `default` (default).
 * License: MIT. Trademarks belong to their owners.
 */
export function MidudevLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
