// Generated by @qeetrix/icons from icons/brand-icons/brands/million/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import { type ReactElement, useId } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 256, 182],
      props: { preserveAspectRatio: "xMidYMid" },
      scoped: true,
      children: '[["defs",null,["radialGradient",{"cx":"50%","cy":"49.999%","fx":"50%","fy":"49.999%","gradientTransform":"translate(0 -380193.475) skewY(90)","id":"\\u00010","r":"32.306%"},["stop",{"offset":"0%","stopColor":"#845CE7"}],["stop",{"offset":"100%","stopColor":"#AF73D8"}]],["radialGradient",{"cx":"50.061%","cy":"104.167%","fx":"50.061%","fy":"104.167%","gradientTransform":"translate(0 -35820434.112) skewY(90)","id":"\\u00011","r":"67.301%"},["stop",{"offset":"0%","stopColor":"#845CE7"}],["stop",{"offset":"100%","stopColor":"#AF73D8"}]],["radialGradient",{"cx":"99.122%","cy":"34.222%","fx":"99.122%","fy":"34.222%","gradientTransform":"translate(0 -56809933.375) skewY(90)","id":"\\u00012","r":"42.521%"},["stop",{"offset":"0%","stopColor":"#845CE7"}],["stop",{"offset":"100%","stopColor":"#AF73D8"}]],["radialGradient",{"cx":".878%","cy":"34.21%","fx":".878%","fy":"34.21%","gradientTransform":"translate(0 -5447320.88) skewY(90)","id":"\\u00013","r":"42.506%"},["stop",{"offset":"0%","stopColor":"#845CE7"}],["stop",{"offset":"100%","stopColor":"#AF73D8"}]]],["path",{"d":"M64.995 153.355c11.777-16.858 35.745-28.399 63.396-28.399 27.65 0 51.62 11.54 63.397 28.4-11.778 16.856-35.746 28.397-63.397 28.397-27.651 0-51.619-11.54-63.396-28.398Z","fill":"url(#\\u00010)"}],["path",{"d":"M64.567 28.097C76.337 11.418 100.289 0 127.923 0c27.633 0 51.586 11.418 63.356 28.097-11.77 16.679-35.723 28.097-63.356 28.097-27.634 0-51.586-11.418-63.356-28.097Z","fill":"url(#\\u00011)"}],["path",{"d":"M129.133 91.209c-17.124 16.54-40.349 25.831-64.566 25.831-24.217 0-47.443-9.292-64.567-25.831l64.567-63.112 64.566 63.112Z","fill":"url(#\\u00012)"}],["path",{"d":"M256 91.24c-17.124 16.54-40.35 25.831-64.567 25.831-24.217 0-47.443-9.292-64.567-25.831l64.567-63.143L256 91.24Z","fill":"url(#\\u00013)"}]]',
    },
  },
};

/**
 * Million logo. Variants: `default` (default).
 * License: MIT. Trademarks belong to their owners.
 */
export function MillionLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props, useId());
}
