// Generated by @qeetrix/icons from icons/brand-icons/auth-badges/minerstat-badge/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC0-1.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 1024, 1024],
      children: '[["circle",{"cx":"512","cy":"512","r":"512","style":{"fill":"#5767ff"}}],["path",{"d":"M668.45 310.69a45 45 0 0 1 44.86 44.86v312.9a45 45 0 0 1-44.86 44.86h-312.9a45.08 45.08 0 0 1-44.86-44.86v-312.9a45.08 45.08 0 0 1 44.86-44.86h312.9m0-22.37h-312.9a67.35 67.35 0 0 0-67.23 67.23v312.9a67.35 67.35 0 0 0 67.23 67.23h312.9a67.35 67.35 0 0 0 67.23-67.23v-312.9a67.35 67.35 0 0 0-67.23-67.23zM567.92 415.07A78 78 0 0 0 512 438.68a78.21 78.21 0 0 0-134.21 54.68v93.2a22.37 22.37 0 0 0 44.74 0v-93.2a33.55 33.55 0 0 1 67.1 0v93.2a22.37 22.37 0 0 0 44.74 0v-93.2a33.55 33.55 0 0 1 67.1 0v93.2a22.37 22.37 0 0 0 44.74 0v-93.2a78.44 78.44 0 0 0-78.29-78.29z","style":{"fill":"#fff"}}]]',
    },
  },
};

/**
 * minerstat logo. Variants: `default` (default).
 * License: CC0-1.0. Trademarks belong to their owners.
 */
export function MinerstatBadgeLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
