// Generated by @qeetrix/icons from icons/brand-icons/auth-badges/mongodb-badge/default.svg.
// Each file is embedded unmodified: percent-decoding its data URI gives back the file byte for byte.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC0-1.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: { width: 1024, height: 1024, src: 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024">%0A   <circle cx="512" cy="512" r="512" style="fill:%2300684a"/>%0A   <path d="M567.84 263.33c-26.98-31.87-50.21-64.24-54.96-70.96-.5-.5-1.25-.5-1.75 0-4.75 6.72-27.98 39.09-54.96 70.96-231.57 294.04 36.47 492.48 36.47 492.48l2.25 1.49c2 30.63 6.99 74.69 6.99 74.69h19.98s5-43.82 6.99-74.69l2.25-1.74c.25 0 268.3-198.19 36.72-492.23Zm-55.96 488s-11.99-10.21-15.24-15.44v-.5l14.49-320.19c0-1 1.5-1 1.5 0l14.49 320.19v.5c-3.25 5.23-15.24 15.44-15.24 15.44Z" style="fill:%23fff"/>%0A</svg>%0A' },
  },
};

/**
 * MongoDB logo. Variants: `default` (default).
 * License: CC0-1.0. Trademarks belong to their owners.
 */
export function MongodbBadgeLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
