// Generated by @qeetrix/icons from icons/brand-icons/auth-badges/niconico-badge/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC0-1.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 1024, 1024],
      children: '[["circle",{"cx":"512","cy":"512","r":"512"}],["path",{"d":"M697.4 367.1H547.5l86.8-86.8-21.5-21.5-100.4 100.4-101.9-100.4-21.5 21.5 86.1 86.1H327.3c-22.3-.4-40.6 17.8-40.2 40.2v236c0 21.8 17.7 39.4 39.4 39.4h46.6l25.8 40.9c1.7 2.7 4.7 4.3 7.9 4.3 3.5.3 6.8-1.4 8.6-4.3l25.8-40.9h136.3l25.8 40.9c1.9 2.9 5.2 4.6 8.6 4.3 3.6 0 6.4-1.5 7.9-4.3l25.8-40.9h51.6c21.8 0 39.4-17.7 39.4-39.4V405.8c-.1-21.4-17.7-38.7-39.2-38.7z","style":{"fill":"#fff"}}]]',
    },
  },
};

/**
 * niconico logo. Variants: `default` (default).
 * License: CC0-1.0. Trademarks belong to their owners.
 */
export function NiconicoBadgeLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
