// Generated by @qeetrix/icons from icons/brand-icons/brands/opera/default.svg, icons/brand-icons/brands/opera/mono.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC0-1.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import { type ReactElement, useId } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default" | "mono";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 1000, 1000],
      props: { xmlSpace: "preserve" },
      scoped: true,
      children: '[["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00010","x1":"416.6229","x2":"416.6229","y1":"16.304","y2":"985.446"},["stop",{"offset":".3","stopColor":"#ff1b2d"}],["stop",{"offset":".4381","stopColor":"#fa1a2c"}],["stop",{"offset":".5939","stopColor":"#ed1528"}],["stop",{"offset":".7581","stopColor":"#d60e21"}],["stop",{"offset":".9272","stopColor":"#b70519"}],["stop",{"offset":"1","stopColor":"#a70014"}]],["path",{"d":"M335.4 781.8c-55.3-65.3-91.1-161.7-93.5-270v-23.6c2.4-108.3 38.2-204.7 93.5-270C407.2 125.1 513.8 66 632.8 66c73.2 0 141.8 22.4 200.4 61.3C745.2 48.5 629.2.5 501.9 0H500C223.9 0 0 223.9 0 500c0 268.2 211.1 487 476.2 499.4 7.9.4 15.8.6 23.8.6 128 0 244.8-48.1 333.2-127.2-58.6 38.8-127.1 61.2-200.4 61.2-119 0-225.6-59.1-297.4-152.2z","fill":"url(#\\u00010)"}],["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00011","x1":"667.7092","x2":"667.7092","y1":"73.4257","y2":"930.5844"},["stop",{"offset":"0","stopColor":"#9c0000"}],["stop",{"offset":".7","stopColor":"#ff4b4b"}]],["path",{"d":"M335.4 218.2c45.9-54.2 105.1-86.8 169.9-86.8 145.6 0 263.5 165 263.5 368.6s-118 368.6-263.5 368.6c-64.7 0-124-32.7-169.9-86.8C407.2 874.9 513.8 934 632.8 934c73.2 0 141.8-22.4 200.4-61.2C935.6 781.2 1000 648.1 1000 500c0-148.1-64.4-281.2-166.8-372.7C774.6 88.4 706.1 66 632.8 66c-119 0-225.6 59.1-297.4 152.2z","fill":"url(#\\u00011)"}]]',
    },
    mono: {
      viewBox: [0, 0, 24, 24],
      props: { fill: "currentColor" },
      children: '[["path",{"d":"M8.051 5.238c-1.328 1.566-2.186 3.883-2.246 6.48v.564c.061 2.598.918 4.912 2.246 6.479 1.721 2.236 4.279 3.654 7.139 3.654 1.756 0 3.4-.537 4.807-1.471C17.879 22.846 15.074 24 12 24c-.192 0-.383-.004-.57-.014C5.064 23.689 0 18.436 0 12 0 5.371 5.373 0 12 0h.045c3.055.012 5.84 1.166 7.953 3.055-1.408-.93-3.051-1.471-4.81-1.471-2.858 0-5.417 1.42-7.14 3.654h.003zM24 12c0 3.556-1.545 6.748-4.002 8.945-3.078 1.5-5.946.451-6.896-.205 3.023-.664 5.307-4.32 5.307-8.74 0-4.422-2.283-8.075-5.307-8.74.949-.654 3.818-1.703 6.896-.205C22.455 5.25 24 8.445 24 12z"}]]',
    },
  },
};

/**
 * Opera logo. Variants: `default` (default), `mono`.
 * License: CC0-1.0. Trademarks belong to their owners.
 */
export function OperaLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props, useId());
}
