// Generated by @qeetrix/icons from icons/brand-icons/brands/passport-js/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 400, 500],
      children: '[["g",{"fill":"none","fillRule":"evenodd"},["path",{"d":"M200 0C89.5 0 0 89.5 0 200h100c0-55.2 44.8-100 100-100V0Z","fill":"#D6FF00"}],["path",{"d":"M400 200C400 89.5 310.5 0 200 0v100c55.2 0 100 44.8 100 100h100Z","fill":"#34E27A"}],["path",{"d":"M200 400c110.5 0 200-89.5 200-200H300c0 55.2-44.8 100-100 100v100Z","fill":"#00B9F1"}],["path",{"d":"M100 400V200H0v300h200V400H100Z","fill":"#FFF"}]]]',
    },
  },
};

/**
 * Passport.js logo. Variants: `default` (default).
 * License: MIT. Trademarks belong to their owners.
 */
export function PassportJsLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
