// Generated by @qeetrix/icons from icons/brand-icons/auth-badges/pebblehost-badge/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC0-1.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 1024, 1024],
      children: '[["circle",{"cx":"512","cy":"512","r":"512","style":{"fill":"#57bb60"}}],["path",{"d":"M475.24 254.68a82 82 0 0 1 46.92-8 84.16 84.16 0 0 1 32.27 11q96.69 55.85 193.39 111.67-.07 111.76 0 223.51c.87 24.23-10.23 48.44-28.71 64a90.26 90.26 0 0 1-15.77 10.71c-28.07 16.29-56.28 32.32-84.35 48.59-35.7 20.55-71.27 41.35-107 61.82-22.39-13-44.87-25.82-67.2-38.9.07-34.13 0-68.26.05-102.39 22.48 12.74 44.79 25.8 67.17 38.71q73.49-42.5 147.07-84.84V420.63c-49.12-28.22-98.09-56.71-147.23-84.91q-73.45 42.61-147 85v272.21q-17.14-9.86-34.25-19.77c-7.75-4.67-16-8.63-23.07-14.3a82.14 82.14 0 0 1-29.61-47.94c-1.5-6.86-1.72-13.91-1.74-20.91v-46.89c.3-12.26.08-24.53.15-36.79V369.4q71.66-41.34 143.3-82.72c11.46-6.89 23.13-13.44 34.69-20.17 6.94-3.94 13.77-8.19 20.92-11.83ZM444.5 466.62q33.75-19.53 67.53-39 33.72 19.5 67.45 39v78q-33.7 19.51-67.46 38.94-33.74-19.51-67.52-39-.01-38.97 0-77.94Z","style":{"fill":"#fff"}}]]',
    },
  },
};

/**
 * PebbleHost logo. Variants: `default` (default).
 * License: CC0-1.0. Trademarks belong to their owners.
 */
export function PebblehostBadgeLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
