// Generated by @qeetrix/icons from icons/brand-icons/brands/picoclaw/default.svg, icons/brand-icons/brands/picoclaw/mono.svg.
// Each file is embedded unmodified: percent-decoding its data URI gives back the file byte for byte.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default" | "mono";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: { width: 24, height: 24, src: 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="%232d6a8a">%0A  <title>PicoClaw</title>%0A  %3C!-- Body -->%0A  <ellipse cx="12" cy="12.5" rx="5.5" ry="6"/>%0A  %3C!-- Head bump -->%0A  <ellipse cx="12" cy="7.5" rx="4" ry="3.5"/>%0A  %3C!-- Antennae -->%0A  <path d="M9.5 5.5 Q7 2 5.5 2.5" stroke="%232d6a8a" stroke-width="1" fill="none" stroke-linecap="round"/>%0A  <path d="M14.5 5.5 Q17 2 18.5 2.5" stroke="%232d6a8a" stroke-width="1" fill="none" stroke-linecap="round"/>%0A  <circle cx="5.2" cy="2.5" r="1" fill="%232d6a8a"/>%0A  <circle cx="18.8" cy="2.5" r="1" fill="%232d6a8a"/>%0A  %3C!-- Left claw -->%0A  <path d="M5.5 10 Q2 8.5 2 11 Q2 13.5 5 12.5" fill="%23e05c5c"/>%0A  %3C!-- Right claw -->%0A  <path d="M18.5 10 Q22 8.5 22 11 Q22 13.5 19 12.5" fill="%23e05c5c"/>%0A  %3C!-- Tail segments -->%0A  <rect x="10" y="18" width="4" height="2" rx="1"/>%0A  <rect x="10.5" y="20" width="3" height="1.5" rx=".75"/>%0A  <path d="M10 21.5 Q12 23.5 14 21.5" fill="%232d6a8a"/>%0A  %3C!-- Eyes -->%0A  <circle cx="10" cy="7" r="1.8" fill="%23fff"/>%0A  <circle cx="14" cy="7" r="1.8" fill="%23fff"/>%0A  <circle cx="10.3" cy="6.8" r="1" fill="%230a1929"/>%0A  <circle cx="14.3" cy="6.8" r="1" fill="%230a1929"/>%0A  %3C!-- Chip/circuit pattern on body -->%0A  <rect x="10" y="11" width="4" height="3" rx=".8" fill="%231a4a6a" opacity=".5"/>%0A  <line x1="11" y1="11" x2="11" y2="14" stroke="%234a9aba" stroke-width=".3" opacity=".6"/>%0A  <line x1="13" y1="11" x2="13" y2="14" stroke="%234a9aba" stroke-width=".3" opacity=".6"/>%0A  <line x1="10" y1="12.5" x2="14" y2="12.5" stroke="%234a9aba" stroke-width=".3" opacity=".6"/>%0A</svg>%0A' },
    mono: { width: 24, height: 24, src: 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">%0A  <title>PicoClaw</title>%0A  <ellipse cx="12" cy="12.5" rx="5.5" ry="6"/>%0A  <ellipse cx="12" cy="7.5" rx="4" ry="3.5"/>%0A  <path d="M9.5 5.5 Q7 2 5.5 2.5" stroke="currentColor" stroke-width="1" fill="none" stroke-linecap="round"/>%0A  <path d="M14.5 5.5 Q17 2 18.5 2.5" stroke="currentColor" stroke-width="1" fill="none" stroke-linecap="round"/>%0A  <circle cx="5.2" cy="2.5" r="1"/>%0A  <circle cx="18.8" cy="2.5" r="1"/>%0A  <path d="M5.5 10 Q2 8.5 2 11 Q2 13.5 5 12.5"/>%0A  <path d="M18.5 10 Q22 8.5 22 11 Q22 13.5 19 12.5"/>%0A  <rect x="10" y="18" width="4" height="2" rx="1"/>%0A  <rect x="10.5" y="20" width="3" height="1.5" rx=".75"/>%0A  <path d="M10 21.5 Q12 23.5 14 21.5"/>%0A</svg>%0A' },
  },
};

/**
 * PicoClaw logo. Variants: `default` (default), `mono`.
 * License: MIT. Trademarks belong to their owners.
 */
export function PicoclawLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
