// Generated by @qeetrix/icons from icons/brand-icons/brands/pingdom/default.svg, icons/brand-icons/brands/pingdom/mono.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC0-1.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default" | "mono";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 24, 24],
      props: { fill: "#FFF000" },
      children: '[["path",{"d":"M11.96 17.804l7.959-3.396-7.049 7.241c-.124-1.315-.432-2.61-.91-3.844v-.001zM24 11.118c-5.101-.236-10.208.414-15.087 1.92 1.024 1.073 1.881 2.292 2.535 3.621 4.042-2.25 9.646-5.123 12.552-5.531v-.015.005zm-12.574.275l.207-.06c1.538-.459 3.049-1.015 4.523-1.656 1.492-.585 2.896-1.38 4.159-2.367 1.345-1.069 2.355-2.499 2.915-4.122.12-.267.211-.549.267-.837-2.024 2.76-10.041 3.048-10.041 3.048l1.89-1.734C9.84 3.684 4.47 5.424 0 8.645c3.03.322 5.877 1.596 8.139 3.634 1.086-.336 2.196-.576 3.286-.879v-.006l.001-.001z"}]]',
    },
    mono: {
      viewBox: [0, 0, 24, 24],
      props: { fill: "currentColor" },
      children: '[["path",{"d":"M11.96 17.804l7.959-3.396-7.049 7.241c-.124-1.315-.432-2.61-.91-3.844v-.001zM24 11.118c-5.101-.236-10.208.414-15.087 1.92 1.024 1.073 1.881 2.292 2.535 3.621 4.042-2.25 9.646-5.123 12.552-5.531v-.015.005zm-12.574.275l.207-.06c1.538-.459 3.049-1.015 4.523-1.656 1.492-.585 2.896-1.38 4.159-2.367 1.345-1.069 2.355-2.499 2.915-4.122.12-.267.211-.549.267-.837-2.024 2.76-10.041 3.048-10.041 3.048l1.89-1.734C9.84 3.684 4.47 5.424 0 8.645c3.03.322 5.877 1.596 8.139 3.634 1.086-.336 2.196-.576 3.286-.879v-.006l.001-.001z"}]]',
    },
  },
};

/**
 * Pingdom logo. Variants: `default` (default), `mono`.
 * License: CC0-1.0. Trademarks belong to their owners.
 */
export function PingdomLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
