// Generated by @qeetrix/icons from icons/brand-icons/brands/qlty/default.svg, icons/brand-icons/brands/qlty/mono.svg.
// Each file is embedded unmodified: percent-decoding its data URI gives back the file byte for byte.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC0-1.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default" | "mono";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: { width: 24, height: 24, src: 'data:image/svg+xml,<svg fill="%2366FAEC" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Qlty</title><path d="M12.453 20.437h10.204V24H12.453Zm2.456-.8 8.868-9.812L14.897 0l-2.444 2.7 6.437 7.125-6.437 7.124ZM9.102 0 .223 9.825l8.868 9.814 2.456-2.69L5.11 9.825 11.55 2.7Z"/></svg>' },
    mono: { width: 24, height: 24, src: 'data:image/svg+xml,<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Qlty</title><path d="M12.453 20.437h10.204V24H12.453Zm2.456-.8 8.868-9.812L14.897 0l-2.444 2.7 6.437 7.125-6.437 7.124ZM9.102 0 .223 9.825l8.868 9.814 2.456-2.69L5.11 9.825 11.55 2.7Z"/></svg>' },
  },
};

/**
 * Qlty logo. Variants: `default` (default), `mono`.
 * License: CC0-1.0. Trademarks belong to their owners.
 */
export function QltyLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
