// Generated by @qeetrix/icons from icons/brand-icons/brands/react-wheel-picker/default.svg, icons/brand-icons/brands/react-wheel-picker/dark.svg, icons/brand-icons/brands/react-wheel-picker/light.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default" | "dark" | "light";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 256, 256],
      props: { fill: "none" },
      children: '[["path",{"d":"M144 16h-32a64.07 64.07 0 0 0-64 64v96a64.069 64.069 0 0 0 64 64h32a64.068 64.068 0 0 0 64-64V80a64.07 64.07 0 0 0-64-64Zm2.34 146.34a8.004 8.004 0 0 1 11.32 11.32l-24 24a7.986 7.986 0 0 1-5.66 2.346 8 8 0 0 1-5.66-2.346l-24-24a8.004 8.004 0 1 1 11.32-11.32L120 172.69V83.31l-10.34 10.35a8.004 8.004 0 1 1-11.32-11.32l24-24a8 8 0 0 1 11.32 0l24 24a8.005 8.005 0 0 1-11.32 11.32L136 83.31v89.38l10.34-10.35Z","fill":"#fff"}]]',
    },
    dark: {
      viewBox: [0, 0, 256, 256],
      props: { fill: "none" },
      children: '[["path",{"d":"M144 16h-32a64.07 64.07 0 0 0-64 64v96a64.069 64.069 0 0 0 64 64h32a64.068 64.068 0 0 0 64-64V80a64.07 64.07 0 0 0-64-64Zm2.34 146.34a8.004 8.004 0 0 1 11.32 11.32l-24 24a7.986 7.986 0 0 1-5.66 2.346 8 8 0 0 1-5.66-2.346l-24-24a8.004 8.004 0 1 1 11.32-11.32L120 172.69V83.31l-10.34 10.35a8.004 8.004 0 1 1-11.32-11.32l24-24a8 8 0 0 1 11.32 0l24 24a8.005 8.005 0 0 1-11.32 11.32L136 83.31v89.38l10.34-10.35Z","fill":"#fff"}]]',
    },
    light: {
      viewBox: [0, 0, 256, 256],
      props: { fill: "none" },
      children: '[["path",{"d":"M144 16h-32a64.07 64.07 0 0 0-64 64v96a64.069 64.069 0 0 0 64 64h32a64.068 64.068 0 0 0 64-64V80a64.07 64.07 0 0 0-64-64Zm2.34 146.34a8.004 8.004 0 0 1 11.32 11.32l-24 24a7.986 7.986 0 0 1-5.66 2.346 8 8 0 0 1-5.66-2.346l-24-24a8.004 8.004 0 1 1 11.32-11.32L120 172.69V83.31l-10.34 10.35a8.004 8.004 0 1 1-11.32-11.32l24-24a8 8 0 0 1 11.32 0l24 24a8.005 8.005 0 0 1-11.32 11.32L136 83.31v89.38l10.34-10.35Z","fill":"#000"}]]',
    },
  },
};

/**
 * React Wheel Picker logo. Variants: `default` (default), `dark`, `light`.
 * License: MIT. Trademarks belong to their owners.
 */
export function ReactWheelPickerLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
