// Generated by @qeetrix/icons from icons/brand-icons/brands/rsshub/color.svg, icons/brand-icons/brands/rsshub/default.svg, icons/brand-icons/brands/rsshub/mono.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "color" | "default" | "mono";

const data: LogoData<Variant> = {
  defaultVariant: "color",
  variants: {
    color: {
      viewBox: [0, 0, 24, 24],
      children: '[["path",{"d":"M1.13 6.646C1.046 7.084 1 7.536 1 8v8a7 7 0 007 7h8a7.04 7.04 0 001.354-.13A12.154 12.154 0 0018.5 17.7c0-6.738-5.462-12.2-12.2-12.2-1.848 0-3.6.41-5.17 1.146z","fill":"#FF8549"}],["circle",{"cx":"6.25","cy":"17.75","fill":"#FF2900","r":"4.55"}],["rect",{"fill":"#FFD6A6","height":"22","rx":"7","width":"22","x":"1","y":"1"}]]',
    },
    default: {
      viewBox: [0, 0, 24, 24],
      children: '[["path",{"d":"M1.13 6.646C1.046 7.084 1 7.536 1 8v8a7 7 0 007 7h8a7.04 7.04 0 001.354-.13A12.154 12.154 0 0018.5 17.7c0-6.738-5.462-12.2-12.2-12.2-1.848 0-3.6.41-5.17 1.146z","fill":"#FF8549"}],["circle",{"cx":"6.25","cy":"17.75","fill":"#FF2900","r":"4.55"}],["rect",{"fill":"#FFD6A6","height":"22","rx":"7","width":"22","x":"1","y":"1"}]]',
    },
    mono: {
      viewBox: [0, 0, 24, 24],
      props: { fill: "currentColor", fillRule: "evenodd" },
      children: '[["path",{"d":"M1.13 6.646C1.046 7.084 1 7.536 1 8v8a7 7 0 007 7h8a7.04 7.04 0 001.354-.13A12.154 12.154 0 0018.5 17.7c0-6.738-5.462-12.2-12.2-12.2-1.848 0-3.6.41-5.17 1.146z","fillOpacity":".33"}],["circle",{"cx":"6.25","cy":"17.75","r":"4.55"}],["rect",{"height":"22","rx":"7","width":"22","x":"1","y":"1"}]]',
    },
  },
};

/**
 * RSSHub logo. Variants: `color` (default), `default`, `mono`.
 * License: MIT. Trademarks belong to their owners.
 */
export function RsshubLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
