// Generated by @qeetrix/icons from icons/brand-icons/brands/sam-s-club/default.svg, icons/brand-icons/brands/sam-s-club/mono.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC0-1.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default" | "mono";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 24, 24],
      props: { fill: "#0067A0" },
      children: '[["path",{"d":"m14.275 1.71 9.403 9.504a1.119 1.119 0 0 1 .001 1.569l-9.401 9.507-1.624-1.64a1.136 1.136 0 0 1 0-1.596L19.631 12l-6.917-6.99a1.225 1.225 0 0 1 0-1.72l1.56-1.579zm-3.026 1.572L9.695 1.71.34 11.17a1.186 1.186 0 0 0 0 1.663l9.356 9.457 1.553-1.57a1.237 1.237 0 0 0 0-1.737L4.341 12l6.909-6.985a1.235 1.235 0 0 0-.001-1.734z"}]]',
    },
    mono: {
      viewBox: [0, 0, 24, 24],
      props: { fill: "currentColor" },
      children: '[["path",{"d":"m14.275 1.71 9.403 9.504a1.119 1.119 0 0 1 .001 1.569l-9.401 9.507-1.624-1.64a1.136 1.136 0 0 1 0-1.596L19.631 12l-6.917-6.99a1.225 1.225 0 0 1 0-1.72l1.56-1.579zm-3.026 1.572L9.695 1.71.34 11.17a1.186 1.186 0 0 0 0 1.663l9.356 9.457 1.553-1.57a1.237 1.237 0 0 0 0-1.737L4.341 12l6.909-6.985a1.235 1.235 0 0 0-.001-1.734z"}]]',
    },
  },
};

/**
 * Sam's Club logo. Variants: `default` (default), `mono`.
 * License: CC0-1.0. Trademarks belong to their owners.
 */
export function SamSClubLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
