// Generated by @qeetrix/icons from icons/brand-icons/community/sonarlint/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: brand-use. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 256, 256],
      children: '[["g",{"fill":"#cb2029"},["path",{"d":"M128 256C57.42 256 0 198.587 0 128S57.42 0 128 0s128 57.413 128 128s-57.42 128-128 128m0-232.799c-57.747 0-104.757 46.993-104.757 104.733S70.253 232.668 128 232.668s104.757-46.993 104.757-104.734S185.747 23.201 128 23.201"}],["path",{"d":"M217.777 121.322c-3.339-6.679-7.529-15.06-15.779-15.06c-8.184 0-12.374 8.316-15.779 15.06c-3.142 6.22-4.91 9.493-8.839 9.493c-3.928 0-5.696-3.273-8.838-9.493c-3.34-6.679-7.53-15.06-15.78-15.06s-12.374 8.316-15.778 15.06c-3.143 6.22-4.91 9.493-8.84 9.493c-3.928 0-5.695-3.273-8.838-9.493c-3.34-6.679-7.53-15.06-15.78-15.06s-12.374 8.316-15.778 15.06c-3.143 6.22-4.91 9.493-8.84 9.493c-3.928 0-5.695-3.273-8.838-9.493c-3.34-6.679-7.53-15.06-15.779-15.06c-8.184 0-12.374 7.923-15.714 14.601c0 0-2.553 5.697-3.666 8.381s-5.434 12.898-1.506 17.809c2.226 2.75 5.434-1.179 7.268-4.06c1.374-2.226 4.648-8.642 4.648-8.642c3.34-5.958 5.107-9.166 8.97-9.166c3.928 0 5.696 3.273 8.839 9.493c3.339 6.679 7.53 15.06 15.779 15.06c8.184 0 12.374-8.316 15.779-15.06c3.143-6.22 4.91-9.493 8.839-9.493c3.928 0 5.696 3.273 8.839 9.493c3.339 6.679 7.53 15.06 15.779 15.06c8.184 0 12.374-8.316 15.779-15.06c3.142-6.22 4.91-9.493 8.839-9.493c3.928 0 5.696 3.273 8.838 9.493c3.34 6.679 7.53 15.06 15.78 15.06s12.374-8.316 15.779-15.06c3.142-6.22 4.91-9.493 8.838-9.493c3.929 0 5.697 3.273 8.84 9.493c0 0 1.44 2.816 3.535 6.482c.916 1.506 4.321 7.268 7.333 7.071c2.684-.196 3.666-8.708.655-16.172c-2.03-4.976-4.584-10.737-4.584-10.737"}]]]',
    },
  },
};

/**
 * SonarLint logo. Variants: `default` (default).
 * License: brand-use. Trademarks belong to their owners.
 */
export function SonarlintLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
