// Generated by @qeetrix/icons from icons/brand-icons/auth-badges/startmail-badge/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC0-1.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 1024, 1024],
      children: '[["circle",{"cx":"512","cy":"512","r":"512","style":{"fill":"#6573ff"}}],["path",{"d":"M724 374.9v-34.7c0-22.2-18-40.2-40.2-40.2H340.2c-22.2 0-40.2 18-40.2 40.2V374c15.7 15.3 162.3 154 212.7 154 53.6 0 194.7-136.9 211.3-153.1zm-75.4 126.2c-57.8 52.2-103.6 78.6-135.9 78.6-73.1 0-197-110.5-212.7-125.3v229.3c0 22.2 18 40.2 40.2 40.2h343.5c22.2 0 40.2-18 40.2-40.2V424.8c-7.3 8.4-37.8 42.6-75.3 76.3z","style":{"fill":"#fff"}}]]',
    },
  },
};

/**
 * StartMail logo. Variants: `default` (default).
 * License: CC0-1.0. Trademarks belong to their owners.
 */
export function StartmailBadgeLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
