// Generated by @qeetrix/icons from icons/brand-icons/brands/storyblok/default.svg, icons/brand-icons/brands/storyblok/mono.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC0-1.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default" | "mono";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 256, 302],
      props: { preserveAspectRatio: "xMidYMid" },
      children: '[["path",{"d":"m244.495 0-.274.292c7.15 0 11.524 5.54 11.768 12.32l.011.6v230.552c0 7.12-4.156 11.473-10.852 11.73l-.635.013H89.558l-42.423 45.82v-46.112H12.966c-6.868 0-12.619-4.146-12.95-10.844L0 243.755V12.921C0 6.067 5.567.327 12.648.013l.61-.013h231.237Zm-78.93 46.989H47.135v164.47H151.43c7.954 0 15.615-1.47 22.682-3.233 6.605-1.364 12.43-4.278 17.729-7.519l1.127-.699a35.547 35.547 0 0 0 12.08-11.94l.585-.99h-.302c2.94-5.277 4.42-11.45 4.42-18.792 0-11.45-2.657-20.563-7.962-27.612-5.589-6.748-12.957-11.45-22.38-14.09a36.78 36.78 0 0 0 17.668-15.86c3.835-7.05 5.899-14.39 5.899-22.024a43.966 43.966 0 0 0-10.017-28.49c-3.242-3.825-7.369-7.049-11.78-9.404-4.405-2.463-9.058-3.654-14.447-3.801l-1.167-.016Zm-16.929 91.923c3.406 0 5.963 1.662 8.237 4.447a16.418 16.418 0 0 1 3.122 9.998c0 4.164-1.424 7.497-3.689 9.725-2.374 2.06-5.236 3.404-8.36 3.586l-.725.02H89.604v-27.776h59.032Zm-4.82-55.563c2.709.026 5.322 1.01 7.377 2.776 1.99 1.945 3.123 5.004 3.123 9.167 0 4.459-1.01 7.932-3.276 9.704l-.413.295c-2.099 1.542-4.68 2.844-7.291 3.035l-.653.024H89.595V83.349h54.22Z","fill":"#0AB3AF"}]]',
    },
    mono: {
      viewBox: [0, 0, 24, 24],
      props: { fill: "currentColor" },
      children: '[["path",{"d":"M13.953 11.462H9.088v2.34h4.748c.281 0 .538-.118.749-.305.187-.187.304-.468.304-.819a1.404 1.404 0 0 0-.257-.842c-.188-.234-.398-.374-.679-.374zm.164-2.83c.21-.14.304-.445.304-.843 0-.35-.094-.608-.257-.771a.935.935 0 0 0-.608-.234H9.088v2.105h4.374c.234 0 .468-.117.655-.257zM21.251 0H2.89c-.585 0-1.053.468-1.053 1.03v18.385c0 .562.468.912 1.03.912H5.58V24l3.368-3.65h12.304c.562 0 .913-.35.913-.935V1.053c0-.562-.351-1.03-.936-1.03zm-3.087 14.9a2.827 2.827 0 0 1-1.006 1.03c-.445.28-.936.538-1.497.655-.562.14-1.17.257-1.801.257H5.579v-13.1h9.403c.468 0 .866.094 1.24.305.351.187.679.444.936.748.524.64.806 1.443.795 2.27 0 .608-.164 1.192-.468 1.754a2.924 2.924 0 0 1-1.403 1.263c.748.21 1.333.585 1.778 1.123.42.561.631 1.286.631 2.199 0 .584-.117 1.076-.35 1.497z"}]]',
    },
  },
};

/**
 * Storyblok logo. Variants: `default` (default), `mono`.
 * License: CC0-1.0. Trademarks belong to their owners.
 */
export function StoryblokLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
