// Generated by @qeetrix/icons from icons/brand-icons/brands/titanium/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: GPL-2.0-only. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import { type ReactElement, useId } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 512, 512],
      scoped: true,
      children: '[["defs",null,["clipPath",{"id":"\\u00010"},["circle",{"cx":"256","cy":"256","r":"208"}]]],["g",{"transform":"translate(256 256) scale(1) translate(-256 -256)"},["g",{"clipPath":"url(#\\u00010)"},["rect",{"fill":"#1c1c31","height":"1512","width":"1512","x":"-500","y":"-500"}]],["g",null,["ellipse",{"cx":"256","cy":"256","fill":"none","rx":"156","ry":"78","stroke":"#50507a","strokeWidth":"12","transform":"rotate(-30 256 256)"}],["circle",{"cx":"256","cy":"256","fill":"#23233b","r":"94.5","stroke":"#ffffff","strokeWidth":"19"}],["circle",{"cx":"391","cy":"178","fill":"#9393bf","r":"36"}],["circle",{"cx":"121","cy":"334","fill":"#9393bf","r":"36"}]]]]',
    },
  },
};

/**
 * Titanium logo. Variants: `default` (default).
 * License: GPL-2.0-only. Trademarks belong to their owners.
 */
export function TitaniumLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props, useId());
}
