// Generated by @qeetrix/icons from icons/brand-icons/brands/tor/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import { type ReactElement, useId } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 256, 256],
      props: { preserveAspectRatio: "xMidYMid" },
      scoped: true,
      children: '[["defs",null,["linearGradient",{"id":"\\u00010","x1":"50%","x2":"50%","y1":"100%","y2":"0%"},["stop",{"offset":"0%","stopColor":"#420C5D"}],["stop",{"offset":"100%","stopColor":"#951AD1"}]],["linearGradient",{"id":"\\u00011","x1":"50%","x2":"50%","y1":"100%","y2":"0%"},["stop",{"offset":"0%","stopColor":"#420C5D"}],["stop",{"offset":"100%","stopColor":"#951AD1"}]]],["circle",{"cx":"128","cy":"128","fill":"#F2E4FF","r":"123"}],["path",{"d":"M128.263 232.72v-15.517c49.15-.142 88.947-40.02 88.947-89.207 0-49.182-39.797-89.06-88.947-89.203V23.277c57.72.145 104.46 46.968 104.46 104.72 0 57.755-46.74 104.58-104.46 104.723Zm0-54.31c27.722-.145 50.161-22.652 50.161-50.414 0-27.758-22.439-50.264-50.161-50.41V62.073c36.295.142 65.678 29.596 65.678 65.923 0 36.331-29.383 65.785-65.678 65.927V178.41Zm0-77.55c14.87.141 26.888 12.23 26.888 27.136 0 14.91-12.018 27-26.888 27.141V100.86ZM0 127.995C0 198.692 57.304 256 128 256c70.692 0 128-57.308 128-128.004C256 57.304 198.692 0 128 0 57.304 0 0 57.304 0 127.996Z","fill":"url(#\\u00010)"}],["path",{"d":"M12.5 14.5c63.789 0 115.5 51.487 115.5 115s-51.711 115-115.5 115v-230Z","fill":"url(#\\u00011)","transform":"matrix(-1 0 0 1 140.5 0)"}]]',
    },
  },
};

/**
 * Tor logo. Variants: `default` (default).
 * License: MIT. Trademarks belong to their owners.
 */
export function TorLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props, useId());
}
