// Generated by @qeetrix/icons from icons/brand-icons/auth-badges/tresorit-badge/default.svg.
// Each file is embedded unmodified: percent-decoding its data URI gives back the file byte for byte.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC0-1.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: { width: 1024, height: 1024, src: 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024">%0A   <circle cx="512" cy="512" r="512" style="fill:%232b6df1"/>%0A   <path d="M512 241.92 278.75 377v270L512 782.08 745.25 647V377ZM327.86 405.27 512 298.67l80.44 46.56-264.58 152Zm368.28 213.45L512 725.33 327.86 618.72v-64.86l313.69-180.2 54.6 31.61Z" style="fill:%23fff"/>%0A</svg>%0A' },
  },
};

/**
 * Tresorit logo. Variants: `default` (default).
 * License: CC0-1.0. Trademarks belong to their owners.
 */
export function TresoritBadgeLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
