// Generated by @qeetrix/icons from icons/brand-icons/brands/trust-wallet/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import { type ReactElement, useId } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 444, 501],
      props: { fill: "none" },
      scoped: true,
      children: '[["path",{"d":"M0.710022 72.41L222.16 0.109985V500.63C63.98 433.89 0.710022 305.98 0.710022 233.69V72.41Z","fill":"#0500FF"}],["path",{"d":"M443.62 72.41L222.17 0.109985V500.63C380.35 433.89 443.62 305.98 443.62 233.69V72.41Z","fill":"url(#\\u00010)"}],["defs",null,["linearGradient",{"gradientUnits":"userSpaceOnUse","id":"\\u00010","x1":"385.26","x2":"216.61","y1":"-34.78","y2":"493.5"},["stop",{"offset":"0.02","stopColor":"#0000FF"}],["stop",{"offset":"0.08","stopColor":"#0094FF"}],["stop",{"offset":"0.16","stopColor":"#48FF91"}],["stop",{"offset":"0.42","stopColor":"#0094FF"}],["stop",{"offset":"0.68","stopColor":"#0038FF"}],["stop",{"offset":"0.9","stopColor":"#0500FF"}]]]]',
    },
  },
};

/**
 * Trust Wallet logo. Variants: `default` (default).
 * License: MIT. Trademarks belong to their owners.
 */
export function TrustWalletLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props, useId());
}
