// Generated by @qeetrix/icons from icons/brand-icons/brands/unreal-engine/default.svg, icons/brand-icons/brands/unreal-engine/dark.svg, icons/brand-icons/brands/unreal-engine/light.svg, icons/brand-icons/brands/unreal-engine/mono.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC0-1.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default" | "dark" | "light" | "mono";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 256, 256],
      props: { fill: "none" },
      children: '[["path",{"clipRule":"evenodd","d":"M201.2 145.8a75 75 0 01-41.7 50.7l-12-13.6-20.5 20.5A75.4 75.4 0 0167.4 173c2.2.6 4.4 1 6.7 1.2 3.3 0 7-1.1 7-6.8V112a9.1 9.1 0 00-11.5-9.1c-9.5 2.2-17 25.8-17 25.8a75 75 0 0164.2-75.2c-10.3 6-16 15.5-16 23.5 0 13 7.7 11.4 10 9.5v74.8a11.9 11.9 0 005.5 6 11 11 0 005 1.2c7.9 0 18-9 18-9V99a21 21 0 00-9.3-16.2s8.6-1.5 15.3 3.6a75 75 0 0146.2-26s-22.1 17.3-22.1 40.6c0 17.3.4 59.6.4 59.6 8.2 7.9 20.4-3.6 31.4-14.8z","fill":"#fff","fillRule":"evenodd"}],["path",{"clipRule":"evenodd","d":"M128 4.8a123.2 123.2 0 100 246.4 123.2 123.2 0 000-246.4zm0 241.5a118.3 118.3 0 110-236.6 118.3 118.3 0 010 236.6z","fill":"#fff","fillRule":"evenodd"}]]',
    },
    dark: {
      viewBox: [0, 0, 256, 256],
      props: { fill: "none" },
      children: '[["path",{"clipRule":"evenodd","d":"M201.2 145.8a75 75 0 01-41.7 50.7l-12-13.6-20.5 20.5A75.4 75.4 0 0167.4 173c2.2.6 4.4 1 6.7 1.2 3.3 0 7-1.1 7-6.8V112a9.1 9.1 0 00-11.5-9.1c-9.5 2.2-17 25.8-17 25.8a75 75 0 0164.2-75.2c-10.3 6-16 15.5-16 23.5 0 13 7.7 11.4 10 9.5v74.8a11.9 11.9 0 005.5 6 11 11 0 005 1.2c7.9 0 18-9 18-9V99a21 21 0 00-9.3-16.2s8.6-1.5 15.3 3.6a75 75 0 0146.2-26s-22.1 17.3-22.1 40.6c0 17.3.4 59.6.4 59.6 8.2 7.9 20.4-3.6 31.4-14.8z","fill":"#fff","fillRule":"evenodd"}],["path",{"clipRule":"evenodd","d":"M128 4.8a123.2 123.2 0 100 246.4 123.2 123.2 0 000-246.4zm0 241.5a118.3 118.3 0 110-236.6 118.3 118.3 0 010 236.6z","fill":"#fff","fillRule":"evenodd"}]]',
    },
    light: {
      viewBox: [0, 0, 256, 256],
      props: { fill: "none" },
      children: '[["path",{"clipRule":"evenodd","d":"M201.2 145.8a75 75 0 01-41.7 50.7l-12-13.6-20.5 20.5A75.4 75.4 0 0167.4 173c2.2.6 4.4 1 6.7 1.2 3.3 0 7-1.1 7-6.8V112a9.1 9.1 0 00-11.5-9.1c-9.5 2.2-17 25.8-17 25.8a75 75 0 0164.2-75.2c-10.3 6-16 15.5-16 23.5 0 13 7.7 11.4 10 9.5v74.8a11.9 11.9 0 005.5 6 11 11 0 005 1.2c7.9 0 18-9 18-9V99a21 21 0 00-9.3-16.2s8.6-1.5 15.3 3.6a75 75 0 0146.2-26s-22.1 17.3-22.1 40.6c0 17.3.4 59.6.4 59.6 8.2 7.9 20.4-3.6 31.4-14.8z","fill":"#000","fillRule":"evenodd"}],["path",{"clipRule":"evenodd","d":"M128 4.8a123.2 123.2 0 100 246.4 123.2 123.2 0 000-246.4zm0 241.5a118.3 118.3 0 110-236.6 118.3 118.3 0 010 236.6z","fill":"#000","fillRule":"evenodd"}]]',
    },
    mono: {
      viewBox: [0, 0, 24, 24],
      props: { fill: "currentColor" },
      children: '[["path",{"d":"M12 0a12 12 0 1012 12A12 12 0 0012 0zm0 23.52A11.52 11.52 0 1123.52 12 11.52 11.52 0 0112 23.52zm7.13-9.791c-.206.997-1.126 3.557-4.06 4.942l-1.179-1.325-1.988 2a7.338 7.338 0 01-5.804-2.978 2.859 2.859 0 00.65.123c.326.006.678-.114.678-.66v-5.394a.89.89 0 00-1.116-.89c-.92.212-1.656 2.509-1.656 2.509a7.304 7.304 0 012.528-5.597 7.408 7.408 0 013.73-1.721c-1.006.573-1.57 1.507-1.57 2.29 0 1.262.76 1.109.984.923v7.28a1.157 1.157 0 00.148.256 1.075 1.075 0 00.88.445c.76 0 1.747-.868 1.747-.868V9.172c0-.6-.452-1.324-.905-1.572 0 0 .838-.149 1.484.346a5.537 5.537 0 01.387-.425c1.508-1.48 2.929-1.902 4.112-2.112 0 0-2.151 1.69-2.151 3.96 0 1.687.043 5.801.043 5.801.799.771 1.986-.342 3.059-1.441Z"}]]',
    },
  },
};

/**
 * Unreal Engine logo. Variants: `default` (default), `dark`, `light`, `mono`.
 * License: CC0-1.0. Trademarks belong to their owners.
 */
export function UnrealEngineLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
