// Generated by @qeetrix/icons from icons/brand-icons/auth-badges/upcloud-badge/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC0-1.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 1024, 1024],
      children: '[["circle",{"cx":"512","cy":"512","r":"512","style":{"fill":"#7b00ff"}}],["path",{"d":"M835 589.81a50.81 50.81 0 0 1-50.7 50.73h-362v-132h23.63V616.9h338.58a27.08 27.08 0 0 0 0-54.17H469.79v-23.65H784.3a50.81 50.81 0 0 1 50.7 50.73ZM212.63 512a27 27 0 0 1 27.07-27.08H551a50.73 50.73 0 0 0 0-101.46H422.52v54.17h23.63V407.1H551a27.08 27.08 0 0 1 0 54.17H239.7a50.84 50.84 0 0 0 0 101.67h159V539.3h-159a27.28 27.28 0 0 1-27.07-27.3Z","style":{"fill":"#fff"}}]]',
    },
  },
};

/**
 * UpCloud logo. Variants: `default` (default).
 * License: CC0-1.0. Trademarks belong to their owners.
 */
export function UpcloudBadgeLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
