// Generated by @qeetrix/icons from icons/brand-icons/brands/upstage/color.svg, icons/brand-icons/brands/upstage/default.svg, icons/brand-icons/brands/upstage/mono.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: MIT. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "color" | "default" | "mono";

const data: LogoData<Variant> = {
  defaultVariant: "color",
  variants: {
    color: {
      viewBox: [0, 0, 24, 24],
      props: { fill: "currentColor", fillRule: "evenodd" },
      children: '[["path",{"d":"M19.763 0l-.373 1.297h2.594L22.354 0h-2.591z"}],["path",{"d":"M16.192 2.27l-.376 1.298h5.52l.37-1.298h-5.514z"}],["path",{"d":"M12.897 4.54l-.377 1.298h8.167l.37-1.297h-8.16z"}],["path",{"d":"M2.85 6.81l-.377 1.298h17.565l.37-1.297H2.85z"}],["path",{"d":"M3.884 9.081l-.376 1.297H19.39l.37-1.297H3.883z"}],["path",{"d":"M4.088 24l.376-1.297H1.866L1.5 24h2.588z"}],["path",{"d":"M7.662 21.73l.376-1.298H2.515L2.15 21.73h5.513z"}],["path",{"d":"M10.957 19.46l.377-1.298h-8.17l-.367 1.297h8.16z"}],["path",{"d":"M21.005 17.19l.376-1.298H3.812l-.366 1.297h17.559z"}],["path",{"d":"M19.967 14.919l.376-1.297H4.461l-.366 1.297h15.872z"}],["path",{"d":"M18.787 12.649l.376-1.298H4.26l-.366 1.298h14.893z"}]]',
    },
    default: {
      viewBox: [0, 0, 24, 24],
      props: { fill: "currentColor", fillRule: "evenodd" },
      children: '[["path",{"d":"M19.763 0l-.373 1.297h2.594L22.354 0h-2.591z"}],["path",{"d":"M16.192 2.27l-.376 1.298h5.52l.37-1.298h-5.514z"}],["path",{"d":"M12.897 4.54l-.377 1.298h8.167l.37-1.297h-8.16z"}],["path",{"d":"M2.85 6.81l-.377 1.298h17.565l.37-1.297H2.85z"}],["path",{"d":"M3.884 9.081l-.376 1.297H19.39l.37-1.297H3.883z"}],["path",{"d":"M4.088 24l.376-1.297H1.866L1.5 24h2.588z"}],["path",{"d":"M7.662 21.73l.376-1.298H2.515L2.15 21.73h5.513z"}],["path",{"d":"M10.957 19.46l.377-1.298h-8.17l-.367 1.297h8.16z"}],["path",{"d":"M21.005 17.19l.376-1.298H3.812l-.366 1.297h17.559z"}],["path",{"d":"M19.967 14.919l.376-1.297H4.461l-.366 1.297h15.872z"}],["path",{"d":"M18.787 12.649l.376-1.298H4.26l-.366 1.298h14.893z"}]]',
    },
    mono: {
      viewBox: [0, 0, 24, 24],
      props: { fill: "currentColor", fillRule: "evenodd" },
      children: '[["path",{"d":"M19.763 0l-.373 1.297h2.594L22.354 0h-2.591z"}],["path",{"d":"M16.192 2.27l-.376 1.298h5.52l.37-1.298h-5.514z"}],["path",{"d":"M12.897 4.54l-.377 1.298h8.167l.37-1.297h-8.16z"}],["path",{"d":"M2.85 6.81l-.377 1.298h17.565l.37-1.297H2.85z"}],["path",{"d":"M3.884 9.081l-.376 1.297H19.39l.37-1.297H3.883z"}],["path",{"d":"M4.088 24l.376-1.297H1.866L1.5 24h2.588z"}],["path",{"d":"M7.662 21.73l.376-1.298H2.515L2.15 21.73h5.513z"}],["path",{"d":"M10.957 19.46l.377-1.298h-8.17l-.367 1.297h8.16z"}],["path",{"d":"M21.005 17.19l.376-1.298H3.812l-.366 1.297h17.559z"}],["path",{"d":"M19.967 14.919l.376-1.297H4.461l-.366 1.297h15.872z"}],["path",{"d":"M18.787 12.649l.376-1.298H4.26l-.366 1.298h14.893z"}]]',
    },
  },
};

/**
 * Upstage logo. Variants: `color` (default), `default`, `mono`.
 * License: MIT. Trademarks belong to their owners.
 */
export function UpstageLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
