// Generated by @qeetrix/icons from icons/brand-icons/brands/verizon/default.svg, icons/brand-icons/brands/verizon/mono.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC0-1.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default" | "mono";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 24, 24],
      props: { fill: "#CD040B" },
      children: '[["path",{"d":"M18.302 0H22v.003L10.674 24H7.662L2 12h3.727l3.449 7.337z"}]]',
    },
    mono: {
      viewBox: [0, 0, 24, 24],
      props: { fill: "currentColor" },
      children: '[["path",{"d":"M18.302 0H22v.003L10.674 24H7.662L2 12h3.727l3.449 7.337z"}]]',
    },
  },
};

/**
 * Verizon logo. Variants: `default` (default), `mono`.
 * License: CC0-1.0. Trademarks belong to their owners.
 */
export function VerizonLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
