// Generated by @qeetrix/icons from icons/brand-icons/auth-badges/wpmu-dev-badge/default.svg.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC0-1.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: {
      viewBox: [0, 0, 1024, 1024],
      children: '[["circle",{"cx":"512","cy":"512","r":"512","style":{"fill":"#286ef1"}}],["path",{"d":"M653.78 558.64V358.22l-32.35 25.28v175.39a17.94 17.94 0 0 1-16.68 18.7 17.69 17.69 0 0 1-16.43-18.7v-93.26a52.06 52.06 0 0 0-49-54.59 52.06 52.06 0 0 0-48.78 54.84v93a17.69 17.69 0 0 1-16.43 18.7 17.94 17.94 0 0 1-16.68-18.7v-93.25a52.06 52.06 0 0 0-49-54.59 52.06 52.06 0 0 0-48 54.59V666.3l32.28-25.3V465.63a17.69 17.69 0 0 1 16.43-18.7 17.94 17.94 0 0 1 16.68 18.7v93a52.31 52.31 0 0 0 48 54.59 52.31 52.31 0 0 0 49-55.09v-92.5a17.69 17.69 0 0 1 16.43-18.7 17.94 17.94 0 0 1 16.75 18.7v93a52.06 52.06 0 0 0 48.78 54.59 52.31 52.31 0 0 0 49-55.09Zm57.37-241.35a267.38 267.38 0 0 0-57.37-44.73 278 278 0 0 0-282 0 269.66 269.66 0 0 0-61.92 48.52c-105.38 111.66-100.28 287.61 11.38 393s287.61 100.28 393-11.38a278.77 278.77 0 0 0-3-385.39Zm3 321.21C645.15 749.74 499 784 387.76 714.93a237.06 237.06 0 0 1-112.06-202.8 233.27 233.27 0 0 1 36.65-126.36 236.3 236.3 0 0 1 295.94-89.72 238.83 238.83 0 0 1 101.09 86.18 236.3 236.3 0 0 1 4.8 256.27Z","style":{"fill":"#fff"}}]]',
    },
  },
};

/**
 * WPMU DEV logo. Variants: `default` (default).
 * License: CC0-1.0. Trademarks belong to their owners.
 */
export function WpmuDevBadgeLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
