// Generated by @qeetrix/icons from icons/brand-icons/auth-badges/yahoo-badge/default.svg.
// Each file is embedded unmodified: percent-decoding its data URI gives back the file byte for byte.
// Upstream: https://github.com/glincker/thesvg at c75313597b8bb14982e433ddae1b705813c66c7c (3.3.12).
// Logo license: CC0-1.0. Trademarks belong to their owners.
// Do not edit this file directly. Edit the sources and run `bun run generate:logos`.

import type { ReactElement } from "react";
import { renderLogo } from "../../runtime/render-logo.js";
import type { LogoData, LogoProps } from "../../types/logo.js";

type Variant = "default";

const data: LogoData<Variant> = {
  defaultVariant: "default",
  variants: {
    default: { width: 1024, height: 1024, src: 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024">%0A   <circle cx="512" cy="512" r="512" style="fill:%236001d2"/>%0A   <path d="M256 390.61h101.45l59.06 151 59.83-151H575L426.38 748.15H327l40.66-94.74Zm332.7 143.54a61.36 61.36 0 1 0 61.37 61.35 61.36 61.36 0 0 0-61.37-61.35ZM768 275.85H657.83l-98.09 235.67h110.55Z" style="fill:%23fff"/>%0A</svg>%0A' },
  },
};

/**
 * Yahoo logo. Variants: `default` (default).
 * License: CC0-1.0. Trademarks belong to their owners.
 */
export function YahooBadgeLogo(props: LogoProps<Variant>): ReactElement {
  return renderLogo(data, props);
}
